import { RAIL_V1_CLIENT_STALE, RAIL_V1_PARSE_FAIL } from "../contract/v1";

/** Diyar B vatandaş cümleleri. Sahte başarı / boş home yok. SEN: sen, siz değil. */
export const RAIL_IS_COPY = {
  brand: "yetkin.ai",
  diyar: "Diyar B",
  boot: "Oturum doğrulanıyor.",
  retry: "Yeniden dene",
  back: "Listeye dön",
  signOut: "Çıkış",
  login: {
    testID: "dron-login",
    title: "Giriş",
    body: "Supabase oturumu native JWT üretir. Çerez yok. Amiral oturumu taşınmaz.",
    email: "E-posta",
    password: "Şifre",
    submit: "Giriş yap",
    pending: "Giriş yapılıyor.",
    verifying: "Oturum Amiral'de doğrulanıyor.",
    fail: "Giriş başarısız.",
    sessionFail: "Giriş oldu; v1 oturum ucu doğrulanamadı. Sahte tezgâh açılmaz.",
    unbound: "Supabase anon yapılandırması yok. Giriş henüz bağlanmadı.",
    apiMissing: "Amiral adresi (EXPO_PUBLIC_RAIL_API_BASE) yok. Sahte iş listesi üretilmez.",
  },
  stale: {
    testID: "dron-stale-lock",
    title: "Lütfen uygulamayı güncelleyiniz",
    body: RAIL_V1_CLIENT_STALE,
  },
  jobs: {
    title: "Açık işler",
    loading: "İş listesi yükleniyor.",
    loadingTestID: "dron-job-list-loading",
    readyTestID: "dron-job-list-ready",
    emptyTestID: "dron-job-list-empty",
    errorTestID: "dron-job-list-error",
    errorTitle: "Liste henüz yüklenemedi.",
    empty: "Şu an açık iş yok.",
    emptyHint: "Bu boşluk sunucunun OPEN listesidir; hata kartı değildir.",
  },
  job: {
    budgetLabel: "Bütçe",
    briefLabel: "İş brief'i",
    openOnly: "Teklif yalnız OPEN ilana gider.",
  },
  bid: {
    title: "Teklif",
    amountLabel: "Teklif tutarı (₺)",
    amountHint: "Tam sayı kuruş (amountMinor). Bant ₺250–₺50.000.",
    coverLabel: "Teklif notu",
    submit: "Teklif gönder",
    pending: "Teklif gönderiliyor.",
    success: "Teklif alındı.",
    invalidAmount: "Tutar tam sayı amountMinor üretmedi.",
    amountBand: "Teklif ₺250–₺50.000 bandında olmalıdır.",
    coverBand: "Teklif notu 4–2000 karakter olmalıdır.",
    conflict:
      "Bu niyet farklı bir teklifle kilitli. Yeni UUID sessiz basılmaz; yeni niyet ayrı eylemdir.",
    newIntent: "Yeni niyet aç",
    errorTestID: "dron-bid-error",
    successTestID: "dron-bid-success",
    formTestID: "dron-bid-form",
  },
  ownerBids: {
    title: "Teklifler",
    loading: "Teklifler yükleniyor.",
    loadingTestID: "dron-owner-bids-loading",
    readyTestID: "dron-owner-bids-ready",
    emptyTestID: "dron-owner-bids-empty",
    errorTestID: "dron-owner-bids-error",
    errorTitle: "Teklifler henüz yüklenemedi.",
    empty: "Bu ilana henüz teklif yok.",
    emptyHint: "Bu boşluk sunucunun SUBMITTED listesidir; hata kartı değildir.",
    noPii: "Usta kimliği yayınlanmaz. Kartta ad, e-posta veya avatar yoktur.",
    coverLabel: "Teklif notu",
  },
  accept: {
    submit: "Teklifi kabul et",
    confirmTitle: "Teklifi kabul et",
    confirmBody:
      "Bu onay lisanslı split (PSP) ile emaneti kilitler. Cüzdan bakiyesi ile fonlanmaz. Usta hemen almaz. Teklif tutarı istekten değiştirilemez.",
    confirm: "Onaylıyorum",
    cancel: "Vazgeç",
    pending: "Teklif kabul ediliyor.",
    errorTitle: "Teklif kabul edilemedi.",
    insufficientHint: "İlan açık kaldı. Freelancer kabulü cüzdan DEBIT ile yapılmaz.",
    stillOpen: "İlan açık kaldı.",
    unboundBlock: "Ödeme henüz bağlanmadı. Sahte kilit yazılmaz.",
    stripHint: "Cüzdan şeridi kabulü fonlamaz. Split bağlı değilse 503 döner.",
    formTestID: "dron-accept-form",
    errorTestID: "dron-accept-error",
    insufficientTestID: "dron-accept-insufficient",
    modalTestID: "dron-accept-confirm",
    paymentsClosed: "Ödeme sistemi pasif",
    paymentsClosedHint:
      "PayTR Pazaryeri Split bu fazda bağlı değil. Teklif kabulü 503 döner; cüzdan bakiyesi ile fonlanmaz. İlan açık kalır; sahte kilit yazılmaz.",
    paymentsClosedTestID: "dron-accept-payments-closed",
    paymentsPassiveTitle: "Ödeme sistemi pasif",
    paymentsPassiveBody:
      "Ödeme henüz bağlanmadı. PayTR Pazaryeri Split bu fazda pasif. Teklif kabulü cüzdan ile fonlanmaz; deneme dürüst 503 döner.",
    paymentsPassiveTestID: "dron-accept-payments-passive",
  },
  wallet: {
    liveTestID: "dron-wallet-live",
    unboundTestID: "dron-wallet-unbound",
    errorTestID: "dron-wallet-error",
    loadingTestID: "dron-wallet-loading",
    liveTitle: "Canlı bakiye",
    unboundTitle: "Cüzdan henüz yüklenemedi",
    unboundBody: "live: false sıfır bakiye değildir. Uydurma ₺0 basılmaz.",
    errorTitle: "Cüzdan şeridi okunamadı.",
    topUp: "Cüzdanı web'de yükle",
    webWallet: "Kasa pasaportunu aç",
    topUpHint:
      "Kart PayTR iFrame'dedir (HMAC kasa). Native IAP yok. Cüzdan şeridi teklif kabulünü fonlamaz. Split bağlı değilse kabul 503.",
    topUpTitle: "Kart ile yükle",
    topUpAmount: "Tutar (₺)",
    topUpName: "Ad soyad",
    topUpPhone: "Cep telefonu",
    topUpAddress: "Açık adres",
    topUpConsentDistance: "Mesafeli satış ve ön bilgi metnini okudum, kabul ediyorum.",
    topUpConsentDigital: "Dijital içeriğin anında ifasını kabul ediyorum.",
    topUpSubmit: "Kasayı aç",
    topUpPending: "Kasa hazırlanıyor.",
    topUpFail: "Yükleme başlatılamadı.",
    topUpSettled: "Bu tutar zaten hesabına geçmiş.",
  },
  bench: {
    title: "İşlerim",
    tab: "İşlerim",
    jobsTab: "Açık işler",
    loading: "İşlerin yükleniyor.",
    loadingTestID: "dron-bench-loading",
    readyTestID: "dron-bench-ready",
    emptyTestID: "dron-bench-empty",
    errorTestID: "dron-bench-error",
    errorTitle: "Tezgâh henüz yüklenemedi.",
    empty: "Şu an kayıtlı işin yok.",
    emptyHint: "Bu boşluk sunucunun sözleşme listesidir; hata kartı değildir.",
    inProgress: "Devam ediyor (emanet blokeli)",
    delivered: "Teslim edildi",
    released: "Hak Ediş Serbest Bırakıldı",
    refunded: "İade",
    disputed: "Tahkimde",
    untitled: "Başlık henüz yok",
    roleFreelancer: "Usta",
    roleClient: "İşveren",
    refresh: "Yenile",
    funded: "Bakiye kilitli",
    escrowOpaque: "Emanet kimliği opak referanstır; hold API çağrılmaz.",
  },
  delivery: {
    submit: "İşi Teslim Et",
    note: "Teslimat notu",
    pending: "Teslimat gönderiliyor.",
    errorTitle: "Teslimat gönderilemedi.",
    noteBand: "Teslimat notu 8–8000 karakter olmalıdır.",
    formTestID: "dron-delivery-form",
    errorTestID: "dron-delivery-error",
    hint: "Teslim, emanet serbest bırakması değildir. İşveren kabulü ayrıdır.",
  },
  release: {
    submit: "Teslimatı Onayla ve Öde",
    pending: "Hak ediş serbest bırakılıyor.",
    errorTitle: "Hak ediş serbest bırakılamadı.",
    success: "Hak Ediş Serbest Bırakıldı",
    hint: "Usta payı yetkin.ai cüzdanına yazılmaz. Dağıtım lisanslı kuruluştadır; split pasifken 503 döner.",
    gross: "Brüt (kilitli)",
    hold: "Platform hold",
    net: "Usta net",
    formTestID: "dron-release-form",
    errorTestID: "dron-release-error",
  },
  phase2Lock: {
    testID: "dron-phase2-lock",
    kicker: "Faz 2",
    title: "Yansıtma bekleniyor",
    body: "Tezgâh (açık işler / işlerim) bu kapalı testte yayında değil. İnceleme yüzeyi Akademi halkasıdır: giriş, cüzdan, satın alma, ders, sınav, mühürlü sertifika.",
  },
  academy: {
    tab: "Akademi",
    title: "Eğitimler",
    catalogHint:
      "Amiral eğitim kernel katalog kimliğidir. Satın alma ve müfredat /api/v1 hop'larıdır. Native IAP yoktur.",
    continue: "Kaldığın yerden devam et",
    open: "Müfredatı aç",
    pulseLoading: "Akademi nabzı yükleniyor.",
    pulseLoadingTestID: "dron-academy-pulse-loading",
    pulseReadyTestID: "dron-academy-pulse-ready",
    pulseErrorTestID: "dron-academy-pulse-error",
    pulseErrorTitle: "Akademi nabzı okunamadı.",
    playerLoading: "Müfredat yükleniyor.",
    playerLoadingTestID: "dron-academy-player-loading",
    playerReadyTestID: "dron-academy-player-ready",
    playerErrorTestID: "dron-academy-player-error",
    playerErrorTitle: "Müfredat henüz yüklenemedi.",
    needPurchaseTestID: "dron-academy-need-purchase",
    needPurchaseTitle: "Bu eğitim henüz senin değil.",
    needPurchase: "Satın alma cüzdan DEBIT hop'udur. Kart native forma girmez.",
    complete: "Dersi tamamla",
    completing: "Ders kaydediliyor.",
    examCta: "Sınava gir",
    listenHint: "Ders metni burada okunur. Native TTS hop'u yoktur; ses web karaoke'dedir. Punchcard rozetleri cue saatiyle yanar.",
    purchase: "Eğitimi satın al",
    purchasing: "Satın alma işleniyor.",
    purchaseFail: "Satın alma tamamlanamadı.",
    lessonClosed: "Bu ders henüz açık değil.",
  },
  exam: {
    title: "Sınav",
    loading: "Sınav yükleniyor.",
    loadingTestID: "dron-exam-loading",
    readyTestID: "dron-exam-ready",
    submittedTestID: "dron-exam-submitted",
    errorTestID: "dron-exam-error",
    errorTitle: "Sınav henüz yüklenemedi.",
    submit: "Sınavı tamamla",
    pending: "Cevaplar gönderiliyor.",
    unanswered: "Her soruyu cevaplamadan sınav gönderilmez.",
    passed: "Sınav geçildi.",
    failed: "Sınav geçilemedi. Sahte mühür basılmaz.",
    openCertificate: "Mühürü göster",
  },
  certificate: {
    title: "Mühürlü sertifika",
    loading: "Sertifika yükleniyor.",
    loadingTestID: "dron-certificate-loading",
    readyTestID: "dron-certificate-ready",
    errorTestID: "dron-certificate-error",
    errorTitle: "Sertifika henüz doğrulanamadı.",
    hashLabel: "Mühür kodu (SHA-256)",
    qrHint:
      "Native QR kütüphanesi yoktur. Mühür kodu kamu doğrulama URL'sidir; tarayıcıda açılır.",
    openVerify: "Doğrulama sayfasını aç",
    score: "Puan",
    seal: "Mühür durumu",
  },
  protocol: RAIL_V1_PARSE_FAIL,
  unknown: "İstek tamamlanamadı. Sahte başarı yok.",
} as const;
