import { RAIL_V1_CLIENT_STALE, RAIL_V1_PARSE_FAIL } from "../contract/v1";

/** Diyar B vatandaş cümleleri. Sahte başarı / boş home yok. SEN: sen, siz değil. */
export const RAIL_IS_COPY = {
  brand: "yetkin.ai",
  diyar: "Diyar B",
  boot: "Oturum doğrulanıyor.",
  retry: "Yeniden dene",
  back: "Listeye dön",
  signOut: "Çıkış",
  login: {
    testID: "dron-login",
    title: "Giriş",
    body: "Supabase oturumu native JWT üretir. Çerez yok. Amiral oturumu taşınmaz.",
    email: "E-posta",
    password: "Şifre",
    submit: "Giriş yap",
    pending: "Giriş yapılıyor.",
    verifying: "Oturum Amiral'de doğrulanıyor.",
    fail: "Giriş başarısız.",
    sessionFail: "Giriş oldu; v1 oturum ucu doğrulanamadı. Sahte tezgâh açılmaz.",
    unbound: "Supabase anon yapılandırması yok. Giriş henüz bağlanmadı.",
    apiMissing: "Amiral adresi (EXPO_PUBLIC_RAIL_API_BASE) yok. Sahte iş listesi üretilmez.",
  },
  stale: {
    testID: "dron-stale-lock",
    title: "Lütfen uygulamayı güncelleyiniz",
    body: RAIL_V1_CLIENT_STALE,
  },
  jobs: {
    title: "Açık işler",
    loading: "İş listesi yükleniyor.",
    loadingTestID: "dron-job-list-loading",
    readyTestID: "dron-job-list-ready",
    emptyTestID: "dron-job-list-empty",
    errorTestID: "dron-job-list-error",
    errorTitle: "Liste henüz yüklenemedi.",
    empty: "Şu an açık iş yok.",
    emptyHint: "Bu boşluk sunucunun OPEN listesidir; hata kartı değildir.",
  },
  job: {
    budgetLabel: "Bütçe",
    briefLabel: "İş brief'i",
    openOnly: "Teklif yalnız OPEN ilana gider.",
  },
  bid: {
    title: "Teklif",
    amountLabel: "Teklif tutarı (₺)",
    amountHint: "Tam sayı kuruş (amountMinor). Bant ₺250–₺50.000.",
    coverLabel: "Teklif notu",
    submit: "Teklif gönder",
    pending: "Teklif gönderiliyor.",
    success: "Teklif alındı.",
    invalidAmount: "Tutar tam sayı amountMinor üretmedi.",
    amountBand: "Teklif ₺250–₺50.000 bandında olmalıdır.",
    coverBand: "Teklif notu 4–2000 karakter olmalıdır.",
    conflict:
      "Bu niyet farklı bir teklifle kilitli. Yeni UUID sessiz basılmaz; yeni niyet ayrı eylemdir.",
    newIntent: "Yeni niyet aç",
    errorTestID: "dron-bid-error",
    successTestID: "dron-bid-success",
    formTestID: "dron-bid-form",
  },
  ownerBids: {
    title: "Teklifler",
    loading: "Teklifler yükleniyor.",
    loadingTestID: "dron-owner-bids-loading",
    readyTestID: "dron-owner-bids-ready",
    emptyTestID: "dron-owner-bids-empty",
    errorTestID: "dron-owner-bids-error",
    errorTitle: "Teklifler henüz yüklenemedi.",
    empty: "Bu ilana henüz teklif yok.",
    emptyHint: "Bu boşluk sunucunun SUBMITTED listesidir; hata kartı değildir.",
    noPii: "Usta kimliği yayınlanmaz. Kartta ad, e-posta veya avatar yoktur.",
    coverLabel: "Teklif notu",
  },
  accept: {
    submit: "Teklifi kabul et",
    confirmTitle: "Teklifi kabul et",
    confirmBody:
      "Bu onay lisanslı split (PSP) ile emaneti kilitler. Cüzdan bakiyesi ile fonlanmaz. Usta hemen almaz. Teklif tutarı istekten değiştirilemez.",
    confirm: "Onaylıyorum",
    cancel: "Vazgeç",
    pending: "Teklif kabul ediliyor.",
    errorTitle: "Teklif kabul edilemedi.",
    insufficientHint: "İlan açık kaldı. Freelancer kabulü cüzdan DEBIT ile yapılmaz.",
    stillOpen: "İlan açık kaldı.",
    unboundBlock: "Ödeme henüz bağlanmadı. Sahte kilit yazılmaz.",
    stripHint: "Cüzdan şeridi kabulü fonlamaz. Split bağlı değilse 503 döner.",
    formTestID: "dron-accept-form",
    errorTestID: "dron-accept-error",
    insufficientTestID: "dron-accept-insufficient",
    modalTestID: "dron-accept-confirm",
    paymentsClosed: "Ödeme sistemi pasif",
    paymentsClosedHint:
      "PayTR Pazaryeri Split bu fazda bağlı değil. Teklif kabulü 503 döner; cüzdan bakiyesi ile fonlanmaz. İlan açık kalır; sahte kilit yazılmaz.",
    paymentsClosedTestID: "dron-accept-payments-closed",
    paymentsPassiveTitle: "Ödeme sistemi pasif",
    paymentsPassiveBody:
      "Ödeme henüz bağlanmadı. PayTR Pazaryeri Split bu fazda pasif. Teklif kabulü cüzdan ile fonlanmaz; deneme dürüst 503 döner.",
    paymentsPassiveTestID: "dron-accept-payments-passive",
  },
  wallet: {
    liveTestID: "dron-wallet-live",
    unboundTestID: "dron-wallet-unbound",
    errorTestID: "dron-wallet-error",
    loadingTestID: "dron-wallet-loading",
    liveTitle: "Canlı bakiye",
    unboundTitle: "Cüzdan henüz yüklenemedi",
    unboundBody: "live: false sıfır bakiye değildir. Uydurma ₺0 basılmaz.",
    errorTitle: "Cüzdan şeridi okunamadı.",
    topUp: "Cüzdanı web'de yükle",
    webWallet: "Cüzdanı web'de aç",
    topUpHint:
      "Yükleme Akademi bakiyesi içindir; teklif kabulünü fonlamaz. Split bağlı değilse kabul 503. Native PayTR yok — Amiral /cuzdan.",
  },
  bench: {
    title: "İşlerim",
    tab: "İşlerim",
    jobsTab: "Açık işler",
    loading: "İşlerin yükleniyor.",
    loadingTestID: "dron-bench-loading",
    readyTestID: "dron-bench-ready",
    emptyTestID: "dron-bench-empty",
    errorTestID: "dron-bench-error",
    errorTitle: "Tezgâh henüz yüklenemedi.",
    empty: "Şu an kayıtlı işin yok.",
    emptyHint: "Bu boşluk sunucunun sözleşme listesidir; hata kartı değildir.",
    inProgress: "Devam ediyor (emanet blokeli)",
    delivered: "Teslim edildi",
    released: "Hak Ediş Serbest Bırakıldı",
    refunded: "İade",
    disputed: "Tahkimde",
    untitled: "Başlık henüz yok",
    roleFreelancer: "Usta",
    roleClient: "İşveren",
    refresh: "Yenile",
    funded: "Bakiye kilitli",
    escrowOpaque: "Emanet kimliği opak referanstır; hold API çağrılmaz.",
  },
  delivery: {
    submit: "İşi Teslim Et",
    note: "Teslimat notu",
    pending: "Teslimat gönderiliyor.",
    errorTitle: "Teslimat gönderilemedi.",
    noteBand: "Teslimat notu 8–8000 karakter olmalıdır.",
    formTestID: "dron-delivery-form",
    errorTestID: "dron-delivery-error",
    hint: "Teslim, emanet serbest bırakması değildir. İşveren kabulü ayrıdır.",
  },
  release: {
    submit: "Teslimatı Onayla ve Öde",
    pending: "Hak ediş serbest bırakılıyor.",
    errorTitle: "Hak ediş serbest bırakılamadı.",
    success: "Hak Ediş Serbest Bırakıldı",
    hint: "Usta payı yetkin.ai cüzdanına yazılmaz. Dağıtım lisanslı kuruluştadır; split pasifken 503 döner.",
    gross: "Brüt (kilitli)",
    hold: "Platform hold",
    net: "Usta net",
    formTestID: "dron-release-form",
    errorTestID: "dron-release-error",
  },
  protocol: RAIL_V1_PARSE_FAIL,
  unknown: "İstek tamamlanamadı. Sahte başarı yok.",
} as const;
