/**
 * Üretir: npm run verify:api-auth
 * Kenar K6 bu haritayı okur. Route grupları ((kernel)) URL'de yoktur.
 */
export const ROUTE_AUTH_MAP = {
  "/api/_gone/[...path]": "public",
  "/api/academy/certificates": "session",
  "/api/academy/certificates/[hash]": "public",
  "/api/academy/courses": "session",
  "/api/academy/courses/[id]": "session",
  "/api/academy/courses/[id]/curriculum": "session",
  "/api/academy/courses/[id]/exam": "session",
  "/api/academy/courses/[id]/listen": "public",
  "/api/academy/courses/[id]/lock": "session",
  "/api/academy/courses/[id]/pdf": "public",
  "/api/academy/courses/[id]/purchase": "session",
  "/api/academy/discussion": "public",
  "/api/academy/generateSpeech": "public",
  "/api/academy/pulse": "session",
  "/api/academy/reviews": "public",
  "/api/admin/catalog": "admin",
  "/api/admin/curriculum-revisions": "public",
  "/api/ai/chat": "session",
  "/api/auth/logout": "public",
  "/api/auth/password": "session",
  "/api/auth/session": "session",
  "/api/career/portfolio": "session",
  "/api/career/pulse": "session",
  "/api/career/visas": "session",
  "/api/client/jobs/[id]/bids": "session",
  "/api/dashboard/pulse": "session",
  "/api/dashboard/wallet-strip": "session",
  "/api/freelancer/contracts": "session",
  "/api/freelancer/contracts/[id]": "session",
  "/api/freelancer/contracts/[id]/dispute": "session",
  "/api/freelancer/contracts/[id]/messages": "session",
  "/api/freelancer/contracts/[id]/refund": "session",
  "/api/freelancer/contracts/[id]/release": "session",
  "/api/freelancer/direct-offers": "session",
  "/api/freelancer/direct-offers/[id]/accept": "session",
  "/api/freelancer/direct-offers/[id]/decline": "session",
  "/api/freelancer/dispute": "session",
  "/api/freelancer/jobs": "session",
  "/api/freelancer/jobs/[id]": "session",
  "/api/freelancer/jobs/[id]/accept": "session",
  "/api/freelancer/jobs/[id]/bids": "session",
  "/api/freelancer/squad": "session",
  "/api/health": "public",
  "/api/health/live": "public",
  "/api/jobs/inngest": "webhook",
  "/api/payments/webhooks/paytr": "webhook",
  "/api/profile": "session",
  "/api/wallet/top-up": "session"
} as const;

export type RouteAuthPath = keyof typeof ROUTE_AUTH_MAP;
