/**
 * TTS kısaltma normalizer — harf harf okuma yasak.
 * Görsel müfredat metni değişmez; yalnız seslendirilecek metin genişletilir.
 * generateSpeech `text` parametresine gitmeden önce zorunlu gümrük.
 */

/** Sık teknik kısaltma → pedagojik tam açılım (Türkçe önce, kısaltma parantezde). */
export const ACADEMY_SPEECH_ACRONYM_EXPANSIONS = {
  LLM: "Büyük Dil Modeli (LLM)",
  RAG: "Artırılmış Geri Çapraz Sorgulama (RAG)",
  DDD: "Etki Alanı Odaklı Tasarım (Domain-Driven Design)",
  PII: "Kişisel Gizli Veriler (PII)",
  API: "Uygulama Programlama Arayüzü (API)",
  SQL: "Yapılandırılmış Sorgu Dili (SQL)",
  ACID: "Atomiklik-Tutarlılık-İzolasyon-Dayanıklılık (ACID)",
  MVCC: "Çok Sürümlü Eşzamanlılık Denetimi (MVCC)",
  NoSQL: "Yalnız Yapılandırılmış Sorgu Dili Değil (NoSQL)",
  DDL: "Veri Tanımlama Dili (DDL)",
  DML: "Veri İşleme Dili (DML)",
  CDC: "değişim verisi yakalama (CDC)",
  CTE: "ortak tablo ifadesi (CTE)",
  ORM: "nesne-ilişkisel eşleme (ORM)",
  HTTP: "Hipermetin Aktarım Protokolü (HTTP)",
  JSON: "JavaScript Nesne Gösterimi (JSON)",
  CSV: "Virgülle Ayrılmış Değerler (CSV)",
  REST: "Temsili Durum Transferi (REST)",
  PDF: "taşınabilir belge biçimi (PDF)",
  OWASP: "Açık Web Uygulaması Güvenlik Projesi (OWASP)",
  XSS: "Siteler Arası Komut Çalıştırma (XSS)",
  CSRF: "Siteler Arası İstek Sahteciliği (CSRF)",
  SQLi: "Yapılandırılmış Sorgu Dili enjeksiyonu (SQLi)",
  PCAP: "paket yakalama dosyası (PCAP)",
  CIA: "gizlilik-bütünlük-erişilebilirlik üçlüsü (CIA)",
  RoE: "etkileşim kuralları (RoE)",
  OSINT: "açık kaynak istihbaratı (OSINT)",
  IDOR: "güvensiz doğrudan nesne referansı (IDOR)",
  TLS: "Taşıma Katmanı Güvenliği (TLS)",
  CSP: "İçerik Güvenliği Politikası (CSP)",
  WAF: "Web Uygulaması Güvenlik Duvarı (WAF)",
  UDP: "Kullanıcı Datagram Protokolü (UDP)",
  OSI: "Açık Sistemler Bağlantısı (OSI)",
  ABI: "uygulama ikili arayüzü (ABI)",
  IOC: "ele geçirme göstergesi (IOC)",
  JWT: "JavaScript Nesne Gösterimi Web Jetonu (JWT)",
  CVSS: "ortak zafiyet puanlama sistemi (CVSS)",
  PoC: "kavram kanıtı (PoC)",
  SSH: "Güvenli Kabuk Protokolü (SSH)",
  DNS: "Alan Adı Sistemi (DNS)",
  IAM: "Kimlik ve Erişim Yönetimi (IAM)",
  AWS: "Amazon Web Servisleri (AWS)",
  VPC: "Sanallaştırılmış Özel Ağ (VPC)",
  EC2: "Esnek Bilgi İşlem Bulutu (EC2)",
  S3: "Basit Depolama Servisi (S3)",
  CIDR: "adres bloğu (CIDR)",
  AMI: "Amazon Makine İmajı (AMI)",
  NACL: "Ağ Erişim Kontrol Listesi (NACL)",
  KVKK: "Kişisel Verilerin Korunması Kanunu (KVKK)",
  SAST: "Statik Uygulama Güvenlik Testi (SAST)",
  DAST: "Dinamik Uygulama Güvenlik Testi (DAST)",
  SBOM: "Yazılım Malzeme Listesi (SBOM)",
  MFA: "Çok Faktörlü Kimlik Doğrulama (MFA)",
  CVE: "bilinen güvenlik açığı kaydı (CVE)",
  CI: "Sürekli Entegrasyon (CI)",
  DTO: "Veri Transfer Nesnesi (DTO)",
  SSOT: "Tek Gerçek Kaynak (SSOT)",
  EVM: "Ethereum Sanal Makinesi (EVM)",
  dApp: "Dağıtık Uygulama (dApp)",
  DeFi: "Centralize Olmayan Finans / Merkeziyetsiz Finans (DeFi)",
  AMM: "Otomatik Piyasa Yapıcı (AMM)",
  CEI: "Kontrol-Etki-Etkileşim (CEI)",
  NFT: "değiştirilemez jeton (NFT)",
  EOA: "dışarıdan sahip olunan hesap (EOA)",
  RPC: "uzak yordam çağrısı (RPC)",
  MEV: "madenci çıkarılabilir değer (MEV)",
  IPA: "iOS uygulama paketi (IPA)",
  OTA: "Havadan Güncelleme (OTA)",
  JSI: "JavaScript Arayüzü (JSI)",
  AAB: "Android Uygulama Paketi (AAB)",
  CRUD: "oluştur-oku-güncelle-sil (CRUD)",
  FFI: "yabancı işlev arayüzü (FFI)",
  IaaS: "Hizmet Olarak Altyapı (IaaS)",
  PaaS: "Hizmet Olarak Platform (PaaS)",
  SaaS: "Hizmet Olarak Yazılım (SaaS)",
  UX: "Kullanıcı Deneyimi (UX)",
  UI: "Kullanıcı Arayüzü (UI)",
  WCAG: "Web İçeriği Erişilebilirlik Kılavuzu (WCAG)",
  HTML: "Hipermetin İşaretleme Dili (HTML)",
  CSS: "Basamaklı Stil Sayfaları (CSS)",
  ARIA: "Erişilebilir Zengin İnternet Uygulamaları (ARIA)",
  CTA: "eyleme çağrı (CTA)",
  IA: "bilgi mimarisi (IA)",
  SUS: "Sistem Kullanılabilirlik Ölçeği (SUS)",
  OKR: "Hedefler ve Anahtar Sonuçlar (OKR)",
  KPI: "Temel Performans Göstergeleri (KPI)",
  WIP: "Devam Eden İş (WIP)",
  INVEST: "Bağımsız-Pazarlığa Açık-Değerli-Tahmin Edilebilir-Küçük-Test Edilebilir (INVEST)",
  tROAS: "Hedef Reklam Harcamasının Geri Dönüşü (tROAS)",
  tCPA: "Hedef Edinme Başına Maliyet (tCPA)",
  ROAS: "Reklam Harcamasının Geri Dönüşü (ROAS)",
  CPA: "Edinme Başına Maliyet (CPA)",
  CPC: "Tıklama Başına Maliyet (CPC)",
  CTR: "Tıklama Oranı (CTR)",
  CVR: "Dönüşüm Oranı (CVR)",
  CAC: "Müşteri Edinim Maliyeti (CAC)",
  SEO: "Arama Motoru Optimizasyonu (SEO)",
  SERP: "Arama Motoru Sonuç Sayfası (SERP)",
  CBO: "Kampanya Bütçe Optimizasyonu (CBO)",
  RSA: "Duyarlı Arama Ağı Reklamı (RSA)",
  PMax: "Performans Maksimumu (PMax)",
  GTM: "Google Etiket Yöneticisi (GTM)",
  UTM: "kampanya izleme parametresi (UTM)",
  CWV: "Temel Web Canlılıkları (CWV)",
  LCP: "En Büyük İçerikli Boyama (LCP)",
  INP: "Etkileşime Sonraki Boyama (INP)",
  CLS: "Kümülatif Düzen Kayması (CLS)",
  AVD: "ortalama izlenme süresi (AVD)",
  PDP: "Ürün Detay Sayfası (PDP)",
  COGS: "Satılan Malın Maliyeti (COGS)",
  SLA: "Hizmet Seviyesi Anlaşması (SLA)",
  AOV: "Ortalama Sipariş Değeri (AOV)",
  MOQ: "asgari sipariş miktarı (MOQ)",
  DAX: "Veri Çözümleme İfadeleri (DAX)",
  ETL: "Veri Dönüştürme ve Yükleme İşlemi (ETL)",
  RLS: "Satır Düzeyi Güvenlik (RLS)",
  NLP: "Nöro-Dilsel Programlama (NLP)",
  SBI: "Durum-Davranış-Etki Geri Bildirimi (SBI)",
  EQ: "Duygusal Zekâ (EQ)",
  ALB: "Esnek Yük Dengeleyici (ALB)",
  RDS: "İlişkisel Veritabanı Servisi (RDS)",
  ASG: "otomatik ölçekleme grubu (ASG)",
  ELB: "Esnek Yük Dengeleyici (ELB)",
  K8s: "Kubernetes (K8s)",
  IaC: "Kod Olarak Altyapı (IaC)",
  GitOps: "Git ile işletme (GitOps)",
  EKS: "Esnek Kubernetes Servisi (EKS)",
  HPA: "yatay pod ölçekleyici (HPA)",
  ELT: "Ayıkla-Yükle-Dönüştür (ELT)",
  DWH: "Veri Ambarı (DWH)",
  dbt: "Veri Dönüştürme Aracı (dbt)",
  DAG: "Yönlü Devirsel Olmayan Graf (DAG)",
  Spark: "Kıvılcım Veri İşleme Motoru (Spark)",
  Airflow: "Hava Akışı Orkestratörü (Airflow)",
  Databricks: "Veri Tuğlaları Platformu (Databricks)",
  Snowflake: "Kar Tanesi Veri Ambarı (Snowflake)",
  QA: "Kalite Güvencesi (QA)",
  E2E: "Uçtan Uca Test (E2E)",
  k6: "Performans Test Aracı (k6)",
  p95: "yüzde doksan beş (p95)",
  JVM: "Java Sanal Makinesi (JVM)",
  JPA: "Java Kalıcılık Uygulama Programlama Arayüzü (JPA)",
  OOP: "Nesne Yönelimli Programlama (OOP)",
  JDBC: "Java Veritabanı Bağlantısı (JDBC)",
  IAP: "Uygulama İçi Satın Alma (IAP)",
  FPS: "Saniye Başına Kare Sayısı (FPS)",
  SDK: "Yazılım Geliştirme Kiti (SDK)",
  MLOps: "Yapay Zekâ Model Operasyonları (MLOps)",
  LLMOps: "Büyük Dil Modeli Operasyonları (LLMOps)",
  DVC: "Veri Sürüm Kontrolü (DVC)",
  MLflow: "Makine Öğrenmesi Akış Defteri (MLflow)",
  GPU: "Grafik İşlem Birimi (GPU)",
  CPU: "Merkezi İşlem Birimi (CPU)",
  RAM: "Rastgele Erişim Belleği (RAM)",
  RPS: "Saniye Başına İstek Sayısı (RPS)",
  CAP: "Tutarlılık-Erişilebilirlik-Bölünme Toleransı (CAP)",
  p99: "yüzde doksan dokuz (p99)",
  ML: "Makine Öğrenmesi (ML)",
} as const;

export type AcademySpeechAcronym = keyof typeof ACADEMY_SPEECH_ACRONYM_EXPANSIONS;

/**
 * Bare kısaltmayı genişletir; `(LLM)` veya `API (...)` gibi zaten
 * parantezli / açıklamalı biçimleri bozmaz.
 * Sınır `\\b` değil Unicode harftir: Türkçe `Sürümlü` içindeki `ml`
 * veya `açılırsa` içindeki `rsa` yutulmaz.
 * Uzun anahtar önce uygulanır: `MLOps` `ML` ile parçalanmaz.
 * SSOT adı: `normalizeAcronyms` — ses motoruna gitmeden önce çağrılır.
 */
export function normalizeAcronyms(text: string): string {
  let out = text;
  const entries = Object.entries(ACADEMY_SPEECH_ACRONYM_EXPANSIONS).sort(
    (left, right) => right[0].length - left[0].length,
  );
  for (const [acronym, expansion] of entries) {
    const escaped = acronym.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const pattern = new RegExp(`(?<![.\\p{L}(])${escaped}(?!\\p{L}|\\s*\\()`, "giu");
    out = out.replace(pattern, expansion);
  }
  return out;
}

/** @deprecated `normalizeAcronyms` kullan — aynı SSOT. */
export const normalizeAcademyAcronymsForSpeech = normalizeAcronyms;
