/**
 * Tur 3 sinema slayt kataloğu — cue kartı içerik SSOT.
 * Bake `scripts/render-academy-cinema-cues.ts` JPG yazar; izlemede generate yok.
 * Taze ingest öncesi slayt gövdesi boştur; 33 ders anahtarı iskelet durur.
 * 01_office_ai-1 Altın Şablon: Beat 3 `visualMode: "split"` Önce/Sonra karşılaştırması.
 * 01_office_ai-2: Beat 3 sol ÖNCE (10 SAYFALIK DÖKÜM), sağ SONRA (3 MADDELİK YÖNETİM ÖZETİ - AI).
 * 01_office_ai-3: %80 canlı slayt editörü. Beat 3 sol ÖNCE (DÜZ METİN YIĞINI), sağ SONRA (GÖRSEL HİYERARŞİLİ SLAYT - AI).
 * 01_office_ai-4: %80 canlı Outlook. Beat 3 sol ÖNCE (142 OKUNMAMIŞ MAİL), sağ SONRA (SIFIRLANMIŞ KUTU - AI).
 * 01_office_ai-5: %80 canlı Excel / Copilot paneli. Beat 3 sol KÖR SÜREÇ (HALÜSİNASYONLU VERİ),
 * sağ DEDEKTİF SÜREÇ (KONTROLLÜ VERİ). Düzeltilmiş dedektif tablosu Beat 3’e kadar kapalı.
 * 01_office_ai-6: %80 canlı Excel / Cuma 30. Beat 3 sol DAĞINIK HAFTA (KRİZ TEKRARI),
 * sağ CUMA OTUZ (SİSTEMLİ RUTİN). Sistemli Cuma tablosu Beat 3’e kadar kapalı.
 * 01_office_ai-g1: %80 canlı Gmail. Beat 3 sol GELEN KUTUSUNDAN KOPUK / TAŞIMA SU,
 * sağ GELEN KUTUSU İÇİ / YERLEŞİK GEMİNİ. Command boyunca yerleşik özet kapalı (Spoiler Yasağı).
 * 01_office_ai-w1: %80 canlı Word. Beat 3 sol ZAHMETLİ YOL / PARÇA PARÇA METİN KOPYALAMA,
 * sağ DOĞRUDAN DOSYA YÜKLEME / YERİNDE DOKÜMAN ANALİZİ. Tam madde listesi Beat 3’e kadar kapalı.
 * Command boyunca biten sunum / sıfır kutu / doğrulanmış tablo kapalı (Spoiler Yasağı).
 * Pekiştirme: cue-01 GİRİŞ KÖPRÜSÜ, cue-07 CEBİNE KOY.
 */

import {
  ACADEMY_GOLDEN_COMPARE_AFTER_LABEL,
  ACADEMY_GOLDEN_COMPARE_BEFORE_LABEL,
  ACADEMY_OFFICE_AI_2_COMPARE_AFTER_LABEL,
  ACADEMY_OFFICE_AI_2_COMPARE_BEFORE_LABEL,
  ACADEMY_OFFICE_AI_2_COPILOT_PROMPT,
  ACADEMY_OFFICE_AI_3_COMPARE_AFTER_LABEL,
  ACADEMY_OFFICE_AI_3_COMPARE_BEFORE_LABEL,
  ACADEMY_OFFICE_AI_3_COPILOT_PROMPT,
  ACADEMY_OFFICE_AI_4_COMPARE_AFTER_LABEL,
  ACADEMY_OFFICE_AI_4_COMPARE_BEFORE_LABEL,
  ACADEMY_OFFICE_AI_5_COMPARE_AFTER_LABEL,
  ACADEMY_OFFICE_AI_5_COMPARE_BEFORE_LABEL,
  ACADEMY_OFFICE_AI_6_COMPARE_AFTER_LABEL,
  ACADEMY_OFFICE_AI_6_COMPARE_BEFORE_LABEL,
  ACADEMY_OFFICE_AI_G1_COMPARE_AFTER_LABEL,
  ACADEMY_OFFICE_AI_G1_COMPARE_BEFORE_LABEL,
  ACADEMY_OFFICE_AI_W1_COMPARE_AFTER_LABEL,
  ACADEMY_OFFICE_AI_K1_COMPARE_AFTER_LABEL,
  ACADEMY_OFFICE_AI_K1_COMPARE_BEFORE_LABEL,
  ACADEMY_OFFICE_AI_W1_COMPARE_BEFORE_LABEL,
  type AcademyGoldenBeatId,
  type AcademyGoldenVisualMode,
} from "@/lib/academy/lesson-beat-visual";
import {
  ACADEMY_ERROR_HUNT_COPILOT_PROMPT,
  ACADEMY_ERROR_HUNT_FILE_NAME,
  ACADEMY_ERROR_HUNT_FLAG_CELLS,
  ACADEMY_ERROR_HUNT_HALLUCINATED_TABLE,
  ACADEMY_ERROR_HUNT_SHEET_NAME,
  ACADEMY_ERROR_HUNT_VERIFIED_TABLE,
} from "@/lib/academy/error-hunt-workspace";
import { ACADEMY_GMAIL_GEMINI_PROMPT } from "@/lib/academy/gmail-workspace";
import {
  ACADEMY_WEEKLY_ROUTINE_CHAOS_TABLE,
  ACADEMY_WEEKLY_ROUTINE_COPILOT_PROMPT,
  ACADEMY_WEEKLY_ROUTINE_FILE_NAME,
  ACADEMY_WEEKLY_ROUTINE_FLAG_CELLS,
  ACADEMY_WEEKLY_ROUTINE_SHEET_NAME,
  ACADEMY_WEEKLY_ROUTINE_SYSTEM_TABLE,
} from "@/lib/academy/weekly-routine-workspace";
import {
  ACADEMY_KVKK_COPILOT_PROMPT,
  ACADEMY_KVKK_FILE_NAME,
  ACADEMY_KVKK_FLAG_CELLS,
  ACADEMY_KVKK_MASKED_TABLE,
  ACADEMY_KVKK_RAW_TABLE,
  ACADEMY_KVKK_SHEET_NAME,
} from "@/lib/academy/kvkk-workspace";
import { ACADEMY_OUTLOOK_COPILOT_PROMPT } from "@/lib/academy/outlook-workspace";
import { ACADEMY_WORD_UPLOAD_PROMPT } from "@/lib/academy/word-workspace";

export const ACADEMY_CINEMA_CUE_SLIDE_LESSON_KEYS = [
  "01_office_ai-1",
  "01_office_ai-2",
  "01_office_ai-3",
  "01_office_ai-4",
  "01_office_ai-5",
  "01_office_ai-6",
  "01_office_ai-g1",
  "01_office_ai-w1",
  "01_office_ai-k1",
  "02_ecommerce_ai-1",
  "02_ecommerce_ai-2",
  "02_ecommerce_ai-3",
  "02_ecommerce_ai-4",
  "02_ecommerce_ai-5",
  "02_ecommerce_ai-6",
  "03_social_media_ai-1",
  "03_social_media_ai-2",
  "03_social_media_ai-3",
  "03_social_media_ai-4",
  "03_social_media_ai-5",
  "03_social_media_ai-6",
  "04_chatbot_nocode-1",
  "04_chatbot_nocode-2",
  "04_chatbot_nocode-3",
  "04_chatbot_nocode-4",
  "04_chatbot_nocode-5",
  "04_chatbot_nocode-6",
  "05_prompt_practice-1",
  "05_prompt_practice-2",
  "05_prompt_practice-3",
  "05_prompt_practice-4",
  "05_prompt_practice-5",
  "05_prompt_practice-6",
] as const;

export type AcademyCinemaCueSlideLessonKey = (typeof ACADEMY_CINEMA_CUE_SLIDE_LESSON_KEYS)[number];

export type AcademyCinemaCueLayout =
  | "problem"
  | "chat"
  | "excel"
  | "email"
  | "word"
  | "pptx"
  | "outlook"
  | "gmail"
  | "listing"
  | "shield"
  | "flow"
  | "whatsapp"
  | "reels"
  | "prompt"
  | "keys";

export type AcademyCinemaThemeId = "office" | "commerce" | "social" | "bot" | "prompt";

export type AcademyCinemaBeatId = AcademyGoldenBeatId;
export type AcademyCinemaVisualMode = AcademyGoldenVisualMode;

export type AcademyCinemaCompareSpec = {
  beforeCueIndex: number;
  beforeLabel: string;
  afterLabel: string;
};

export type AcademyCinemaCueSlide = {
  lessonKey: AcademyCinemaCueSlideLessonKey;
  cueIndex: number;
  theme: AcademyCinemaThemeId;
  courseLabel: string;
  lessonTitle: string;
  instructor: string;
  section: string;
  headline: string;
  subhead: string;
  bullets: readonly string[];
  tools: readonly string[];
  layout: AcademyCinemaCueLayout;
  beat?: AcademyCinemaBeatId;
  visualMode?: AcademyCinemaVisualMode;
  compare?: AcademyCinemaCompareSpec;
  stats?: readonly { label: string; value: string }[];
  table?: { headers: readonly string[]; rows: readonly (readonly string[])[]; note?: string };
  chat?: { role: string; prompt: string; replyTitle: string; replyLines: readonly string[] };
  messages?: readonly { from: "bot" | "user"; text: string }[];
  nodes?: readonly { title: string; sub: string }[];
  keys?: readonly { n: string; title: string; body: string }[];
  warning?: string;
  fieldTask?: string;
  highlightCell?: string;
  /** Halüsinasyon / sapma hücreleri — kırmızı işaret. */
  errorCells?: readonly string[];
  mergedTop?: boolean;
  zoomA1?: boolean;
  formulaBar?: string;
  fileName?: string;
  sheetName?: string;
  copilot?: { prompt: string; replyLines: readonly string[]; hideReply?: boolean };
};

type OverlayDraft = Omit<
  AcademyCinemaCueSlide,
  "lessonKey" | "theme" | "courseLabel" | "lessonTitle" | "instructor"
>;

type LessonDraft = {
  title: string;
  theme: AcademyCinemaThemeId;
  courseLabel: string;
  instructor: string;
  cues: readonly OverlayDraft[];
};

const EMPTY_CUES: readonly OverlayDraft[] = [];

const OFFICE = {
  theme: "office" as const,
  courseLabel: "Ofis AI · Excel Word PPT Outlook",
  instructor: "Gözde",
};
const COMMERCE = {
  theme: "commerce" as const,
  courseLabel: "E-Ticaret AI · Trendyol HB Amazon",
  instructor: "Aylin",
};
const SOCIAL = {
  theme: "social" as const,
  courseLabel: "Sosyal Medya AI · Reels Fabrikası",
  instructor: "Deniz",
};
const BOT = {
  theme: "bot" as const,
  courseLabel: "Kodsuz Chatbot · Voiceflow Botpress",
  instructor: "Kaan",
};
const PROMPT = {
  theme: "prompt" as const,
  courseLabel: "Prompt Atölyesi · ChatGPT Claude Perplexity",
  instructor: "Gözde",
};

/** 01_office_ai-1 Command beat — dağınık ızgara; temiz tablo yalnız Beat 3 sağ panelde. */
const OFFICE_AI_1_MESSY_TABLE = {
  headers: ["Tarih", "Cari", "Fatura", "Tutar", "Durum", "Not"],
  rows: [
    ["12.03.2026", "Kaya Gıda A.Ş.", "FT-1042", "12 450", "Ödendi", ""],
    ["", "", "", "", "", ""],
    ["12/03/26", "Demir Lojistik", "ft 1043", "8.200 TL", "Bekler", "mail?"],
    ["Mart-12", "Pınar Market", "1044", "3400", "ödendi", "vade?"],
    ["13.03.2026", "Yıldız Tekstil", "", "  9 100 ", "Açık", ""],
    ["", "", "", "", "", ""],
    ["14/3/2026", "Kaya Gıda A.Ş.", "FT-1047", "21500", "ÖDENDİ", "çift mi"],
  ],
  note: "A1:F1 birleşik afiş — tablo değil.",
} as const;

const OFFICE_AI_3_TEXT_DUMP = {
  headers: ["Satır", "Düz metin yığını"],
  rows: [
    ["1", "Mart tahsilat toplamı 54.650 TL; Kaya önde, Demir bekler..."],
    ["2", "Yıldız açık vade, risk cümleleri paragrafa gömülü durur..."],
    ["3", "Karar notu var ama slayt yok; her şey tek yığında..."],
    ["4", "Şablon klasöründe yirmi tema açık, hiçbiri hiyerarşi kurmadı."],
    ["5", "Boş slayt stresinde metin olduğu gibi yapıştırılır."],
  ],
  note: "Spoiler yasağı: biten sunum Beat 3’e kadar kapalı.",
} as const;

const OFFICE_AI_3_DECK_TABLE = {
  headers: ["KPI", "Değer", "Not"],
  rows: [
    ["Toplam tahsilat", "54.650 TL", "Yeşil vurgu"],
    ["Lider müşteri", "Kaya Gıda A.Ş.", "Mavi vurgu"],
    ["Riskli vade", "%15", "Turuncu uyarı"],
  ],
  note: "Stratejik Eylem: Yıldız Tekstil takibi başlatılsın",
} as const;

const OFFICE_AI_3_DECK_NODES = [
  { title: "Mart 2026 Yönetim Özeti", sub: "54.650 TL" },
  { title: "Kaya Gıda A.Ş.", sub: "Lider müşteri" },
  { title: "%15 Riskli Vade", sub: "Uyarı rozeti" },
] as const;

const OFFICE_AI_4_INBOX_DUMP = {
  headers: ["Kimden", "Konu"],
  rows: [
    ["Kaya Gıda A.Ş.", "Vade bugün — 54.650 TL tahsilat onayı"],
    ["Yıldız Tekstil", "Açık vade ve risk notu 14 gündür bekliyor"],
    ["Haftalık Bülten", "Üç toplantı daveti ve iki fatura aynı yığında"],
    ["İnsan Kaynakları", "Toplantı notu okunmamış duruyor"],
    ["Muhasebe", "Fatura hatırlatması kuyruğa takıldı"],
  ],
  note: "Spoiler yasağı: sıfırlanmış kutu Beat 3’e kadar kapalı.",
} as const;

const OFFICE_AI_4_ZERO_TABLE = {
  headers: ["Grup", "İçerik", "Durum"],
  rows: [
    ["ACİL AKSİYON", "Kaya Gıda — 54.650 TL Tahsilat", "Acil"],
    ["TAKİPTE / BEKLEYEN", "Yıldız Tekstil — Vade Takibi", "Bekle"],
    ["OTOMATİK ARŞİVLENDİ", "140 Okunmamış Bülten & Davet", "Arşiv"],
  ],
  note: "142 okunmamıştan sıfır kutuya: üç grup — acil, takipte, arşiv.",
} as const;

const OFFICE_AI_4_ZERO_NODES = [
  { title: "ACİL AKSİYON", sub: "Kaya Gıda — 54.650 TL Tahsilat" },
  { title: "TAKİPTE / BEKLEYEN", sub: "Yıldız Tekstil — Vade Takibi" },
  { title: "OTOMATİK ARŞİVLENDİ", sub: "140 Bülten & Davet arşivde" },
] as const;

const OFFICE_AI_G1_CARRY_TABLE = {
  headers: ["Yol", "Durum"],
  rows: [
    ["Ctrl+C mail kopyala", "Gelen kutusu kopuk"],
    ["Ekran görüntüsü", "Taşıma su"],
    ["ChatGPT yapıştır", "Yerleşik Gemini yok"],
  ],
  note: "Spoiler yasağı: yerleşik Gemini özeti Beat 3’e kadar kapalı.",
} as const;

const OFFICE_AI_G1_NATIVE_TABLE = {
  headers: ["Gönderen", "İş", "Son tarih"],
  rows: [
    ["Kaya Gıda A.Ş.", "54.650 TL tahsilat onayı", "Bugün"],
    ["Yönetim Kurulu", "Sözleşme eki imza", "17:00"],
    ["Banka + bülten", "Arşivlik", "—"],
  ],
  note: "Son 24 saat Gmail içinde Gemini ile süzüldü; taslak gönderilmedi.",
} as const;

const OFFICE_AI_G1_NATIVE_NODES = [
  { title: "ÖDEME / ONAY", sub: "Kaya Gıda — 54.650 TL tahsilat" },
  { title: "ACİL AKSİYON", sub: "Yönetim — imza onayı" },
  { title: "ARŞİVLİK", sub: "Banka dekontu + bülten" },
] as const;

const OFFICE_AI_W1_COPY_TABLE = {
  headers: ["Parça", "Kopyalanan metin"],
  rows: [
    ["syf 4", "…gecikmede günlük yüzde…"],
    ["syf 11", "…bildirim süresi belirsiz…"],
    ["syf 18", "…süre ve ceza kopuk…"],
  ],
  note: "Spoiler yasağı: tam dosya analizi Beat 3’e kadar kapalı.",
} as const;

const OFFICE_AI_W1_UPLOAD_TABLE = {
  headers: ["İş", "Özet", "İnsan kilidi"],
  rows: [
    ["CEZAİ ŞART", "Gecikmede %15 + günlük işlem", "Sayfa no"],
    ["DİLEKÇE HİTAP", "Kaymakamlık süre uzatımı", "Tarih / unvan / imza"],
    ["RAPOR MADDESİ", "Başlık + üç madde + sonraki adım", "Gözlem ≠ karar"],
  ],
  note: "Sözleşme, dilekçe ve rapor ayrı istemle; Word belgesi olarak ataş. İmza insanda.",
} as const;

const OFFICE_AI_W1_UPLOAD_NODES = [
  { title: "CEZAİ ŞART", sub: "Gecikmede %15 + günlük işlem" },
  { title: "DİLEKÇE HİTAP", sub: "Kaymakamlık süre uzatımı" },
  { title: "RAPOR MADDESİ", sub: "Başlık + üç madde + sonraki adım" },
] as const;

const LESSONS: Record<AcademyCinemaCueSlideLessonKey, LessonDraft> = {
  "01_office_ai-1": {
    ...OFFICE,
    title: "Tablonu Konuştur: Düzensiz Excel → Düzenli Tablo",
    cues: [
      {
        cueIndex: 1,
        beat: "warmup",
        visualMode: "veo",
        section: "GİRİŞ KÖPRÜSÜ",
        headline: "GİRİŞ KÖPRÜSÜ",
        subhead: "Lyria jenerik, sonra ofis veri akışı. Yapay zekâyı masana çağırma refleksini hatırla.",
        bullets: ["Refleksi hatırla", "Çoklu AI kapısı", "Önce A1 hücresi"],
        tools: ["ChatGPT", "Claude", "Gemini"],
        layout: "excel",
        highlightCell: "A1",
        fileName: "Kitap1.xlsx",
        sheetName: "Sayfa1",
        formulaBar: "Tarih",
        table: {
          headers: ["Tarih", "Cari", "Fatura", "Tutar", "Durum", "Not"],
          rows: [
            ["", "", "", "", "", ""],
            ["", "", "", "", "", ""],
            ["", "", "", "", "", ""],
            ["", "", "", "", "", ""],
            ["", "", "", "", "", ""],
          ],
        },
      },
      {
        cueIndex: 2,
        beat: "warmup",
        visualMode: "live",
        section: "HOŞ GELDİN",
        headline: "HOŞ GELDİN",
        subhead: "Gözde masada. Excel kitabı açık, A1 hücresi seçili.",
        bullets: ["Selamlar, ben Gözde", "ChatGPT Claude Gemini", "Önce A1 hücresi"],
        tools: ["ChatGPT", "Claude", "Gemini"],
        layout: "excel",
        highlightCell: "A1",
        fileName: "Kitap1.xlsx",
        sheetName: "Sayfa1",
        formulaBar: "Tarih",
        copilot: {
          prompt:
            "Bu ham dökümü hangi kapıya verirsin? Önce A1 eşiğini kur, sonra kapıyı seç.",
          replyLines: [
            "ChatGPT: hızlı taslak → ataş ile yükle.",
            "Claude: uzun dökümü dikkatle okur.",
            "Gemini: adımları net sıralar.",
            "API: şirket formatını kilitler.",
          ],
        },
        table: {
          headers: ["Tarih", "Cari", "Fatura", "Tutar", "Durum", "Not"],
          rows: [
            ["", "", "", "", "", ""],
            ["", "", "", "", "", ""],
            ["", "", "", "", "", ""],
            ["", "", "", "", "", ""],
            ["", "", "", "", "", ""],
          ],
        },
      },
      {
        cueIndex: 3,
        beat: "warmup",
        visualMode: "live",
        section: "DÜZENSİZ TABLO",
        headline: "DÜZENSİZ TABLO",
        subhead: "Birleşik afiş A1:F1, boş satır, üç dilli tarih. Ham veri / dağınık yapı.",
        bullets: ["Birleşik başlık", "Boş satır", "Tür karmaşası"],
        tools: ["Excel", "Tahsilat"],
        layout: "excel",
        highlightCell: "A1",
        mergedTop: true,
        fileName: "Tahsilat_Mart_2026.xlsx",
        sheetName: "Döküm",
        formulaBar: "Mart 2026 Tahsilat Dökümü",
        table: OFFICE_AI_1_MESSY_TABLE,
      },
      {
        cueIndex: 4,
        beat: "command",
        visualMode: "live",
        section: "A1 HÜCRESİ",
        headline: "A1 HÜCRESİ",
        subhead: "Dağınık ızgara durur. A1 zoom: birleşik afiş hâlâ masada.",
        bullets: ["İsim kutusu A1", "Formül çubuğu", "Yeşil çerçeve"],
        tools: ["Excel", "A1"],
        layout: "excel",
        highlightCell: "A1",
        zoomA1: true,
        mergedTop: true,
        fileName: "Tahsilat_Mart_2026.xlsx",
        sheetName: "Döküm",
        formulaBar: "Mart 2026 Tahsilat Dökümü",
        table: OFFICE_AI_1_MESSY_TABLE,
      },
      {
        cueIndex: 5,
        beat: "command",
        visualMode: "live",
        section: "TEMİZLE ŞİMDİ",
        headline: "TEMİZLE ŞİMDİ",
        subhead: "Dağınık ızgara + Copilot şerit veya temiz örnek ataş. Maske 2. derste.",
        bullets: ["Copilot şerit", "Ataş yükle", "Maskeli kısa"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        mergedTop: true,
        fileName: "Tahsilat_Mart_2026.xlsx",
        sheetName: "Döküm",
        formulaBar: "Mart 2026 Tahsilat Dökümü",
        copilot: {
          prompt:
            "Bu düzensiz ızgarayı düzenle. A1 hücresine sütun adı koy. Birleşikleri çöz. Boş satırları sil. Copilot varsa şeritten doğrudan okut; yoksa dosyayı ataş ile yükle. (Kişisel verileri maskeleme kuralını 2. derste kilitleyeceğiz.) Ham tabloyu yapıştırma. Bu dersteki örnek kişi adı taşımayan temiz tahsilat tablosudur.",
          replyLines: [
            "1. Copilot şeridi.",
            "2. Ataş yükle.",
            "3. Maskeli kısa özet.",
            "4. A1 hücresine Tarih yaz.",
            "5. Birleşik A1:F1 çöz, boş satırı sil.",
            "6. Orijinali koru, Temiz kopyada çalış.",
          ],
        },
        table: OFFICE_AI_1_MESSY_TABLE,
      },
      {
        cueIndex: 6,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_GOLDEN_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_GOLDEN_COMPARE_AFTER_LABEL,
        },
        section: "FARK ORTADA",
        headline: "FARK ORTADA",
        subhead: "Sol ham veri, sağ AI çıktısı. A1 hücresi ışıldar.",
        bullets: ["Önce dağınık yapı", "Sonra düzenli tablo", "A1 ışıldar"],
        tools: ["Excel", "Filtre"],
        layout: "excel",
        highlightCell: "A1",
        fileName: "Tahsilat_Mart_2026.xlsx",
        sheetName: "Temiz",
        formulaBar: "Tarih",
        table: {
          headers: ["Tarih", "Cari", "Fatura", "Tutar", "Durum"],
          rows: [
            ["12.03.2026", "Kaya Gıda A.Ş.", "FT-1042", "12.450,00", "Ödendi"],
            ["13.03.2026", "Demir Lojistik", "FT-1043", "8.200,00", "Bekler"],
            ["13.03.2026", "Pınar Market", "FT-1044", "3.400,00", "Ödendi"],
            ["14.03.2026", "Yıldız Tekstil", "FT-1045", "9.100,00", "Açık"],
            ["14.03.2026", "Kaya Gıda A.Ş.", "FT-1047", "21.500,00", "Ödendi"],
            ["Toplam", "", "", "54.650,00", ""],
          ],
          note: "Aynı dosya, farklı eşik.",
        },
      },
      {
        cueIndex: 7,
        beat: "task",
        visualMode: "live",
        section: "CEBİNE KOY",
        headline: "CEBİNE KOY",
        subhead: "Üç adımı cebine koy: A1, birleşikler, yalın istem.",
        bullets: ["A1 sütun adı", "Birleşik ve boş satır", "Yalın dille söyle"],
        tools: ["Excel", "A1"],
        layout: "excel",
        highlightCell: "A1",
        zoomA1: true,
        fileName: "Tahsilat_Mart_2026.xlsx",
        sheetName: "Temiz",
        formulaBar: "Tarih",
        table: {
          headers: ["Tarih", "Cari", "Fatura", "Tutar", "Durum"],
          rows: [
            ["12.03.2026", "Kaya Gıda A.Ş.", "FT-1042", "12.450,00", "Ödendi"],
            ["13.03.2026", "Demir Lojistik", "FT-1043", "8.200,00", "Bekler"],
            ["13.03.2026", "Pınar Market", "FT-1044", "3.400,00", "Ödendi"],
            ["14.03.2026", "Yıldız Tekstil", "FT-1045", "9.100,00", "Açık"],
            ["14.03.2026", "Kaya Gıda A.Ş.", "FT-1047", "21.500,00", "Ödendi"],
            ["Toplam", "", "", "54.650,00", ""],
          ],
          note: "Üç adım: A1, birleşik, yalın istem.",
        },
      },
      {
        cueIndex: 8,
        beat: "task",
        visualMode: "live",
        section: "SIRA SENDE",
        headline: "SIRA SENDE",
        subhead: "Düzenli nihai tablo. A1 hücresini önce ve sonra sakla.",
        bullets: ["50 satır seç", "A1 görüntüsü", "Yan yana koy"],
        tools: ["Excel", "A1"],
        layout: "excel",
        highlightCell: "A1",
        zoomA1: true,
        fileName: "Tahsilat_Mart_2026.xlsx",
        sheetName: "Temiz",
        formulaBar: "Tarih",
        table: {
          headers: ["Tarih", "Cari", "Fatura", "Tutar", "Durum"],
          rows: [
            ["12.03.2026", "Kaya Gıda A.Ş.", "FT-1042", "12.450,00", "Ödendi"],
            ["13.03.2026", "Demir Lojistik", "FT-1043", "8.200,00", "Bekler"],
            ["13.03.2026", "Pınar Market", "FT-1044", "3.400,00", "Ödendi"],
            ["14.03.2026", "Yıldız Tekstil", "FT-1045", "9.100,00", "Açık"],
            ["14.03.2026", "Kaya Gıda A.Ş.", "FT-1047", "21.500,00", "Ödendi"],
            ["Toplam", "", "", "54.650,00", ""],
          ],
          note: "A1 hücresine kendi sütun adını yaz.",
        },
      },
    ],
  },
  "01_office_ai-2": {
    ...OFFICE,
    title: "Rapor Otomasyonu: Tablodan Yönetim Özetine",
    cues: [
      {
        cueIndex: 1,
        beat: "warmup",
        visualMode: "veo",
        section: "GİRİŞ KÖPRÜSÜ",
        headline: "GİRİŞ KÖPRÜSÜ",
        subhead: "A1 ve temiz tablo refleksi cebinde. Toplantı öncesi özet stresi başlıyor.",
        bullets: ["A1 sütun adı", "Temiz tablo", "Toplantı stresi"],
        tools: ["Excel", "A1"],
        layout: "excel",
        highlightCell: "A1",
        fileName: "Tahsilat_Mart_2026.xlsx",
        sheetName: "Temiz",
        formulaBar: "Tarih",
        table: {
          headers: ["Tarih", "Cari", "Fatura", "Tutar", "Durum"],
          rows: [
            ["12.03.2026", "Kaya Gıda A.Ş.", "FT-1042", "12.450,00", "Ödendi"],
            ["13.03.2026", "Demir Lojistik", "FT-1043", "8.200,00", "Bekler"],
            ["13.03.2026", "Pınar Market", "FT-1044", "3.400,00", "Ödendi"],
            ["14.03.2026", "Yıldız Tekstil", "FT-1045", "9.100,00", "Açık"],
            ["14.03.2026", "Kaya Gıda A.Ş.", "FT-1047", "21.500,00", "Ödendi"],
          ],
        },
      },
      {
        cueIndex: 2,
        beat: "warmup",
        visualMode: "live",
        section: "HOŞ GELDİN",
        headline: "HOŞ GELDİN",
        subhead: "Gözde masada. Temiz tablo açık; bugün yönetim özeti ve karar notu.",
        bullets: ["Selamlar, ben Gözde", "Tablo hazır", "Rapor otomasyonu"],
        tools: ["Excel", "Word"],
        layout: "excel",
        highlightCell: "A1",
        fileName: "Tahsilat_Mart_2026.xlsx",
        sheetName: "Temiz",
        formulaBar: "Tarih",
        table: {
          headers: ["Tarih", "Cari", "Fatura", "Tutar", "Durum"],
          rows: [
            ["12.03.2026", "Kaya Gıda A.Ş.", "FT-1042", "12.450,00", "Ödendi"],
            ["13.03.2026", "Demir Lojistik", "FT-1043", "8.200,00", "Bekler"],
            ["13.03.2026", "Pınar Market", "FT-1044", "3.400,00", "Ödendi"],
            ["14.03.2026", "Yıldız Tekstil", "FT-1045", "9.100,00", "Açık"],
            ["14.03.2026", "Kaya Gıda A.Ş.", "FT-1047", "21.500,00", "Ödendi"],
          ],
        },
      },
      {
        cueIndex: 3,
        beat: "warmup",
        visualMode: "live",
        section: "UZUN RAPOR",
        headline: "UZUN RAPOR",
        subhead: "Yönetim toplantısı beş dakika sonra. On sayfalık döküm kimseyi ikna etmez.",
        bullets: ["On sayfa döküm", "Karar yok", "Toplantı stresi"],
        tools: ["Word", "Excel"],
        layout: "excel",
        highlightCell: "A1",
        fileName: "Haftalik_Durum_Raporu.docx",
        sheetName: "Döküm",
        formulaBar: "Sayfa",
        table: {
          headers: ["Sayfa", "Döküm"],
          rows: [
            ["1", "Giriş ve yöntem notları uzar, karar cümlesi yoktur..."],
            ["2", "Kaya Gıda faturalarının tek tek anlatısı sürer..."],
            ["3", "Demir Lojistik bekleyen bakiye dipnotlarla şişer..."],
            ["4–7", "Pınar, Yıldız ve yan cariler paragraf paragraf..."],
            ["8–10", "Sonuç yok; yönetici on sayfada kaybolur."],
          ],
          note: "On sayfalık döküm. Karar cümlesi yok.",
        },
      },
      {
        cueIndex: 4,
        beat: "command",
        visualMode: "live",
        section: "ÖZET İSTE",
        headline: "ÖZET İSTE",
        subhead: "Temiz tablodan üç madde ve karar cümlesi iste. Sayı hücreden gelir.",
        bullets: ["Tabloyu ver", "Üç madde iste", "Sayı hücreden"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "D1",
        fileName: "Tahsilat_Mart_2026.xlsx",
        sheetName: "Temiz",
        formulaBar: "Tutar",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_OFFICE_AI_2_COPILOT_PROMPT,
          replyLines: [],
        },
        table: {
          headers: ["Tarih", "Cari", "Fatura", "Tutar", "Durum"],
          rows: [
            ["12.03.2026", "Kaya Gıda A.Ş.", "FT-1042", "12.450,00", "Ödendi"],
            ["13.03.2026", "Demir Lojistik", "FT-1043", "8.200,00", "Bekler"],
            ["13.03.2026", "Pınar Market", "FT-1044", "3.400,00", "Ödendi"],
            ["14.03.2026", "Yıldız Tekstil", "FT-1045", "9.100,00", "Açık"],
            ["14.03.2026", "Kaya Gıda A.Ş.", "FT-1047", "21.500,00", "Ödendi"],
          ],
          note: "Üç madde iste. Sayıları hücreden al. Uydurma yüzde yok.",
        },
      },
      {
        cueIndex: 5,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_2_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_2_COMPARE_AFTER_LABEL,
        },
        section: "KARAR NOTU",
        headline: "KARAR NOTU",
        subhead: "Sol on sayfalık döküm, sağ üç madde ve eylem cümlesi.",
        bullets: ["On sayfa döküm", "Üç madde", "Eylem cümlesi"],
        tools: ["Excel", "Word"],
        layout: "excel",
        highlightCell: "A1",
        fileName: "Yonetici_Ozeti.docx",
        sheetName: "Ozet",
        formulaBar: "Madde",
        table: {
          headers: ["Madde", "Kaynak sayı", "Not"],
          rows: [
            ["Toplam", "54.650", "Mart tahsilat; trend Kaya önde"],
            ["Risk", "8.200", "Demir Lojistik bekler"],
            ["Açık", "9.100", "Yıldız Tekstil vade"],
            ["Karar", "—", "Bugün Demir'i ara"],
          ],
          note: "Üç madde + karar. Sayılar tahsilat ızgarasından kilitli.",
        },
      },
      {
        cueIndex: 6,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_2_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_2_COMPARE_AFTER_LABEL,
        },
        section: "FARK ORTADA",
        headline: "FARK ORTADA",
        subhead: "Sol on sayfalık döküm. Sağ üç maddelik yönetim özeti — AI.",
        bullets: ["Önce on sayfa", "Sonra üç madde", "Karar görünür"],
        tools: ["Word", "Excel"],
        layout: "excel",
        highlightCell: "A1",
        fileName: "Yonetici_Ozeti.docx",
        sheetName: "Ozet",
        formulaBar: "Madde",
        table: {
          headers: ["Madde", "Kaynak sayı", "Not"],
          rows: [
            ["Toplam", "54.650", "Mart tahsilat; trend Kaya önde"],
            ["Risk", "8.200", "Demir Lojistik bekler"],
            ["Açık", "9.100", "Yıldız Tekstil vade"],
            ["Karar", "—", "Bugün Demir'i ara"],
          ],
          note: "Sol on sayfa. Sağ üç madde; sayılar hücreden kilitli.",
        },
      },
      {
        cueIndex: 7,
        beat: "task",
        visualMode: "live",
        section: "CEBİNE KOY",
        headline: "CEBİNE KOY",
        subhead: "Üç adım: toplam ve trend, anomali, eylem cümlesi.",
        bullets: ["Toplam ve trend", "Anomali ve risk", "Eylem cümlesi"],
        tools: ["Excel", "Word"],
        layout: "excel",
        highlightCell: "A1",
        fileName: "Yonetici_Ozeti.docx",
        sheetName: "Ozet",
        formulaBar: "Madde",
        table: {
          headers: ["Madde", "Kaynak sayı", "Not"],
          rows: [
            ["Toplam", "54.650", "Mart tahsilat; trend Kaya önde"],
            ["Risk", "8.200", "Demir Lojistik bekler"],
            ["Açık", "9.100", "Yıldız Tekstil vade"],
            ["Karar", "—", "Bugün Demir'i ara"],
          ],
          note: "Cebine koy: toplam, risk, eylem. Sayı hücreden.",
        },
      },
      {
        cueIndex: 8,
        beat: "task",
        visualMode: "live",
        section: "SIRA SENDE",
        headline: "SIRA SENDE",
        subhead: "Kendi tablondan yönetim özeti ve karar notu çıkar. Sonra slayta geçeceğiz.",
        bullets: ["Kendi tablonu seç", "Özet ve karar", "4. ders slayt köprüsü"],
        tools: ["Excel", "Word"],
        layout: "excel",
        highlightCell: "A1",
        fileName: "Yonetici_Ozeti.docx",
        sheetName: "Ozet",
        formulaBar: "Madde",
        table: {
          headers: ["Madde", "Kaynak sayı", "Not"],
          rows: [
            ["Toplam", "54.650", "Mart tahsilat; trend Kaya önde"],
            ["Risk", "8.200", "Demir Lojistik bekler"],
            ["Açık", "9.100", "Yıldız Tekstil vade"],
            ["Karar", "—", "Bugün Demir'i ara"],
          ],
          note: "Saha görevi: kendi tablon, kendi özetin. Sonraki ders: Sunum Fabrikası.",
        },
      },
    ],
  },
  "01_office_ai-3": {
    ...OFFICE,
    title: "Sunum Fabrikası: Metinden Slayta",
    cues: [
      {
        cueIndex: 1,
        beat: "warmup",
        visualMode: "live",
        section: "GİRİŞ KÖPRÜSÜ",
        headline: "GİRİŞ KÖPRÜSÜ",
        subhead: "Yönetici özeti cebinde. Şimdi o metni slayta çevirme stresi başlıyor.",
        bullets: ["Özet cebinde", "Slayt stresi", "Şablon karmaşası"],
        tools: ["PowerPoint", "Copilot"],
        layout: "pptx",
        highlightCell: "A1",
        fileName: "Yonetim_Sunumu.pptx",
        sheetName: "Slayt1",
        nodes: [
          { title: "Tema 07", sub: "Boş kapak" },
          { title: "Tema 12", sub: "Boş başlık" },
          { title: "Tema 19", sub: "Boş madde" },
        ],
        table: OFFICE_AI_3_TEXT_DUMP,
      },
      {
        cueIndex: 2,
        beat: "warmup",
        visualMode: "live",
        section: "HOŞ GELDİN",
        headline: "HOŞ GELDİN",
        subhead: "Gözde masada. Boş slayt ve şablon arama karmaşası.",
        bullets: ["Selamlar, ben Gözde", "Boş slayt", "Şablon kaos"],
        tools: ["PowerPoint", "Copilot"],
        layout: "pptx",
        highlightCell: "A1",
        fileName: "Yonetim_Sunumu.pptx",
        sheetName: "Slayt1",
        nodes: [
          { title: "Tema 07", sub: "Boş kapak" },
          { title: "Tema 12", sub: "Boş başlık" },
          { title: "Tema 19", sub: "Boş madde" },
        ],
        table: OFFICE_AI_3_TEXT_DUMP,
      },
      {
        cueIndex: 3,
        beat: "warmup",
        visualMode: "live",
        section: "ŞABLON KAOSU",
        headline: "ŞABLON KAOSU",
        subhead: "Sıfırdan slayt. Metin yığını şablon klasöründe kaybolur.",
        bullets: ["Boş slayt", "Şablon ara", "Metin yığını"],
        tools: ["PowerPoint", "Word"],
        layout: "pptx",
        highlightCell: "A1",
        fileName: "Yonetim_Sunumu.pptx",
        sheetName: "Taslak",
        nodes: [
          { title: "Tema 07", sub: "Boş kapak" },
          { title: "Tema 12", sub: "Boş başlık" },
          { title: "Tema 19", sub: "Boş madde" },
        ],
        table: OFFICE_AI_3_TEXT_DUMP,
      },
      {
        cueIndex: 4,
        beat: "command",
        visualMode: "live",
        section: "SLAYT İSTE",
        headline: "SLAYT İSTE",
        subhead: "Metinden slayt taslağı iste. Biten sunum henüz açılmaz.",
        bullets: ["Tek fikir ver", "Görsel yön yaz", "Taslak kapalı"],
        tools: ["PowerPoint", "Copilot"],
        layout: "pptx",
        highlightCell: "A1",
        fileName: "Yonetim_Sunumu.pptx",
        sheetName: "Taslak",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_OFFICE_AI_3_COPILOT_PROMPT,
          replyLines: [],
        },
        nodes: [
          { title: "Yeni slayt", sub: "Taslak kapalı" },
          { title: "Yeni slayt", sub: "Spoiler yok" },
        ],
        table: OFFICE_AI_3_TEXT_DUMP,
      },
      {
        cueIndex: 5,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_3_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_3_COMPARE_AFTER_LABEL,
        },
        section: "HİYERARŞİ",
        headline: "HİYERARŞİ",
        subhead: "Beat 3 açılır: sol düz metin yığını, sağ görsel hiyerarşili slayt.",
        bullets: ["54.650 TL", "Kaya Gıda A.Ş.", "%15 Riskli Vade"],
        tools: ["PowerPoint", "Copilot"],
        layout: "pptx",
        highlightCell: "A1",
        fileName: "Yonetim_Sunumu.pptx",
        sheetName: "Slayt1",
        nodes: OFFICE_AI_3_DECK_NODES,
        table: OFFICE_AI_3_DECK_TABLE,
      },
      {
        cueIndex: 6,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_3_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_3_COMPARE_AFTER_LABEL,
        },
        section: "FARK ORTADA",
        headline: "FARK ORTADA",
        subhead: "Sol düz metin yığını. Sağ görsel hiyerarşili slayt — AI.",
        bullets: ["54.650 TL", "Kaya Gıda A.Ş.", "%15 Riskli Vade"],
        tools: ["PowerPoint", "Copilot"],
        layout: "pptx",
        highlightCell: "B1",
        fileName: "Yonetim_Sunumu.pptx",
        sheetName: "Slayt2",
        nodes: OFFICE_AI_3_DECK_NODES,
        table: OFFICE_AI_3_DECK_TABLE,
      },
      {
        cueIndex: 7,
        beat: "task",
        visualMode: "live",
        section: "CEBİNE KOY",
        headline: "CEBİNE KOY",
        subhead: "Üç adım: tek fikir, görsel yön, taslağı aktar.",
        bullets: ["Tek fikir / slayt", "Görsel yönlendir", "Taslağı aktar"],
        tools: ["PowerPoint", "Copilot"],
        layout: "pptx",
        highlightCell: "C1",
        fileName: "Yonetim_Sunumu.pptx",
        sheetName: "Slayt3",
        nodes: OFFICE_AI_3_DECK_NODES,
        table: OFFICE_AI_3_DECK_TABLE,
      },
      {
        cueIndex: 8,
        beat: "task",
        visualMode: "live",
        section: "SIRA SENDE",
        headline: "SIRA SENDE",
        subhead: "Kendi metnini tek tıkla slayt yapısına çevir. Sonra hata avı.",
        bullets: ["Kendi metnini seç", "Slayt yapısı", "5. ders hata avı köprüsü"],
        tools: ["PowerPoint", "Outlook"],
        layout: "pptx",
        highlightCell: "A1",
        fileName: "Yonetim_Sunumu.pptx",
        sheetName: "Slayt1",
        nodes: OFFICE_AI_3_DECK_NODES,
        table: OFFICE_AI_3_DECK_TABLE,
      },
    ],
  },
  "01_office_ai-4": {
    ...OFFICE,
    title: "E-Posta Akışı: Gelen Kutusu Sıfırlama",
    cues: [
      {
        cueIndex: 1,
        beat: "warmup",
        visualMode: "veo",
        section: "GİRİŞ KÖPRÜSÜ",
        headline: "GİRİŞ KÖPRÜSÜ",
        subhead: "Hata avı cebinde. Şimdi yüzlerce okunmamış mail stresi başlıyor.",
        bullets: ["Sayı kilidi cebinde", "Inbox kaosu", "Okunmamış sel"],
        tools: ["Outlook", "Copilot"],
        layout: "outlook",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.ost",
        sheetName: "Inbox",
        nodes: [
          { title: "Gelen Kutusu", sub: "142 okunmamış" },
          { title: "Taslaklar", sub: "Boş" },
          { title: "Arşiv", sub: "Kapalı" },
        ],
        table: OFFICE_AI_4_INBOX_DUMP,
      },
      {
        cueIndex: 2,
        beat: "warmup",
        visualMode: "live",
        section: "HOŞ GELDİN",
        headline: "HOŞ GELDİN",
        subhead: "Gözde masada. Yüzlerce okunmamış satır, gelen kutusu kaosu.",
        bullets: ["Selamlar, ben Gözde", "142 okunmamış", "Inbox kaos"],
        tools: ["Outlook", "Copilot"],
        layout: "outlook",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.ost",
        sheetName: "Inbox",
        nodes: [
          { title: "Gelen Kutusu", sub: "142 okunmamış" },
          { title: "Taslaklar", sub: "Boş" },
          { title: "Arşiv", sub: "Kapalı" },
        ],
        table: OFFICE_AI_4_INBOX_DUMP,
      },
      {
        cueIndex: 3,
        beat: "warmup",
        visualMode: "live",
        section: "INBOX KAOSU",
        headline: "INBOX KAOSU",
        subhead: "Okunmamış mail yığını. Etiket yok, taslak yok, arşiv kapalı.",
        bullets: ["Okunmamış sel", "Etiket yok", "Taslak kapalı"],
        tools: ["Outlook", "Gmail"],
        layout: "outlook",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.ost",
        sheetName: "Inbox",
        nodes: [
          { title: "Gelen Kutusu", sub: "142 okunmamış" },
          { title: "Taslaklar", sub: "Boş" },
          { title: "Arşiv", sub: "Kapalı" },
        ],
        table: OFFICE_AI_4_INBOX_DUMP,
      },
      {
        cueIndex: 4,
        beat: "command",
        visualMode: "live",
        section: "TASLAK YAZ",
        headline: "TASLAK YAZ",
        subhead: "Etiketle ve taslak yanıt iste. Sıfır kutu henüz açılmaz.",
        bullets: ["Önem sırası", "Taslak yanıt", "Sıfır kutu kapalı"],
        tools: ["Outlook", "Copilot", "Gemini"],
        layout: "outlook",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.ost",
        sheetName: "Inbox",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_OUTLOOK_COPILOT_PROMPT,
          replyLines: [],
        },
        nodes: [
          { title: "Gelen Kutusu", sub: "Komut açık" },
          { title: "Taslaklar", sub: "Spoiler yok" },
        ],
        table: OFFICE_AI_4_INBOX_DUMP,
      },
      {
        cueIndex: 5,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_4_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_4_COMPARE_AFTER_LABEL,
        },
        section: "SIFIR KUTU",
        headline: "SIFIR KUTU",
        subhead: "Beat 3 açılır: sol 142 okunmamış mail, sağ sıfırlanmış kutu.",
        bullets: ["Acil etiket", "Taslak yanıt", "Arşiv"],
        tools: ["Outlook", "Copilot"],
        layout: "outlook",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.ost",
        sheetName: "Inbox",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_OUTLOOK_COPILOT_PROMPT,
          replyLines: [],
        },
        nodes: OFFICE_AI_4_ZERO_NODES,
        table: OFFICE_AI_4_ZERO_TABLE,
      },
      {
        cueIndex: 6,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_4_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_4_COMPARE_AFTER_LABEL,
        },
        section: "FARK ORTADA",
        headline: "FARK ORTADA",
        subhead: "Sol 142 okunmamış mail. Sağ sıfırlanmış kutu — AI.",
        bullets: ["Acil etiket", "Taslak yanıt", "Arşiv"],
        tools: ["Outlook", "Copilot"],
        layout: "outlook",
        highlightCell: "B1",
        fileName: "Gelen_Kutusu.ost",
        sheetName: "Inbox",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_OUTLOOK_COPILOT_PROMPT,
          replyLines: [],
        },
        nodes: OFFICE_AI_4_ZERO_NODES,
        table: OFFICE_AI_4_ZERO_TABLE,
      },
      {
        cueIndex: 7,
        beat: "task",
        visualMode: "live",
        section: "CEBİNE KOY",
        headline: "CEBİNE KOY",
        subhead: "Üç adım: etiketle, taslak yazdır, arşive kaldır.",
        bullets: ["Önemle etiketle", "Taslak yazdır", "Arşive kaldır"],
        tools: ["Outlook", "Copilot"],
        layout: "outlook",
        highlightCell: "C1",
        fileName: "Gelen_Kutusu.ost",
        sheetName: "Inbox",
        nodes: OFFICE_AI_4_ZERO_NODES,
        table: OFFICE_AI_4_ZERO_TABLE,
      },
      {
        cueIndex: 8,
        beat: "task",
        visualMode: "live",
        section: "SIRA SENDE",
        headline: "SIRA SENDE",
        subhead: "Kendi gelen kutunu 3 kuralla sıfırla. Sonra Gmail kapısı.",
        bullets: ["Kendi kutunu seç", "Üç kural", "7. ders Gmail köprüsü"],
        tools: ["Outlook", "Copilot"],
        layout: "outlook",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.ost",
        sheetName: "Inbox",
        nodes: OFFICE_AI_4_ZERO_NODES,
        table: OFFICE_AI_4_ZERO_TABLE,
      },
    ],
  },
  "01_office_ai-5": {
    ...OFFICE,
    title: "İstisnalar & Hata Avı: AI Yanılınca",
    cues: [
      {
        cueIndex: 1,
        beat: "warmup",
        visualMode: "veo",
        section: "GİRİŞ KÖPRÜSÜ",
        headline: "GİRİŞ KÖPRÜSÜ",
        subhead: "Sunum Fabrikası cebinde. Şimdi rapordaki halüsinasyon stresi başlıyor.",
        bullets: ["Slayt hiyerarşisi", "Aşırı güven", "Hata gömülü"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_ERROR_HUNT_FILE_NAME,
        sheetName: ACADEMY_ERROR_HUNT_SHEET_NAME,
        formulaBar: "Cari",
        table: ACADEMY_ERROR_HUNT_HALLUCINATED_TABLE,
      },
      {
        cueIndex: 2,
        beat: "warmup",
        visualMode: "live",
        section: "HOŞ GELDİN",
        headline: "HOŞ GELDİN",
        subhead: "Gözde masada. Özet akıcı durur; gözü kapalı güvenme. Sapma henüz kırmızı değil.",
        bullets: ["Selamlar, ben Gözde", "Özete kör güven", "Halüsinasyon riski"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_ERROR_HUNT_FILE_NAME,
        sheetName: ACADEMY_ERROR_HUNT_SHEET_NAME,
        formulaBar: "Cari",
        table: ACADEMY_ERROR_HUNT_HALLUCINATED_TABLE,
      },
      {
        cueIndex: 3,
        beat: "warmup",
        visualMode: "live",
        section: "AŞIRI GÜVEN",
        headline: "AŞIRI GÜVEN",
        subhead: "Özete gözü kapalı güvenme. 21.500 ve 59.450 gömülü durur. Dedektif veri kapalı.",
        bullets: ["Uydurma özet", "Şişmiş toplam", "Spoiler yok"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_ERROR_HUNT_FILE_NAME,
        sheetName: ACADEMY_ERROR_HUNT_SHEET_NAME,
        formulaBar: "Cari",
        table: ACADEMY_ERROR_HUNT_HALLUCINATED_TABLE,
      },
      {
        cueIndex: 4,
        beat: "command",
        visualMode: "live",
        section: "HATA AVI",
        headline: "HATA AVI",
        subhead: "Çapraz kontrol istemi yazılır. Kırmızı hücreye zoom; kontrollü veri yok.",
        bullets: ["Veriyi yükle", "Çapraz sorgu", "Sapan hücre"],
        tools: ["Excel", "Copilot", "Gemini"],
        layout: "excel",
        highlightCell: "D4",
        zoomA1: true,
        errorCells: ACADEMY_ERROR_HUNT_FLAG_CELLS,
        fileName: ACADEMY_ERROR_HUNT_FILE_NAME,
        sheetName: ACADEMY_ERROR_HUNT_SHEET_NAME,
        formulaBar: "21.500",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_ERROR_HUNT_COPILOT_PROMPT,
          replyLines: [],
        },
        table: ACADEMY_ERROR_HUNT_HALLUCINATED_TABLE,
      },
      {
        cueIndex: 5,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_5_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_5_COMPARE_AFTER_LABEL,
        },
        section: "AI DEDEKTİF",
        headline: "AI DEDEKTİF",
        subhead: "Beat 3 açılır: sol kör süreç (halüsinasyonlu veri), sağ kontrollü dedektif veri.",
        bullets: ["21.500 düzeltildi", "59.450 düştü", "Formülle kilit"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "D4",
        fileName: ACADEMY_ERROR_HUNT_FILE_NAME,
        sheetName: ACADEMY_ERROR_HUNT_SHEET_NAME,
        formulaBar: "=B4+C4",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_ERROR_HUNT_COPILOT_PROMPT,
          replyLines: [],
        },
        table: ACADEMY_ERROR_HUNT_VERIFIED_TABLE,
      },
      {
        cueIndex: 6,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_5_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_5_COMPARE_AFTER_LABEL,
        },
        section: "FARK ORTADA",
        headline: "FARK ORTADA",
        subhead: "Sol 59.450 halüsinasyonlu veri. Sağ 50.450 kontrollü veri. Kör süreç vs dedektif süreç.",
        bullets: ["Sol kör süreç", "Sağ dedektif", "İnsan gözü"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "D5",
        fileName: ACADEMY_ERROR_HUNT_FILE_NAME,
        sheetName: ACADEMY_ERROR_HUNT_SHEET_NAME,
        formulaBar: "=D2+D3+D4",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_ERROR_HUNT_COPILOT_PROMPT,
          replyLines: [],
        },
        table: ACADEMY_ERROR_HUNT_VERIFIED_TABLE,
      },
      {
        cueIndex: 7,
        beat: "task",
        visualMode: "live",
        section: "CEBİNE KOY",
        headline: "CEBİNE KOY",
        subhead: "Üç adım: formülle doğrula, mantık hatası sor, insan gözü kilitle.",
        bullets: ["Formülle doğrula", "Mantık hatası sor", "İnsan gözü kilitle"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "D5",
        fileName: ACADEMY_ERROR_HUNT_FILE_NAME,
        sheetName: ACADEMY_ERROR_HUNT_SHEET_NAME,
        formulaBar: "=D2+D3+D4",
        table: ACADEMY_ERROR_HUNT_VERIFIED_TABLE,
      },
      {
        cueIndex: 8,
        beat: "task",
        visualMode: "live",
        section: "SIRA SENDE",
        headline: "SIRA SENDE",
        subhead: "Kendi tablonda uydurma rakamı yakala. Sonra e-posta ritüeli.",
        bullets: ["Kendi verini seç", "Çapraz sorgu", "6. ders e-posta köprüsü"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "D4",
        fileName: ACADEMY_ERROR_HUNT_FILE_NAME,
        sheetName: ACADEMY_ERROR_HUNT_SHEET_NAME,
        formulaBar: "=B4+C4",
        table: ACADEMY_ERROR_HUNT_VERIFIED_TABLE,
      },
    ],
  },
  "01_office_ai-6": {
    ...OFFICE,
    title: "Haftalık Sistem: 30 Dakikalık Rutin",
    cues: [
      {
        cueIndex: 1,
        beat: "warmup",
        visualMode: "veo",
        section: "GİRİŞ KÖPRÜSÜ",
        headline: "GİRİŞ KÖPRÜSÜ",
        subhead: "Word ataş cebinde. Şimdi alışkanlığı Cuma takvimine bağla.",
        bullets: ["Word ataş", "Kriz tekrarı", "Cuma penceresi"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_WEEKLY_ROUTINE_FILE_NAME,
        sheetName: ACADEMY_WEEKLY_ROUTINE_SHEET_NAME,
        formulaBar: "Cuma",
        table: ACADEMY_WEEKLY_ROUTINE_CHAOS_TABLE,
      },
      {
        cueIndex: 2,
        beat: "warmup",
        visualMode: "live",
        section: "HOŞ GELDİN",
        headline: "HOŞ GELDİN",
        subhead: "Gözde masada. Otuz dakika takvime yazılır. Sınav henüz kapalı.",
        bullets: ["Selamlar, ben Gözde", "Cuma 30 dakika", "Sınav tüm dersler bitince"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_WEEKLY_ROUTINE_FILE_NAME,
        sheetName: ACADEMY_WEEKLY_ROUTINE_SHEET_NAME,
        formulaBar: "Cuma",
        table: ACADEMY_WEEKLY_ROUTINE_CHAOS_TABLE,
      },
      {
        cueIndex: 3,
        beat: "warmup",
        visualMode: "live",
        section: "DAĞINIK HAFTA",
        headline: "DAĞINIK HAFTA",
        subhead: "Kriz her gün yeniden icat edilir. Sistemli Cuma tablosu kapalı.",
        bullets: ["Kopyala-yapıştır", "Gece mesaisi", "Spoiler yok"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_WEEKLY_ROUTINE_FILE_NAME,
        sheetName: ACADEMY_WEEKLY_ROUTINE_SHEET_NAME,
        formulaBar: "Cuma",
        table: ACADEMY_WEEKLY_ROUTINE_CHAOS_TABLE,
      },
      {
        cueIndex: 4,
        beat: "command",
        visualMode: "live",
        section: "OTUZ DAKİKA",
        headline: "OTUZ DAKİKA",
        subhead: "Üç blok komutu yazılır. Sistemli tablo yok; ataşa zoom.",
        bullets: ["Takvime yaz", "Üç bloğu kur", "E-posta"],
        tools: ["Excel", "Copilot", "Gemini"],
        layout: "excel",
        highlightCell: "A1",
        zoomA1: true,
        errorCells: ACADEMY_WEEKLY_ROUTINE_FLAG_CELLS,
        fileName: ACADEMY_WEEKLY_ROUTINE_FILE_NAME,
        sheetName: ACADEMY_WEEKLY_ROUTINE_SHEET_NAME,
        formulaBar: "90 dk",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_WEEKLY_ROUTINE_COPILOT_PROMPT,
          replyLines: [],
        },
        table: ACADEMY_WEEKLY_ROUTINE_CHAOS_TABLE,
      },
      {
        cueIndex: 5,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_6_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_6_COMPARE_AFTER_LABEL,
        },
        section: "ÜÇ BLOK",
        headline: "ÜÇ BLOK",
        subhead: "Beat 3 açılır: sol dağınık hafta, sağ 10 Excel + 10 slayt + 10 e-posta.",
        bullets: ["Excel temizlik", "Slayt özet", "E-posta sıfırlama"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_WEEKLY_ROUTINE_FILE_NAME,
        sheetName: ACADEMY_WEEKLY_ROUTINE_SHEET_NAME,
        formulaBar: "0–10",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_WEEKLY_ROUTINE_COPILOT_PROMPT,
          replyLines: [],
        },
        table: ACADEMY_WEEKLY_ROUTINE_SYSTEM_TABLE,
      },
      {
        cueIndex: 6,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_6_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_6_COMPARE_AFTER_LABEL,
        },
        section: "FARK ORTADA",
        headline: "FARK ORTADA",
        subhead: "Sol 90 dk yetiştirme. Sağ 10+10+10 kilitli blok. Kriz vs takvim.",
        bullets: ["Excel temizlik", "Slayt özet", "E-posta sıfırlama"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "C1",
        fileName: ACADEMY_WEEKLY_ROUTINE_FILE_NAME,
        sheetName: ACADEMY_WEEKLY_ROUTINE_SHEET_NAME,
        formulaBar: "20–30",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_WEEKLY_ROUTINE_COPILOT_PROMPT,
          replyLines: [],
        },
        table: ACADEMY_WEEKLY_ROUTINE_SYSTEM_TABLE,
      },
      {
        cueIndex: 7,
        beat: "task",
        visualMode: "live",
        section: "CEBİNE KOY",
        headline: "CEBİNE KOY",
        subhead: "Üç adım: takvime yaz, ataş veya Copilot, maskeli kısa özet.",
        bullets: ["Takvime yaz", "Ataş veya Copilot", "Maskeli kısa özet"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "C1",
        fileName: ACADEMY_WEEKLY_ROUTINE_FILE_NAME,
        sheetName: ACADEMY_WEEKLY_ROUTINE_SHEET_NAME,
        formulaBar: "20–30",
        table: ACADEMY_WEEKLY_ROUTINE_SYSTEM_TABLE,
      },
      {
        cueIndex: 8,
        beat: "task",
        visualMode: "live",
        section: "SIRA SENDE",
        headline: "SIRA SENDE",
        subhead: "Cuma 30’u takvime koy. Sınav Kapısı Açıldı. Baraj 70.",
        bullets: ["Takvime koy", "10+10+10", "Sınav Kapısı Açıldı"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_WEEKLY_ROUTINE_FILE_NAME,
        sheetName: ACADEMY_WEEKLY_ROUTINE_SHEET_NAME,
        formulaBar: "Cuma",
        table: ACADEMY_WEEKLY_ROUTINE_SYSTEM_TABLE,
      },
    ],
  },
  "01_office_ai-g1": {
    ...OFFICE,
    title: "Gmail + Gemini ile Gelen Kutusu ve Aksiyon Listesi",
    cues: [
      {
        cueIndex: 1,
        beat: "warmup",
        visualMode: "veo",
        section: "GİRİŞ KÖPRÜSÜ",
        headline: "GİRİŞ KÖPRÜSÜ",
        subhead: "Maili ChatGPT’ye kopyalamak kutuyu koparır. Asıl kapı Gmail içinde Gemini.",
        bullets: ["Atlanmış kapı", "Gmail kapısı", "Gemini yerleşik"],
        tools: ["Gmail", "Gemini"],
        layout: "gmail",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.gmail",
        sheetName: "Inbox",
        nodes: [
          { title: "Gelen Kutusu", sub: "Son 24 saat" },
          { title: "Gemini", sub: "Kapalı" },
          { title: "Arşivlik", sub: "Karışık" },
        ],
        table: OFFICE_AI_G1_CARRY_TABLE,
      },
      {
        cueIndex: 2,
        beat: "warmup",
        visualMode: "live",
        section: "HOŞ GELDİN",
        headline: "HOŞ GELDİN",
        subhead: "Gözde masada. Kim, ne, ne zaman kilitlenir; kutu Gmail’de kalır.",
        bullets: ["Selamlar, ben Gözde", "Kutu kopuk değil", "Yerleşik yol"],
        tools: ["Gmail", "Gemini"],
        layout: "gmail",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.gmail",
        sheetName: "Inbox",
        nodes: [
          { title: "Gelen Kutusu", sub: "Son 24 saat" },
          { title: "Gemini", sub: "Bekler" },
          { title: "Arşivlik", sub: "Karışık" },
        ],
        table: OFFICE_AI_G1_CARRY_TABLE,
      },
      {
        cueIndex: 3,
        beat: "warmup",
        visualMode: "live",
        section: "TAŞIMA SU",
        headline: "TAŞIMA SU",
        subhead: "1. ve 2. kapı dururken mailleri dış sohbete yapıştırmak atlanmış kapıdır.",
        bullets: ["Önce yerleşik panel", "Yoksa ataş", "Son çare maskeli kısa"],
        tools: ["Gmail", "Gemini"],
        layout: "gmail",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.gmail",
        sheetName: "Inbox",
        nodes: [
          { title: "Taşıma su", sub: "Kopyala-yapıştır" },
          { title: "Gelen kutusu", sub: "Kopuk" },
        ],
        table: OFFICE_AI_G1_CARRY_TABLE,
      },
      {
        cueIndex: 4,
        beat: "command",
        visualMode: "live",
        section: "GEMİNİ AÇ",
        headline: "GEMİNİ AÇ",
        subhead: "Gemini paneline yaz. ChatGPT’ye kopyalama. Özet henüz yok.",
        bullets: ["Yan paneli aç", "İstemi yaz", "Özet kapalı"],
        tools: ["Gmail", "Gemini"],
        layout: "gmail",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.gmail",
        sheetName: "Inbox",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_GMAIL_GEMINI_PROMPT,
          replyLines: [],
        },
        nodes: [
          { title: "Gelen Kutusu", sub: "Gemini açık" },
          { title: "Özet", sub: "Spoiler yok" },
        ],
        table: OFFICE_AI_G1_CARRY_TABLE,
      },
      {
        cueIndex: 5,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_G1_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_G1_COMPARE_AFTER_LABEL,
        },
        section: "YERLEŞİK YOL",
        headline: "YERLEŞİK YOL",
        subhead: "Beat 3 açılır: sol kutudan kopuk taşıma su, sağ Gmail içi Gemini.",
        bullets: ["Ödeme özeti", "Acil aksiyon", "Arşivlik"],
        tools: ["Gmail", "Gemini"],
        layout: "gmail",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.gmail",
        sheetName: "Inbox",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_GMAIL_GEMINI_PROMPT,
          replyLines: [],
        },
        nodes: OFFICE_AI_G1_NATIVE_NODES,
        table: OFFICE_AI_G1_NATIVE_TABLE,
      },
      {
        cueIndex: 6,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_G1_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_G1_COMPARE_AFTER_LABEL,
        },
        section: "FARK ORTADA",
        headline: "FARK ORTADA",
        subhead: "Sol taşıma su. Sağ yerleşik Gemini — kutu yerinde kaldı.",
        bullets: ["Ödeme özeti", "Acil aksiyon", "Arşivlik"],
        tools: ["Gmail", "Gemini"],
        layout: "gmail",
        highlightCell: "B1",
        fileName: "Gelen_Kutusu.gmail",
        sheetName: "Inbox",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_GMAIL_GEMINI_PROMPT,
          replyLines: [],
        },
        nodes: OFFICE_AI_G1_NATIVE_NODES,
        table: OFFICE_AI_G1_NATIVE_TABLE,
      },
      {
        cueIndex: 7,
        beat: "task",
        visualMode: "live",
        section: "CEBİNE KOY",
        headline: "CEBİNE KOY",
        subhead: "Üç adım: yerleşik paneli aç, aksiyon tablosu iste, onaylamadan gönderme.",
        bullets: ["Yerleşik paneli aç", "Aksiyon tablosu iste", "Onaylamadan gönderme"],
        tools: ["Gmail", "Gemini"],
        layout: "gmail",
        highlightCell: "C1",
        fileName: "Gelen_Kutusu.gmail",
        sheetName: "Inbox",
        nodes: OFFICE_AI_G1_NATIVE_NODES,
        table: OFFICE_AI_G1_NATIVE_TABLE,
      },
      {
        cueIndex: 8,
        beat: "task",
        visualMode: "live",
        section: "SIRA SENDE",
        headline: "SIRA SENDE",
        subhead: "Kendi Gmail’inde Gemini panelini aç. Son 24 saati yerinde tara.",
        bullets: ["Kendi Gmail’in", "Üç kural", "Word ataş köprüsü"],
        tools: ["Gmail", "Gemini"],
        layout: "gmail",
        highlightCell: "A1",
        fileName: "Gelen_Kutusu.gmail",
        sheetName: "Inbox",
        nodes: OFFICE_AI_G1_NATIVE_NODES,
        table: OFFICE_AI_G1_NATIVE_TABLE,
      },
    ],
  },
  "01_office_ai-w1": {
    ...OFFICE,
    title: "Word ve Uzun Doküman Analizi: Sözleşme, Dilekçe, Rapor",
    cues: [
      {
        cueIndex: 1,
        beat: "warmup",
        visualMode: "veo",
        section: "GİRİŞ KÖPRÜSÜ",
        headline: "GİRİŞ KÖPRÜSÜ",
        subhead: "Sözleşmeyi parça parça kopyalamak zahmetli yoldur. Asıl kapı ataş.",
        bullets: ["Ataş kapısı", "Spesifik paragraf", "Yerinde analiz"],
        tools: ["Word", "Gemini"],
        layout: "word",
        highlightCell: "A1",
        fileName: "Sozlesme_Kaya_Gida.docx",
        sheetName: "Sözleşme",
        nodes: [
          { title: "Sözleşme", sub: "Word belgesi kapalı" },
          { title: "Ataş", sub: "Bekler" },
          { title: "Maddeler", sub: "Spoiler yok" },
        ],
        table: OFFICE_AI_W1_COPY_TABLE,
      },
      {
        cueIndex: 2,
        beat: "warmup",
        visualMode: "live",
        section: "HOŞ GELDİN",
        headline: "HOŞ GELDİN",
        subhead: "Gözde masada. Dosyayı ataşla yüklersin. Spesifik bir paragrafı soracaksan, onu istemine eklersin.",
        bullets: ["Selamlar, ben Gözde", "Uzun doküman", "Dosya yükle"],
        tools: ["Word", "Gemini"],
        layout: "word",
        highlightCell: "A1",
        fileName: "Sozlesme_Kaya_Gida.docx",
        sheetName: "Sözleşme",
        nodes: [
          { title: "Sözleşme", sub: "Word belgesi bekler" },
          { title: "Ataş", sub: "Kapalı" },
          { title: "Maddeler", sub: "Spoiler yok" },
        ],
        table: OFFICE_AI_W1_COPY_TABLE,
      },
      {
        cueIndex: 3,
        beat: "warmup",
        visualMode: "live",
        section: "PARÇA PARÇA",
        headline: "PARÇA PARÇA",
        subhead: "Sayfa 4, 11, 18’den kopuk cümleler. Bağlam kaybolur. Tüm dosyayı böyle taşıma.",
        bullets: ["Sayfa kopuk", "Kopuk bağlam", "Zahmetli yol"],
        tools: ["Word", "Gemini"],
        layout: "word",
        highlightCell: "A1",
        fileName: "Sozlesme_Kaya_Gida.docx",
        sheetName: "Sözleşme",
        nodes: [
          { title: "Zahmetli yol", sub: "Parça parça" },
          { title: "Sözleşme", sub: "Kopuk" },
        ],
        table: OFFICE_AI_W1_COPY_TABLE,
      },
      {
        cueIndex: 4,
        beat: "command",
        visualMode: "live",
        section: "ATAŞ YÜKLE",
        headline: "ATAŞ YÜKLE",
        subhead: "Sözleşmeyi Word belgesi olarak ataşla. İstem yazılır. Madde listesi henüz yok.",
        bullets: ["Dosyayı ataşla", "İstemi yaz", "Liste kapalı"],
        tools: ["Word", "Gemini"],
        layout: "word",
        highlightCell: "A1",
        fileName: "Sozlesme_Kaya_Gida.docx",
        sheetName: "Sözleşme",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_WORD_UPLOAD_PROMPT,
          replyLines: [],
        },
        nodes: [
          { title: "Ataş", sub: "Sozlesme_Kaya_Gida.docx" },
          { title: "Maddeler", sub: "Spoiler yok" },
        ],
        table: OFFICE_AI_W1_COPY_TABLE,
      },
      {
        cueIndex: 5,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_W1_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_W1_COMPARE_AFTER_LABEL,
        },
        section: "YERİNDE ANALİZ",
        headline: "YERİNDE ANALİZ",
        subhead: "Beat 3 açılır: sol parça parça kopya, sağ doğrudan dosya yükleme.",
        bullets: ["Cezai şart", "Fesih koşulu", "Gizlilik"],
        tools: ["Word", "Gemini"],
        layout: "word",
        highlightCell: "A1",
        fileName: "Sozlesme_Kaya_Gida.docx",
        sheetName: "Sözleşme",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_WORD_UPLOAD_PROMPT,
          replyLines: [],
        },
        nodes: OFFICE_AI_W1_UPLOAD_NODES,
        table: OFFICE_AI_W1_UPLOAD_TABLE,
      },
      {
        cueIndex: 6,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_W1_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_W1_COMPARE_AFTER_LABEL,
        },
        section: "FARK ORTADA",
        headline: "FARK ORTADA",
        subhead: "Sol zahmetli yol. Sağ yerinde doküman analizi — tam dosya.",
        bullets: ["Cezai şart", "Fesih koşulu", "Gizlilik"],
        tools: ["Word", "Gemini"],
        layout: "word",
        highlightCell: "B1",
        fileName: "Sozlesme_Kaya_Gida.docx",
        sheetName: "Sözleşme",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_WORD_UPLOAD_PROMPT,
          replyLines: [],
        },
        nodes: OFFICE_AI_W1_UPLOAD_NODES,
        table: OFFICE_AI_W1_UPLOAD_TABLE,
      },
      {
        cueIndex: 7,
        beat: "task",
        visualMode: "live",
        section: "CEBİNE KOY",
        headline: "CEBİNE KOY",
        subhead: "Üç adım: dosyayı ataşla, üç işi ayrı iste, imzayı kendin at.",
        bullets: ["Dosyayı ataşla", "Üç işi ayrı iste", "İmzayı kendin at"],
        tools: ["Word", "Gemini"],
        layout: "word",
        highlightCell: "C1",
        fileName: "Sozlesme_Kaya_Gida.docx",
        sheetName: "Sözleşme",
        nodes: OFFICE_AI_W1_UPLOAD_NODES,
        table: OFFICE_AI_W1_UPLOAD_TABLE,
      },
      {
        cueIndex: 8,
        beat: "task",
        visualMode: "live",
        section: "SIRA SENDE",
        headline: "SIRA SENDE",
        subhead: "Kendi sözleşmeni ataşla. Spesifik bir paragrafı sorabilirsin. Sonra Cuma 30.",
        bullets: ["Kendi dosyan", "Üç kural", "9. ders Cuma köprüsü"],
        tools: ["Word", "Gemini"],
        layout: "word",
        highlightCell: "A1",
        fileName: "Sozlesme_Kaya_Gida.docx",
        sheetName: "Sözleşme",
        nodes: OFFICE_AI_W1_UPLOAD_NODES,
        table: OFFICE_AI_W1_UPLOAD_TABLE,
      },
    ],
  },
  "01_office_ai-k1": {
    ...OFFICE,
    title: "KVKK, Şirket Sırları ve Maskeleme: Ne Yüklenmez?",
    cues: [
      {
        cueIndex: 1,
        beat: "warmup",
        visualMode: "veo",
        section: "GİRİŞ KÖPRÜSÜ",
        headline: "GİRİŞ KÖPRÜSÜ",
        subhead: "Müşteri listesi, IBAN ve maaş açık yapay zekâ ekranına yüklenmez.",
        bullets: ["Ham liste yasak", "Maske zorunlu", "3. Kapı kısa"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_KVKK_FILE_NAME,
        sheetName: ACADEMY_KVKK_SHEET_NAME,
        formulaBar: "Maske",
        table: ACADEMY_KVKK_RAW_TABLE,
      },
      {
        cueIndex: 2,
        beat: "warmup",
        visualMode: "live",
        section: "HOŞ GELDİN",
        headline: "HOŞ GELDİN",
        subhead: "Gözde masada. Kişisel veri ve şirket sırrı sohbetin işi değildir.",
        bullets: ["Selamlar, ben Gözde", "KVKK maskeleme", "Sınav tüm dersler sonra"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_KVKK_FILE_NAME,
        sheetName: ACADEMY_KVKK_SHEET_NAME,
        formulaBar: "Maske",
        table: ACADEMY_KVKK_RAW_TABLE,
      },
      {
        cueIndex: 3,
        beat: "warmup",
        visualMode: "live",
        section: "YASAK LİSTE",
        headline: "YASAK LİSTE",
        subhead: "Ad, telefon, IBAN, maaş, T.C. Kimlik No. Maskeli tablo kapalı.",
        bullets: ["Kişi satırı", "Açık IBAN", "Spoiler yok"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "B2",
        errorCells: ACADEMY_KVKK_FLAG_CELLS,
        fileName: ACADEMY_KVKK_FILE_NAME,
        sheetName: ACADEMY_KVKK_SHEET_NAME,
        formulaBar: "Maske",
        table: ACADEMY_KVKK_RAW_TABLE,
      },
      {
        cueIndex: 4,
        beat: "command",
        visualMode: "live",
        section: "MASKELE",
        headline: "MASKELE",
        subhead: "Ayşe Kaya yerine Müşteri A. IBAN yerine MASKELİ_IBAN.",
        bullets: ["Müşteri A", "MASKELİ_IBAN", "Kısa soru"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        zoomA1: true,
        errorCells: ACADEMY_KVKK_FLAG_CELLS,
        fileName: ACADEMY_KVKK_FILE_NAME,
        sheetName: ACADEMY_KVKK_SHEET_NAME,
        formulaBar: ACADEMY_KVKK_COPILOT_PROMPT,
        copilot: {
          hideReply: true,
          prompt: ACADEMY_KVKK_COPILOT_PROMPT,
          replyLines: [],
        },
        table: ACADEMY_KVKK_RAW_TABLE,
      },
      {
        cueIndex: 5,
        beat: "command",
        visualMode: "split",
        section: "ÜÇÜNCÜ KAPI",
        headline: "ÜÇÜNCÜ KAPI",
        subhead: "1. Kapı yerleşik panel, 2. Kapı ataş, 3. Kapı maskeli kısa.",
        bullets: ["Yerleşik panel", "Ataş yükleme", "Maskeli kısa"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_KVKK_FILE_NAME,
        sheetName: ACADEMY_KVKK_SHEET_NAME,
        formulaBar: "3. Kapı",
        copilot: {
          hideReply: true,
          prompt: ACADEMY_KVKK_COPILOT_PROMPT,
          replyLines: [],
        },
        table: ACADEMY_KVKK_RAW_TABLE,
      },
      {
        cueIndex: 6,
        beat: "comparison",
        visualMode: "split",
        compare: {
          beforeCueIndex: 3,
          beforeLabel: ACADEMY_OFFICE_AI_K1_COMPARE_BEFORE_LABEL,
          afterLabel: ACADEMY_OFFICE_AI_K1_COMPARE_AFTER_LABEL,
        },
        section: "FARK ORTADA",
        headline: "FARK ORTADA",
        subhead: "Sol Ayşe Kaya ve açık IBAN. Sağ Müşteri A ve MASKELİ_IBAN.",
        bullets: ["Sol açık kimlik", "Sağ maske", "Araç fark etmez"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_KVKK_FILE_NAME,
        sheetName: ACADEMY_KVKK_SHEET_NAME,
        formulaBar: "Maske",
        table: ACADEMY_KVKK_MASKED_TABLE,
      },
      {
        cueIndex: 7,
        beat: "task",
        visualMode: "live",
        section: "CEBİNE KOY",
        headline: "CEBİNE KOY",
        subhead: "Üç adım: ham veri yükleme, maskeleyip sor, 3. Kapı kısa özet.",
        bullets: ["Ham veri yükleme", "Maskeleyip sor", "3. Kapı kısa özet"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_KVKK_FILE_NAME,
        sheetName: ACADEMY_KVKK_SHEET_NAME,
        formulaBar: "Maske",
        table: ACADEMY_KVKK_MASKED_TABLE,
      },
      {
        cueIndex: 8,
        beat: "task",
        visualMode: "live",
        section: "SIRA SENDE",
        headline: "SIRA SENDE",
        subhead: "Kendi listeni maskele. Sıradaki kapı rapordur; sınav kapanıştan sonra açılır.",
        bullets: ["Kendi listen", "Üç kural", "3. ders rapor köprüsü"],
        tools: ["Excel", "Copilot"],
        layout: "excel",
        highlightCell: "A1",
        fileName: ACADEMY_KVKK_FILE_NAME,
        sheetName: ACADEMY_KVKK_SHEET_NAME,
        formulaBar: "Maske",
        table: ACADEMY_KVKK_MASKED_TABLE,
      },
    ],
  },
  "02_ecommerce_ai-1": { ...COMMERCE, title: "Mağaza Röntgeni: Nerede Kan Kaybediyorsun", cues: EMPTY_CUES },
  "02_ecommerce_ai-2": { ...COMMERCE, title: "Liste Hızlandırma: Başlık + Açıklama Sistemi", cues: EMPTY_CUES },
  "02_ecommerce_ai-3": { ...COMMERCE, title: "Yorum & Soru Madeni: İade Düşürme", cues: EMPTY_CUES },
  "02_ecommerce_ai-4": { ...COMMERCE, title: "Rakip & Fiyat Radarı: Kör Uçma", cues: EMPTY_CUES },
  "02_ecommerce_ai-5": { ...COMMERCE, title: "Kampanya & Reklam Metni: Tıklatan Dil", cues: EMPTY_CUES },
  "02_ecommerce_ai-6": { ...COMMERCE, title: "Haftalık Operasyon Rutini + Sınav Köprüsü", cues: EMPTY_CUES },
  "03_social_media_ai-1": { ...SOCIAL, title: "İçerik Stoku: 1 Fikirden 10 Parça", cues: EMPTY_CUES },
  "03_social_media_ai-2": { ...SOCIAL, title: "Görsel Hattı: Ürün Çekimi + Afiş", cues: EMPTY_CUES },
  "03_social_media_ai-3": { ...SOCIAL, title: "Video Hattı: Reels Kurgu Sistemi", cues: EMPTY_CUES },
  "03_social_media_ai-4": { ...SOCIAL, title: "Metin Hattı: Açıklama + Hashtag + CTA", cues: EMPTY_CUES },
  "03_social_media_ai-5": { ...SOCIAL, title: "Kalite Kapısı: AI Kokusu Temizliği", cues: EMPTY_CUES },
  "03_social_media_ai-6": { ...SOCIAL, title: "Yayın Rutini: Haftada 3 + Sınav Köprüsü", cues: EMPTY_CUES },
  "04_chatbot_nocode-1": { ...BOT, title: "KOBİ Acısı: Kaçan Mesaj, Kaçan Randevu", cues: EMPTY_CUES },
  "04_chatbot_nocode-2": { ...BOT, title: "İlk Bot: Karşılama + SSS + Randevu", cues: EMPTY_CUES },
  "04_chatbot_nocode-3": { ...BOT, title: "WhatsApp Bağlantısı: Canlıya Alma", cues: EMPTY_CUES },
  "04_chatbot_nocode-4": { ...BOT, title: "Bozulunca: Yanlış Anlama + Öfke Senaryosu", cues: EMPTY_CUES },
  "04_chatbot_nocode-5": {
    ...BOT,
    title: "Teslim Seti: Keşif + Teklif + Kurulum Checklist",
    cues: EMPTY_CUES,
  },
  "04_chatbot_nocode-6": {
    ...BOT,
    title: "İlk Müşteri Oyunu: Pilot Kapatma + Sınav Köprüsü",
    cues: EMPTY_CUES,
  },
  "05_prompt_practice-1": { ...PROMPT, title: "Neden Saçmalıyor: 5 Kötü İstem", cues: EMPTY_CUES },
  "05_prompt_practice-2": { ...PROMPT, title: "İyi İstem Reçetesi: Rol + Bağlam + Format", cues: EMPTY_CUES },
  "05_prompt_practice-3": { ...PROMPT, title: "Araştırma & Özet: Kaynakla Çalış", cues: EMPTY_CUES },
  "05_prompt_practice-4": { ...PROMPT, title: "Yazı & Çeviri: Ton Ayarı", cues: EMPTY_CUES },
  "05_prompt_practice-5": { ...PROMPT, title: "Tablo & Plan: Günlük Hayat Kısayolları", cues: EMPTY_CUES },
  "05_prompt_practice-6": { ...PROMPT, title: "10 Promptluk Cep Seti + Sınav Köprüsü", cues: EMPTY_CUES },
};

function asSlide(
  lessonKey: AcademyCinemaCueSlideLessonKey,
  draft: LessonDraft,
  cue: OverlayDraft,
): AcademyCinemaCueSlide {
  return {
    lessonKey,
    theme: draft.theme,
    courseLabel: draft.courseLabel,
    lessonTitle: draft.title,
    instructor: draft.instructor,
    ...cue,
  };
}

export function academyCinemaCueIndexFromId(cueId: string): number | null {
  const match = /^cue-0*([0-9]+)$/iu.exec(cueId.trim());
  if (!match) {
    return null;
  }
  const index = Number(match[1]);
  return Number.isInteger(index) && index > 0 ? index : null;
}

export function academyCinemaSlideForCue(
  lessonKey: string,
  cueId: string,
): AcademyCinemaCueSlide | null {
  const cueIndex = academyCinemaCueIndexFromId(cueId);
  if (cueIndex == null) {
    return null;
  }
  return loadAcademyCinemaCueSlides(lessonKey).find((slide) => slide.cueIndex === cueIndex) ?? null;
}

export function loadAcademyCinemaCueSlides(lessonKey: string): readonly AcademyCinemaCueSlide[] {
  const key = lessonKey.trim() as AcademyCinemaCueSlideLessonKey;
  const draft = LESSONS[key];
  if (!draft) {
    return [];
  }
  return draft.cues.map((cue) => asSlide(key, draft, cue));
}

export function listAcademyCinemaCueSlides(): readonly AcademyCinemaCueSlide[] {
  return ACADEMY_CINEMA_CUE_SLIDE_LESSON_KEYS.flatMap((lessonKey) => loadAcademyCinemaCueSlides(lessonKey));
}

export function academyCinemaCueSlideFileName(slide: Pick<AcademyCinemaCueSlide, "lessonKey" | "cueIndex">): string {
  return `${slide.lessonKey}-cue-${slide.cueIndex}.jpg`;
}

export function academyCinemaCueSlidePublicPathFromSlide(
  slide: Pick<AcademyCinemaCueSlide, "lessonKey" | "cueIndex">,
): string {
  return `/academy/cinema/${academyCinemaCueSlideFileName(slide)}`;
}
