import type { AcademyLessonVisualCopy } from "@/lib/academy/lesson-media";

function visual(
  diagramKey: string,
  diagramTitle: string,
  diagramCaption: string,
  videoTitle: string,
  videoCaption: string,
  durationSec: 5 | 6 | 7 | 8,
): AcademyLessonVisualCopy {
  return { diagramKey, diagramTitle, diagramCaption, videoTitle, videoCaption, durationSec };
}

export const ACADEMY_GROWTH_LESSON_VISUALS: Record<string, AcademyLessonVisualCopy> = {
  "fullstack-temel-1": visual("fs-http-request-response", "DNS ve HTTP", "Tabela, kapı, fiş.", "status", "503’te yeşil yok.", 6),
  "fullstack-temel-2": visual("fs-js-vars-functions", "İskelet ve ızgara", "Anlam + Flex/Grid.", "wrap", "Div ormanı yok.", 7),
  "fullstack-temel-3": visual("fs-dom-honest-feedback", "JS ve DOM", "Yuva ve textContent.", "null", "innerHTML yok.", 6),
  "fullstack-temel-4": visual("fs-fetch-error-reflect", "fetch kapısı", "res.ok sonra şema.", "await", "map’siz dur.", 7),
  "fullstack-temel-5": visual("fs-ts-compile-gate", "TS sözleşmesi", "interface + unknown.", "tsc", "any yok.", 5),
  "fullstack-temel-6": visual("fs-typed-client-lab", "Form ve liste", "doğrula → fetch → çiz", "disabled", "boş POST yok.", 8),
  "fullstack-orta-1": visual("fs-react-props-contract", "Bileşen ve props", "Oda, poşet, JSX.", "salt okunur", "Poşet yırtılmaz.", 6),
  "fullstack-orta-2": visual("fs-useeffect-race-cleanup", "Durum ve etki", "Pano, nöbet, iptal.", "deps", "Sonsuz setState yok.", 7),
  "fullstack-orta-3": visual("fs-express-middleware-order", "Express sırası", "json, doğrula, işleyici.", "400", "Şemasız 201 yok.", 6),
  "fullstack-orta-4": visual("fs-postgres-param-query", "Prisma defteri", "where id bağlanır.", "parametre", "SQL + id yok.", 8),
  "fullstack-orta-5": visual("fs-jwt-bearer-gate", "JWT kapısı", "Bearer, verify, 401.", "imza", "decode yetmez.", 7),
  "fullstack-orta-6": visual("fs-cart-api-capstone", "Görev teslimi", "form, JWT, Prisma, UI.", "dört kapı", "Sahte yeşil yok.", 7),
  "fullstack-ileri-1": visual("fs-rsc-server-action", "RSC ve eylem", "sunucu, vitrin, kapı.", "use server", "Sır vitrine inmez.", 6),
  "fullstack-ileri-2": visual("fs-micro-event-bus", "Olay fişi", "yayın, kuyruk, devre.", "tip", "Bilinmeyen durur.", 7),
  "fullstack-ileri-3": visual("fs-redis-rate-limit", "Raf ve turnike", "kaçırma, 429.", "PONG", "200 boş yok.", 6),
  "fullstack-ileri-4": visual("fs-docker-compose-health", "Kutu planı", "web, redis, sağlık.", "health", "URL uydurma yok.", 7),
  "fullstack-ileri-5": visual("fs-github-actions-cicd", "CI/CD gişesi", "test, needs, yayın.", "needs", "Kırmızı kamyon yok.", 6),
  "fullstack-ileri-6": visual("fs-docker-redis-capstone", "Mini fabrika", "sku, PONG, 429, yayın.", "beş kapı", "Sahte yeşil yok.", 8),
  "security-temel-1": visual("threat-risk", "CIA ve tehdit", "Varlık, tehdit, risk.", "üçlü", "Boş kayıt yok.", 6),
  "security-temel-2": visual("sec-tcpip-osi-ports", "Katman ve port", "protokol, kapı, izin.", "port", "Liste yoksa düşer.", 6),
  "security-temel-3": visual("sec-owasp-top10", "OWASP kapısı", "sınıf, öncelik, kapat.", "parametre", "Ham birleştirme yok.", 6),
  "security-temel-4": visual("sec-auth-session", "Kimlik fişi", "hash, oturum, MFA.", "hash", "Düz metin yok.", 7),
  "security-temel-5": visual("do-dns-port-firewall", "Duvar ve izin", "port, deny, RoE.", "deny", "İzinsiz test yok.", 6),
  "security-temel-6": visual("sec-sqli-secure", "Kapatma gişesi", "tespit, parametre, doğrula.", "dört kapı", "Sahte yeşil yok.", 7),
  "security-orta-1": visual("sec-osint-passive", "Keşif ve OSINT", "kamu, kapsam, RoE.", "pasif", "İzinsiz keşif yok.", 6),
  "security-orta-2": visual("sec-active-enum-lab", "Lab envanteri", "RoE, lab hedef, kapı.", "lab", "Lab dışı düşer.", 7),
  "security-orta-3": visual("sec-idor-access", "IDOR ve SSRF", "sahip, yetki, konak.", "nesne", "Yabancı id durur.", 6),
  "security-orta-4": visual("sec-auth-session", "OAuth2 ve JWT", "imza, alg, süre.", "imza", "Fotokopi yok.", 7),
  "security-orta-5": visual("sec-re-static", "SAST gişesi", "kaynak, sır, fiş.", "statik", "Sahipsiz yeşil yok.", 6),
  "security-orta-6": visual("sec-web-report-lab", "Harita ve kapat", "RoE, sahip, jeton, SAST.", "dört kapı", "Sahte yeşil yok.", 8),
  "security-ileri-1": visual("sec-re-static", "DevSecOps damga", "SAST, DAST, SCA.", "üç damga", "Kırmızıda kamyon yok.", 6),
  "security-ileri-2": visual("sec-auth-session", "IAM ve KMS", "rol, eylem, anahtar.", "en az yetki", "Joker * yok.", 7),
  "security-ileri-3": visual("sec-blue-ioc", "IR torbası", "hash, imza, zincir.", "ekle", "Silme durur.", 6),
  "security-ileri-4": visual("sec-priv-esc-detect", "SIEM ve SOC", "kaynak, imza, taban.", "anomali", "Tabansız av yok.", 7),
  "security-ileri-5": visual("sec-lateral-segment", "Sıfır Güven", "kimlik, cihaz, segment.", "üçlü", "Konum güven değil.", 6),
  "security-ileri-6": visual("sec-sim-capstone-lab", "Beş kapı", "damga, fiş, torba, av, üçlü.", "beş kapı", "Sahte yeşil yok.", 8),
  "ai-temel-1": visual("ai-llm-window", "Pencere", "Token tavanı.", "token", "Sessiz özet yok.", 6),
  "ai-temel-2": visual("ai-prompt-layers", "Tarif katmanı", "sistem / kullanıcı / biçim", "üç kutu", "Yığma yasak.", 7),
  "ai-temel-3": visual("ai-json-schema", "JSON kapısı", "Şema parse.", "JSON mod", "Neredeyse yetmez.", 5),
  "ai-temel-4": visual("ai-few-shot", "Few-shot", "Sabit örnek.", "kabul", "Beğeni tur değil.", 6),
  "ai-temel-5": visual("ai-secret-pii", "Sır kapısı", "PII tarife girmez.", "FAIL", "Üretim kapanır.", 7),
  "ai-temel-6": visual("ai-prompt-lab", "Tarif lab", "doğrula → üret", "parse", "Çökme yok.", 8),
  "ai-temel-7": visual("ds-question-contract", "Soru sözleşmesi", "birim + payda", "FAIL", "Tablo yoksa sus.", 6),
  "ai-temel-8": visual("ds-clean-missing", "Temizlik", "eksik ≠ sıfır", "dtype", "Kör fillna yok.", 6),
  "ai-temel-9": visual("ds-eda-groupby", "Dürüst özet", "payda yazılı", "n", "Süs pasta yok.", 7),
  "ai-temel-10": visual("ai-rag-split", "RAG ayırımı", "ara, sonra üret", "retriever", "Boşsa sus.", 6),
  "ai-temel-11": visual("ai-grounded-answer", "Kanıt kapısı", "alıntı yoksa dur", "eşik", "Uydurma yok.", 8),
  "ai-temel-12": visual("ai-pdf-assistant", "Kapanış asistanı", "PDF + RAG + UI", "alıntı", "Dört halka.", 5),
  "ux-temel-1": visual("ux-vs-ui", "UX / UI sınırı", "yol ve yüz", "görev", "Beğeni kabul değil.", 6),
  "ux-temel-2": visual("ux-research", "Araştırma", "soru → bulgu", "görüşme", "İç zevk yasak.", 6),
  "ux-temel-3": visual("ux-persona-journey", "Yolculuk", "yüz ve acı", "persona", "Masal yok.", 7),
  "ux-temel-4": visual("ux-information-architecture", "Bilgi mimarisi", "etiket ve grup", "IA", "Jargon yok.", 6),
  "ux-temel-5": visual("ux-wireframe", "Tel çerçeve", "iskelet öncelik", "gri kutu", "Palet yok.", 7),
  "ux-temel-6": visual("ux-figma-basics", "Figma temel", "frame / layout", "component", "Kopya borç.", 6),
  "ux-temel-7": visual("ux-wireframe-figma-lab", "Lab zinciri", "bulgu → Figma", "dört halka", "Kopuk yok.", 8),
  "ux-temel-8": visual("ux-visual-hierarchy", "Hiyerarşi", "odak ve ızgara", "8px", "Tek birincil.", 6),
  "ux-temel-9": visual("ux-design-tokens", "Jeton", "renk boşluk tipo", "token", "Serbest hex yok.", 6),
  "ux-temel-10": visual("ux-prototype", "Prototip", "tıklanır akış", "görev", "Slayt yetmez.", 6),
  "ux-temel-11": visual("ux-wcag", "Erişim barajı", "kontrast odak etiket", "a11y", "İkon-only yok.", 7),
  "ux-temel-12": visual("ux-handoff", "El teslimi", "ölçü ve not", "dev", "Link yetmez.", 6),
  "excel-masterclass-1": visual("ex-excel-formulas", "Hücre ve tartı", "adres, değer, n.", "SUM", "Boş ortalama yok.", 7),
  "excel-masterclass-2": visual("ex-model-relationships", "Arama kapısı", "tam eşleşme.", "XLOOKUP", "Yaklaşık SKU yok.", 6),
  "excel-masterclass-3": visual("ex-pivot-table", "Özet ve dilim", "SAY / SUM.", "pivot", "Kimlik toplanmaz.", 7),
  "excel-masterclass-4": visual("ex-cleanse-lab", "Temizlik", "anahtar, ayırıcı.", "N/A", "Sıfır uydurma yok.", 8),
  "excel-masterclass-5": visual("ex-apps-script-menu", "Taslak ve imza", "parse, VBA.", "imza", "PII tarife girmez.", 7),
  "excel-masterclass-6": visual("ex-dashboard-lab", "Dört kapı", "temiz, ara, özet, yenile.", "dashboard", "Sahte yeşil yok.", 8),
  "google-ads-masterclass-1": visual("ex-excel-formulas", "Tabela ve hesap", "dönüşüm, fatura.", "hesap", "Dönüşümsüz harcama yok.", 7),
  "google-ads-masterclass-2": visual("ex-model-relationships", "Eşleme kapısı", "geniş, sıralı, tam.", "eşleme", "Dönüşümsüz geniş yok.", 6),
  "google-ads-masterclass-3": visual("ex-pivot-table", "Ağ ayrımı", "arama / görüntülü.", "ağ", "Bakış satış değil.", 7),
  "google-ads-masterclass-4": visual("ex-cleanse-lab", "GTM fişi", "teşekkür, sipariş id.", "etiket", "Çift sayım yok.", 8),
  "google-ads-masterclass-5": visual("ex-apps-script-menu", "Kalite puanı", "başlık, QS 5+.", "QS", "Düşük puan ölçek yok.", 7),
  "google-ads-masterclass-6": visual("ex-dashboard-lab", "Dört kapı", "ölçü, eşleme, ağ, QS.", "kampanya", "Sahte yeşil yok.", 8),
  "meta-ads-masterclass-1": visual("ex-excel-formulas", "Vitrin ve Suite", "sayfa, piksel, fatura.", "hesap", "Pikselsiz harcama yok.", 7),
  "meta-ads-masterclass-2": visual("ex-model-relationships", "Kitle kapısı", "purchase kaynak.", "lookalike", "Beğeni benzeri yok.", 6),
  "meta-ads-masterclass-3": visual("ex-pivot-table", "Format ve test", "Reels, görsel, atlıkarınca.", "kreatif", "Beğeni kazanan değil.", 7),
  "meta-ads-masterclass-4": visual("ex-cleanse-lab", "Piksel ve CAPI", "event_id, değer.", "ölçü", "Çift sayım yok.", 8),
  "meta-ads-masterclass-5": visual("ex-apps-script-menu", "CBO ve ROAS", "öğrenme %20.", "bütçe", "Kör ROAS yok.", 7),
  "meta-ads-masterclass-6": visual("ex-dashboard-lab", "Dört kapı", "ölçü, kitle, öğrenme, değer.", "huni", "Sahte yeşil yok.", 8),
  "eticaret-masterclass-1": visual("ex-excel-formulas", "Tezgâh ve komisyon", "vergi, kargo, stok.", "tezgâh", "Stoksuz satış yok.", 7),
  "eticaret-masterclass-2": visual("ex-model-relationships", "Mağaza kapısı", "unvan, IBAN.", "mağaza", "Sözlü kurye yok.", 6),
  "eticaret-masterclass-3": visual("ex-pivot-table", "Liste ve barkod", "başlık / GTIN.", "ilan", "Çalıntı görsel yok.", 7),
  "eticaret-masterclass-4": visual("ex-cleanse-lab", "Stok senkron", "merkez, rezerv.", "sayaç", "Oversell yok.", 8),
  "eticaret-masterclass-5": visual("ex-apps-script-menu", "Kargo ve iade", "takip, SLA.", "fiş", "Fişsiz teslim yok.", 7),
  "eticaret-masterclass-6": visual("ex-dashboard-lab", "Dört kapı", "mağaza, liste, stok, kargo.", "vitrin", "Sahte yeşil yok.", 8),
  "canva-masterclass-1": visual("ex-excel-formulas", "Kalıp ve kit", "logo, hex, tipo.", "kit", "Boş palet yok.", 7),
  "canva-masterclass-2": visual("ex-model-relationships", "Kare ve boy", "1:1 / 9:16.", "kare", "Üç CTA yok.", 6),
  "canva-masterclass-3": visual("ex-pivot-table", "Izgara ve pay", "punto / bleed.", "kâğıt", "Taşma yok.", 7),
  "canva-masterclass-4": visual("ex-cleanse-lab", "Magic kapısı", "taslak, lisans.", "AI", "PII tarife girmez.", 8),
  "canva-masterclass-5": visual("ex-apps-script-menu", "RGB ve CMYK", "dpi, pay.", "teslim", "RGB baskı yok.", 7),
  "canva-masterclass-6": visual("ex-dashboard-lab", "Dört kapı", "kit, boy, lisans, profil.", "paket", "Sahte yeşil yok.", 8),
  "linkedin-masterclass-1": visual("ex-excel-formulas", "Kartvizit", "foto, başlık, kanıt.", "All-Star", "Slogan yok.", 7),
  "linkedin-masterclass-2": visual("ex-model-relationships", "Kanca kapısı", "kanıt, etiket.", "gönderi", "Beğeni avı yok.", 6),
  "linkedin-masterclass-3": visual("ex-pivot-table", "ICP süzgeç", "unvan / sektör.", "Navigator", "Yığın hedef yok.", 7),
  "linkedin-masterclass-4": visual("ex-cleanse-lab", "Outreach", "bağlam, soru.", "InMail", "Kopya duvar yok.", 8),
  "linkedin-masterclass-5": visual("ex-apps-script-menu", "Niş ve kanıt", "tek cümle.", "konum", "Kanıtsız unvan yok.", 7),
  "linkedin-masterclass-6": visual("ex-dashboard-lab", "Dört kapı", "profil, içerik, ICP, yazı.", "pipeline", "Sahte yeşil yok.", 8),
};
