import type { AcademyLessonVisualCopy } from "@/lib/academy/lesson-media";

function visual(
  diagramKey: string,
  diagramTitle: string,
  diagramCaption: string,
  videoTitle: string,
  videoCaption: string,
  durationSec: 5 | 6 | 7 | 8,
): AcademyLessonVisualCopy {
  return { diagramKey, diagramTitle, diagramCaption, videoTitle, videoCaption, durationSec };
}

export const ACADEMY_GROWTH_LESSON_VISUALS: Record<string, AcademyLessonVisualCopy> = {
  "python-temel-7": visual("py-select-filter", "Liste ve indeks", "Sıra sıfırdan başlar.", "sepet[-1]", "Son raf -1’dir.", 6),
  "python-temel-8": visual("py-group-merge", "Sözlük", "Anahtar etikettir.", ".get", "Yokluk çökmez.", 7),
  "python-temel-9": visual("py-file-auto", "Dosya yolu", "Kaynak ve çıktı ayrı.", "pathlib", "Atomik yazım.", 6),
  "python-temel-10": visual("py-pandas-frame", "Tablo sözleşmesi", "Cins yazılı durur.", "dtypes", "Kuruş int64.", 6),
  "python-temel-11": visual("py-sql-bridge", "SQL köprüsü", "Değer parametredir.", "$1", "Birleştirme yasak.", 5),
  "python-temel-12": visual("py-pipeline", "Kapanış hattı", "oku → doğrula → yaz", "main", "Yeniden koşar.", 5),
  "fullstack-temel-1": visual("fs-http-request-response", "HTTP çifti", "İstek ve yanıt birlikte.", "status", "Fiş okunur.", 6),
  "fullstack-temel-2": visual("fs-js-vars-functions", "JS kutu", "Etiket ve tip.", "Number", "Metin çarpılmaz.", 7),
  "fullstack-temel-3": visual("fs-ts-compile-gate", "TS kapısı", "tsc mühürler.", "interface", "any yok.", 5),
  "fullstack-temel-4": visual("fs-dom-honest-feedback", "DOM geri bildirim", "Tek cümle.", "disabled", "Çift tıklama yutulur.", 6),
  "fullstack-temel-5": visual("fs-fetch-error-reflect", "fetch kapısı", "res.ok okunur.", "503", "Yeşil yasak.", 7),
  "fullstack-temel-6": visual("fs-typed-client-lab", "İstemci lab", "Tip + DOM + fetch", "qty", "Boş istek yok.", 8),
  "fullstack-temel-7": visual("fs-react-props-contract", "React props", "Tek yönlü veri.", "Props", "Çocuk mutasyon yok.", 6),
  "fullstack-temel-8": visual("fs-usereducer-ssot-phase", "Faz makinesi", "Tek gerçek kaynak.", "idle", "Bayrak çelişmez.", 8),
  "fullstack-temel-9": visual("fs-routing-page-contract", "App Router", "Adres sayfadır.", "Link", "Boş dürüst.", 8),
  "fullstack-temel-10": visual("fs-express-middleware-order", "Express sıra", "json → validate", "Zod", "Şemasız 200 yok.", 6),
  "fullstack-temel-11": visual("fs-postgres-param-query", "Postgres $1", "Parametre bağlanır.", "CHECK", "Enjeksiyon yok.", 8),
  "fullstack-temel-12": visual("fs-cart-api-capstone", "Sepet teslimi", "Zod, jeton, tx, test", "kapanış", "Dört kapı.", 7),
  "ai-temel-1": visual("ai-llm-window", "Pencere", "Token tavanı.", "token", "Sessiz özet yok.", 6),
  "ai-temel-2": visual("ai-prompt-layers", "Tarif katmanı", "sistem / kullanıcı / biçim", "üç kutu", "Yığma yasak.", 7),
  "ai-temel-3": visual("ai-json-schema", "JSON kapısı", "Şema parse.", "JSON mod", "Neredeyse yetmez.", 5),
  "ai-temel-4": visual("ai-few-shot", "Few-shot", "Sabit örnek.", "kabul", "Beğeni tur değil.", 6),
  "ai-temel-5": visual("ai-secret-pii", "Sır kapısı", "PII tarife girmez.", "FAIL", "Üretim kapanır.", 7),
  "ai-temel-6": visual("ai-prompt-lab", "Tarif lab", "doğrula → üret", "parse", "Çökme yok.", 8),
  "ai-temel-7": visual("ds-question-contract", "Soru sözleşmesi", "birim + payda", "FAIL", "Tablo yoksa sus.", 6),
  "ai-temel-8": visual("ds-clean-missing", "Temizlik", "eksik ≠ sıfır", "dtype", "Kör fillna yok.", 6),
  "ai-temel-9": visual("ds-eda-groupby", "Dürüst özet", "payda yazılı", "n", "Süs pasta yok.", 7),
  "ai-temel-10": visual("ai-rag-split", "RAG ayırımı", "ara, sonra üret", "retriever", "Boşsa sus.", 6),
  "ai-temel-11": visual("ai-grounded-answer", "Kanıt kapısı", "alıntı yoksa dur", "eşik", "Uydurma yok.", 8),
  "ai-temel-12": visual("ai-pdf-assistant", "Kapanış asistanı", "PDF + RAG + UI", "alıntı", "Dört halka.", 5),
  "ux-temel-1": visual("ux-vs-ui", "UX / UI sınırı", "yol ve yüz", "görev", "Beğeni kabul değil.", 6),
  "ux-temel-2": visual("ux-research", "Araştırma", "soru → bulgu", "görüşme", "İç zevk yasak.", 6),
  "ux-temel-3": visual("ux-persona-journey", "Yolculuk", "yüz ve acı", "persona", "Masal yok.", 7),
  "ux-temel-4": visual("ux-information-architecture", "Bilgi mimarisi", "etiket ve grup", "IA", "Jargon yok.", 6),
  "ux-temel-5": visual("ux-wireframe", "Tel çerçeve", "iskelet öncelik", "gri kutu", "Palet yok.", 7),
  "ux-temel-6": visual("ux-figma-basics", "Figma temel", "frame / layout", "component", "Kopya borç.", 6),
  "ux-temel-7": visual("ux-wireframe-figma-lab", "Lab zinciri", "bulgu → Figma", "dört halka", "Kopuk yok.", 8),
  "ux-temel-8": visual("ux-visual-hierarchy", "Hiyerarşi", "odak ve ızgara", "8px", "Tek birincil.", 6),
  "ux-temel-9": visual("ux-design-tokens", "Jeton", "renk boşluk tipo", "token", "Serbest hex yok.", 6),
  "ux-temel-10": visual("ux-prototype", "Prototip", "tıklanır akış", "görev", "Slayt yetmez.", 6),
  "ux-temel-11": visual("ux-wcag", "Erişim barajı", "kontrast odak etiket", "a11y", "İkon-only yok.", 7),
  "ux-temel-12": visual("ux-handoff", "El teslimi", "ölçü ve not", "dev", "Link yetmez.", 6),
};
