/**
 * Kanonik terim — İngilizce (Türkçe parantez). Client-safe.
 */

export const ACADEMY_TERM = {
  ISO_4217: "ISO 4217 (Para Birimi Kodu)",
  INTERLOCKING: "Interlocking (Anklaşman)",
  FAIL_SAFE: "Fail-safe (Hata Anında Emniyet)",
  TRACK_CIRCUIT: "Track circuit (Ray Devresi)",
  BRIEF: "Brief (İş Brifi)",
  FAIL_CLOSED: "Fail-closed (Hata Anında Kapalı)",
  RELEASE: "RELEASE (Hak Devri)",
  UNSET: "UNSET (Henüz Tanımlanmamış)",
  DELIVERY: "DELIVERY (Teslim Kaydı)",
  SHA_256: "SHA-256 (İçerik Özeti)",
  BIM: "BIM (Yapı Bilgi Modellemesi)",
  EIR: "EIR (Bilgi İstek Belgesi)",
  BEP: "BEP (BIM Uygulama Planı)",
  CDE: "CDE (Ortak Veri Ortamı)",
  DTYPE: "dType (Veri Tipi)",
  KPI: "KPI (Anahtar Performans Göstergesi)",
  GREENWASHING: "Greenwashing (Yeşil Boyama)",
  PO: "Product Owner (Ürün Sahibi)",
  INCREMENT: "Increment (Artırım)",
  SM: "Scrum Master (Scrum Ustası)",
  DOD: "DoD (Kabul Kriteri)",
  DONE: "Done (Bitti Tanımı)",
  DEFINITION_OF_DONE: "Definition of Done (Bitti Tanımı)",
  INSPECT: "Inspect (Denetle)",
  ADAPT: "Adapt (Uyarla)",
  EMPIRICISM: "Empiricism (Görgül Yöntem)",
  CLICK_OPS: "Click-ops (Tıklama Operasyonu)",
  ROLLBACK: "Rollback (Geri Alma)",
  HOTFIX: "Hotfix (Acil Yama)",
  CANARY: "Canary (Kanarya Sürümü)",
  QUIET_LUXURY: "Quiet Luxury (Sakin Lüks)",
  WCAG: "WCAG (Web İçeriği Erişilebilirlik Kılavuzu)",
  TOKEN: "Design token (Tasarım Jetonu)",
  AIS: "AIS (Hesap Bilgisi Hizmeti)",
  PIS: "PIS (Ödeme Başlatma Hizmeti)",
  CONSENT: "Consent (Açık Rıza)",
  IBAN: "IBAN (Uluslararası Banka Hesap Numarası)",
  SCA: "SCA (Güçlü Müşteri Kimliği)",
  CI: "CI (Sürekli Entegrasyon)",
  ARTIFACT: "Artifact (Yapı Paketi)",
  SBOM: "SBOM (Yazılım Malzeme Listesi)",
  CD: "CD (Sürekli Teslim)",
  SLI: "SLI (Hizmet Seviye Göstergesi)",
  SLO: "SLO (Hizmet Seviye Hedefi)",
  HASH: "Hash (Özet Değeri)",
  PSD2: "PSD2 (Ödeme Hizmetleri Direktifi)",
  OTP: "OTP (Tek Kullanımlık Parola)",
  TTL: "TTL (Yaşam Süresi)",
  PROMPT: "Prompt (Üretim Tarifi)",
  ASPECT: "Aspect (Sinyal Aspekti)",
  RAG: "Artırılmış Geri Çapraz Sorgulama (RAG)",
  BLEU: "BLEU (Metin Benzerlik Puanı)",
  ESG: "ESG (Çevre Sosyal Yönetişim)",
  LOD: "LOD (Detay Seviyesi)",
  IFC: "IFC (Endüstri Temel Sınıfları)",
  DRIFT: "Drift (Sapma)",
  API: "API (Uygulama Programlama Arayüzü)",
  REST: "REST (Temsili Durum Transferi)",
  FIGMA: "Figma (Arayüz Tasarım Aracı)",
  PENTEST: "Pentest (Sızma Testi)",
  PHISHING: "Phishing (Kimlik Avı)",
  MFA: "MFA (Çok Faktörlü Kimlik)",
  NFR: "NFR (İşlevsel Olmayan Gereksinim)",
  SOW: "SOW (İş Tanımı)",
  AGENT: "AI Agent (Yapay Zekâ Ajanı)",
  ROAS: "Reklam Harcamasının Geri Dönüşü (ROAS)",
  CPA: "Edinme Başına Maliyet (CPA)",
  CPC: "Tıklama Başına Maliyet (CPC)",
  CTR: "Tıklama Oranı (CTR)",
  CVR: "Dönüşüm Oranı (CVR)",
  CAC: "Müşteri Edinim Maliyeti (CAC)",
  SEO: "Arama Motoru Optimizasyonu (SEO)",
  SERP: "Arama Motoru Sonuç Sayfası (SERP)",
  META_PIXEL: "Meta Piksel (Meta Pixel)",
  META_ADS: "Meta Reklamları (Meta Ads)",
  GOOGLE_ADS: "Google Reklamları (Google Ads)",
  CTA: "eyleme çağrı (CTA)",
  AVD: "ortalama izlenme süresi (AVD)",
  SHORTS: "Kısa Dikey Video (Shorts)",
  REELS: "Kısa Dikey Video (Reels)",
  THUMBNAIL: "küçük resim (thumbnail)",
  B_ROLL: "destek görüntüsü (B-roll)",
  DROPSHIPPING: "Doğrudan Sevkiyat / Stoksuz Satış (Dropshipping)",
  FULFILLMENT: "Sipariş Karşılama ve Depo Operasyonu (Fulfillment)",
  CAPSTONE: "Kapanış Çalışması (Capstone)",
  NLP: "Nöro-Dilsel Programlama (NLP)",
  SBI: "Durum-Davranış-Etki Geri Bildirimi (SBI)",
  EQ: "Duygusal Zekâ (EQ)",
  EISENHOWER: "Eisenhower Öncelik Matrisi (Eisenhower)",
  TIMEBOX: "zaman kutusu (timeboxing)",
  PERSONAL_OS: "Kişisel İşletim Sistemi (OS)",
  DAX: "Veri Çözümleme İfadeleri (DAX)",
  ETL: "Veri Dönüştürme ve Yükleme İşlemi (ETL)",
  RLS: "Satır Düzeyi Güvenlik (RLS)",
  BI: "İş Zekâsı (BI)",
  PIVOT: "Özet Tablo (Pivot)",
  APPS_SCRIPT: "Uygulama Senaryosu (Apps Script)",
  POWER_QUERY: "Power Query (Veri Dönüştürme ve Yükleme İşlemi)",
  POWER_BI: "Power BI (İş Zekâsı)",
  ARRAYFORMULA: "dizi formülü (ARRAYFORMULA)",
  SHEETS_QUERY: "sorgulama işlevi (QUERY)",
  PII: "Kişisel Gizli Veriler (PII)",
  SSOT: "Tek Gerçek Kaynak (SSOT)",
  PDP: "Ürün Detay Sayfası (PDP)",
  COGS: "Satılan Malın Maliyeti (COGS)",
  SLA: "Hizmet Seviyesi Anlaşması (SLA)",
  AOV: "Ortalama Sipariş Değeri (AOV)",
  QA: "Kalite Güvencesi (QA)",
  E2E: "Uçtan Uca Test (E2E)",
  K6: "Performans Test Aracı (k6)",
  P95: "yüzde doksan beş (p95)",
} as const;

export type AcademyTermKey = keyof typeof ACADEMY_TERM;

export const ACADEMY_MENTOR_BRIDGES = [
  /** Pedagoji doktrini — re-frame / mikro-duraksama / kültürel analoji (bkz. pedagogy-doctrine.ts) */
  "Başka bir deyişle...",
  "Buraya dikkat...",
  "İşte işin düğümlendiği, kritik nokta tam da burası.",
  "Kırılma anı tam olarak bu adımda yaşanıyor.",
  "Saha tecrübesiyle söyleyeyim: Buradaki küçük bir detay tüm sonucu değiştirir.",
  "Bunu günlük hayattan bir örnekle ele alırsak...",
  "Şimdi bu kısmı bir kez daha farklı bir örnekle oturtalım...",
  /** Pedagoji doktrini — doğal onaylama (bkz. pedagogy-doctrine.ts); «Harika!» / «Süper!» yasak */
  "Evet, yani...",
  "Doğru dedin.",
  "Aynen öyle.",
  "Tam olarak bu işte.",
  "Çok doğru bir noktaya değindin.",
] as const;
