export const ACADEMY_SEN = {
  catalog: {
    eyebrow: "Akademi",
    title: "Mühürlü Kariyer",
    description:
      "Eğitimi incele, müfredatı gör veya doğrudan 70+ mühür sınavına gir. Her eğitimin tek bir eğitmeni vardır; Moderatör Koray stüdyoyu açıp kapatır. Dersler ödeme sonrası açılır. Ustalık belgesi yalnız sınav barajından (≥70) sonra basılır.",
    certificatesCta: "Sertifikalar",
    live: (count: number) =>
      count > 0 ? "Mühürlü Kariyer — popüler yetkinlik yolları" : "",
    unbound: "Liste henüz yüklenemedi.",
    empty: "Yayında eğitim yok.",
    cardCtaInspect: "İncele",
    cardCtaOpen: "Eğitimi Gör",
    /** Vitrin kartı — satın alma yokken birincil eylem. */
    cardCtaBuy: "Satın Al",
    /** Vitrin kartı — DURUM A fiyatlı birincil eylem. */
    cardCtaBuyPriced: (priceLabel: string) => `Satın Al — ${priceLabel}`,
    /** Süzgeç chip’i ile aynı etiket — Temel Seviye / Orta Seviye / İleri Seviye. */
    badgeLevel: (level: string) => {
      if (level === "Temel") return "Temel Seviye";
      if (level === "Orta") return "Orta Seviye";
      if (level === "İleri") return "İleri Seviye";
      if (level === "Masterclass") return "Masterclass";
      return level;
    },
    /**
     * Kart kicker — Quiet Luxury seviye indikatörü.
     * Seri modülünde seviye sözcüğü (Temel / Orta / İleri) önde durur; kod ikinci.
     */
    cardLevelContext: (level?: string | null, moduleCode?: string | null) => {
      const label = level?.trim() ?? "";
      const code = moduleCode?.trim() ?? "";
      if (label && code) return `${label} · ${code}`;
      return label || code;
    },
    badgeClosed: "Kayıt kapalı",
    priceMissing: "Fiyat yok",
    /** Quiet Luxury Piyasa Talep Skoru — 100 üzerinden Match Score mührü. */
    marketDemandScoreTitle: "Piyasa Talep Skoru",
    marketDemandScore: (score: number) => `✦ ${score.toFixed(1)}`,
    marketRank: (rank: number) => `Piyasa Sırası: #${rank}`,
    /** Kart meta — eğitmen + bölüm; tekrar eden lab süsü yok. Baraj kurs/sınav sayfasında. */
    cardMeta: (lessons: number, instructorName?: string) =>
      [instructorName ? `Eğitmen: ${instructorName}` : null, `${lessons} Bölüm`]
        .filter((part) => Boolean(part && part.length > 0))
        .join(" · "),
    infoBand: (count: number) =>
      count > 0
        ? "Onaylı Eğitimler · Piyasa değerine göre dinamik fiyat · Tekil Masterclass veya çoklu modül · Eğitim veya Doğrudan Sınav/Vize · Baraj 70+ · Mühürlü Ustalık Belgesi"
        : "",
    boardTitle: "Eğitim kataloğu",
    tabCatalog: "Tüm Katalog",
    tabOwned: "Aldığım Eğitimler",
    tabFavorites: "Favorilerim",
    tabLabel: "Katalog sekmeleri",
    filteredEmpty: "Kriterlere uygun eğitim bulunamadı",
    filteredEmptyHint: "Arama, dikey veya seviye süzgecini gevşetmek sonucu açabilir.",
    ownedEmpty: "Henüz satın alınmış eğitim yok.",
    favoritesEmpty: "Henüz favori eğitim yok.",
    clearFiltersCta: "Süzgeçleri temizle",
    favoriteAdd: "Favorilere ekle",
    favoriteRemove: "Favorilerden çıkar",
    statusContinue: "Devam Et",
    statusCompleted: "Tamamlandı",
  },
  filter: {
    searchPlaceholder: "Eğitimlerde ara...",
    categoryLabel: "Kategori",
    groupLabel: "Ana Grup",
    verticalLabel: "Alt Kategori",
    levelLabel: "Seviye",
    sortLabel: "Sıralama",
    viewLabel: "Görünüm",
    viewGrid: "Izgara",
    viewList: "Liste",
  },

  course: {
    eyebrow: "Eğitim · Akademi",
    catalogCta: "Akademi",
    noPrice: "Fiyat henüz yok — kayıt kapalı",
    notPurchasable: "Bu eğitim şu an kayıt almıyor.",
    /** Antre hero — DURUM A (satın alınmadı). */
    heroBuyCta: (priceLabel: string) => `Eğitimi Satın Al — ${priceLabel}`,
    heroBuyCtaIdle: "Satın Al",
    /** Antre / vitrin fiyat yerine — DURUM B (satın alındı). */
    accessOpen: "Erişim Açık",
    purchasedBadge: "Satın Alındı",
    loginLead: "Eğitimi başlatmak için",
    loginCta: "giriş yap",
    ownedExam: (passScore: number) =>
      `Sınav kapısı açık (≥${passScore}). Eğitim yolunda dersleri bitirebilir veya doğrudan mühür testine girebilirsin. Satın alma belge basmaz.`,
    ownedNoExam:
      "Dersler açık. İstersen öğrenmeye devam et; doğrudan sınav yolu ödeme sonrası açıktır.",
    certificateEyebrow: "Ustalık belgesi",
    certificateBody:
      "Sınav kapısı geçildi. SHA-256 içerik özeti kariyer vizesine aktarılır. Kriptografik imza değildir.",
    examEyebrow: "Müfredat sınavı",
    libraryGuarantee:
      "Satın aldığın eğitim kütüphanende 365 gün sabit kalır; müfredat veya sıralama güncellense de hakkın düşmez. Doğrudan sınav yolunda ders gövdesi açılmaz; belge yine 70+ ister.",
    purchaseEyebrow: "Yetkinlik yolu",
    purchaseBody:
      "Dersi al, müfredatı bitir, sunucu sınavında 70+ al. SHA-256 mühür ve kariyer vizesi yalnız baraj üstünde basılır. Satın alma belge basmaz.",
    pathTrainingCta: (priceLabel: string) => `Eğitimi Satın Al & Öğren (${priceLabel})`,
    pathTrainingCtaIdle: "Eğitimi Satın Al & Öğren",
    pathTrainingBody: "Ders materyalleri, kod laboratuvarı ve uygulamalı içerik.",
    pathExamCta: (priceLabel: string) => `Doğrudan Sınava Gir & Vize Al (${priceLabel})`,
    pathExamCtaIdle: "Doğrudan Sınava Gir & Vize Al",
    pathExamBody: "Eğitimsiz yol — yalnız 70+ barajlı mühür testi.",
  },
  outline: {
    eyebrow: "Müfredat özeti",
    title: "Ne öğreneceksin",
    exam: (passScore: number) =>
      `Sınav şartı: ${passScore}+ puan. Belge yalnız bu barajın üstünde basılır.`,
    visaPromise:
      "Sınav barajı üstünde SHA-256 mühür ve CareerVisaStamp kariyer vizesi damgası basılır. Satın alma belge basmaz.",
    lockedHint: "Ders gövdesi ödeme sonrası açılır.",
    empty: "Müfredat tohumu yok.",
  },
  outcomes: {
    eyebrow: "Öğrenim çıktıları",
    title: "Bu yolda ne kazanırsın",
    empty: "Çıktı sicili yok.",
  },
  settlement: {
    title: "Ödeme notu",
    steps: (lockMinutes: number) =>
      [
        {
          key: "lock",
          label: "Fiyat",
          detail: `Ödeme anındaki fiyat ${lockMinutes} dakika geçerli kalır.`,
        },
        {
          key: "settle",
          label: "Erişim",
          detail: "Ödeme iade edilmez; ders erişimi 365 gün sürer.",
        },
        {
          key: "record",
          label: "Belge",
          detail: "Dersler ödeme sonrası açılır. Ustalık belgesi bu adımda basılmaz.",
        },
      ] as const,
  },
  purchase: {
    cta: (priceLabel: string) => `Eğitimi Satın Al & Öğren (${priceLabel})`,
    ctaIdle: "Eğitimi Satın Al & Öğren",
    ctaExam: (priceLabel: string) => `Doğrudan Sınava Gir & Vize Al (${priceLabel})`,
    ctaExamIdle: "Doğrudan Sınava Gir & Vize Al",
    ctaTopUp: "Bakiye Yükle / Öde",
    closed: "Ödeme henüz bağlanmadı / pasif",
    closedBody:
      "Ödeme henüz bağlanmadı / pasif. Kart ile yükleme bağlı değil. Cüzdanında harç varsa eğitimi başlat; yoksa kayıt bekler. Sahte bakiye yazılmaz.",
    pendingCta: "Kaydediliyor…",
    locking: (lockMinutes: number) => `Fiyat onaylanıyor — ${lockMinutes} dakika geçerli.`,
    settling: "Ödeme onaylanıyor.",
    lockFail: "Fiyat onayı alınamadı.",
    buyFail: "Satın alma tamamlanamadı.",
    licenseDuration: "365_DAYS",
    licenseNote: "Lisans 365 gün. Seviye bandı eğitim kartında durur. Doğrudan sınav yolu ders gövdesi açmaz.",
  },
  exam: {
    barajHint: (passScore: number) => `Baraj ${passScore}. Satın alma sertifika basmaz.`,
    unanswered: "Tüm soruları yanıtla.",
    submit: "Sınavı gönder",
    pending: "Değerlendiriliyor…",
    failClosed: "Sınav değerlendirilemedi.",
    remaining: (mm: string, ss: string) => `Kalan Süre: ${mm}:${ss}`,
    passed: (score: number) =>
      `Baraj geçildi (${score}). Belgen ve kariyer vizen basıldı.`,
    viewCertificate: "Belgeni gör",
    careerVisa: "Kariyer vizesi",
    forensicHash: "Sicil özeti (SHA-256)",
    timedOut: "Süre doldu. Son gönderim.",
    failed: (score: number) =>
      `Barajın altında (${score}). Sertifika basılmaz; öğrenme kaydı durur, yeniden dene.`,
    retryHint: "Yeniden gönderilebilir. Belge yalnız baraj üstünde basılır.",
    locked: "Sınav kapısı ödeme sonrası açılır.",
    workTasksLocked: "Bölüm iş görevleri tamamlanmadan sınav kapısı kapalı.",
    workProofLead: "Süre altında aynı fail-closed kararı kilitle. Ezber şık belgesi basmaz.",
    workProofMissing: "İş kanıtı kilitlenmeden sınav gönderilmez.",
    startCta: (_minutes: number, _passScore: number) => "Müfredat Sınavına Başla",
    startLead: (minutes: number, passScore: number) =>
      `Bu sınav ${minutes} dakikadır ve baraj puanı ${passScore}'tir. Başla butonuna bastığında süren başlar.`,
    starting: "Sınav açılıyor…",
    startFail: "Sınav oturumu açılamadı.",
    focusLabel: "Müfredat sınavı — odak odası",
    stepOf: (current: number, total: number) => `Soru ${current} / ${total}`,
    nextQuestion: "Sonraki soru",
    prevQuestion: "Önceki soru",
    diplomaReveal: "Belgen mühürlendi",
    chamberEyebrow: "Focus Chamber",
    /** Focus Chamber — oturumu iptal; JTI tüketilmez, attempt yazılmaz. */
    abandonCta: "Sınavdan vazgeç",
    exitCta: "Çık",
    abandonLead: "Cevaplar gönderilmez. Yeniden başlayabilirsin.",
  },
  player: {
    eyebrow: (name: string) => `Stüdyo · Eğitmen ${name}`,
    instructorLead: (name: string) =>
      `Stüdyoda Moderatör Koray sunar ve ara soru sorar; ${name} anlatır.`,
    catalogCta: "Eğitime dön",
    locked: "Ödeme alınmadan ders içeriği açılmaz.",
    lockedBody: "Dersler ödeme sonrası açılır. Eğitimi kurs sayfasından başlat.",
    progress: (done: number, total: number) => `${done} / ${total} ders tamam`,
    cardProgress: (current: number, total: number) => `${current} / ${total} Bölüm`,
    nextCardCta: "Sonraki",
    completeCta: "Dersi Tamamla",
    prevLessonCta: "Önceki Ders",
    nextOrCompleteCta: "Sonraki Ders / Dersi Tamamla",
    playlistLabel: "Oynatma listesi",
    companionEyebrow: "Ders açıklaması",
    descriptionEyebrow: "Ders açıklaması",
    resourcesEyebrow: "Kaynaklar",
    discussionEyebrow: "Yorumlar",
    discussionEmpty: "Henüz yorum yok.",
    discussionPlaceholder: "Sorunu veya notunu yaz",
    discussionSubmit: "Yorumu gönder",
    discussionPending: "Gönderiliyor…",
    discussionLocked: "Yorum yazmak için bu eğitime kaydol.",
    discussionCount: (count: number) => `${count} yorum`,
    discussionFail: "Yorum kaydedilemedi.",
    cinemaEyebrow: "Ders yayını",
    cinemaTimeline: "Zaman çizelgesi",
    cinemaFullscreen: "Tam ekran",
    cinemaExitFullscreen: "Tam ekrandan çık",
    cinemaCaptions: "Altyazı",
    cinemaCaptionsOn: "Altyazı açık",
    cinemaCaptionsOff: "Altyazı kapalı",
    cinemaPreparing: "Yayın hazırlanıyor…",
    labEyebrow: "Kod laboratuvarı",
    labRun: "Çalıştır",
    labCopy: "Kopyala",
    labCopied: "Kopyalandı",
    labReset: "Sıfırla",
    labOutput: "Çıktı",
    labStdin: "Girdi",
    labStdinHint: "input() satırları, her satır bir giriş",
    labEmpty: "Bu derste çalıştırılacak kod yok.",
    labCopyFail: "Kopyalanamadı.",
    completing: "Kaydediliyor…",
    completeFail: "Ders tamamlanamadı.",
    completeLocked: "İş kanıtı olmadan ders kapanmaz.",
    examReady: "Bölüm İş Görevleri Tamamlandı. Sınav kapısı açıldı (≥70).",
    examBlocked: "Bölüm iş görevleri tamamlanmadan sınav kapısı kapalı.",
    examCta: "Sınava geç",
    alreadyDone: "Ders tamam",
    nextHint: "Sıradaki ders açık. Atlanan ders tamamlanmaz.",
    openCta: "Derse başla",
    /** Antre — yarım kalan müfredat. */
    resumeCta: "Kaldığın Yerden Devam Et",
    lessonCount: (count: number) => `${count} ders`,
    levelBadge: (level: string) => level,
    autoAdvance: "Otomatik Geçiş",
    advancing: (sec: number) => `Sıradaki derse geçiyoruz… ${sec}`,
    advanceCancel: "İptal",
    sectionDone: "Bu bölüm bitti. Sıradaki derse geçelim mi?",
    sectionDoneLast: "Bu bölüm bitti.",
    nextLessonCta: "Sıradaki Derse Geç",
    /** Katalog / kurs — yarım kalan müfredata dönüş. */
    continueEyebrow: "Eksik / Yarım kaldı",
    continueCta: "Sıradaki Derse Devam Et",
    continueStripCta: "Devam Et",
    continueDismiss: "Gizle",
    continueLead: (done: number, total: number, title: string) =>
      done === 0
        ? `${title} · henüz başlanmadı.`
        : `${title} · ${done} / ${total} ders.`,
    continueExamLead: (title: string) =>
      `${title} · müfredat bitti. Sınav kapısı açık; baraj 70+.`,
    continueExamCta: "Sınava geç",
    continueExamHint: "Sınav kapısı",
    startCta: "Derse başla",
    starting: "Yayın açılıyor…",
    pdfCta: "Ders Notunu İndir (PDF)",
    proofCardCta: "İş Kanıtı Kartı",
    curriculumPdfCta: "Müfredat Notunu İndir (PDF)",
    pdfLessonLocked: "Ders tamamlanmadan not basılmaz.",
    pdfCurriculumLocked: "Müfredat tamamlanmadan toplu not basılmaz.",
    licenseEnded: "Lisans doldu. Mühürlü ders notu ve iş kanıtı kartı durur.",
    /** İkincil aksiyonlar — ana sahnede değil, Araçlar menüsünde. */
    toolsMenu: "Araçlar",
    toolsMenuHint: "Ders notu, iş kanıtı ve stüdyo yardımı",
    toolsClose: "Kapat",
    toolsTask: "İş kanıtı görevi",
  },
  task: {
    eyebrow: "İş kanıtı",
    title: "İş görevi",
    amountHint:
      "Bu görev kuruş tamsayısı ister. Vitrin ₺ gösterir; 25000 yazmak 250,00 ₺ demektir.",
    confirm: "Görevi Onayla",
    confirmed: "Görev mühürlendi",
    locked: "Doğru kayıt olmadan kapı açılmaz",
    amountLabel: "Tutar (kuruş)",
    currencyLabel: "Para birimi",
    promptLabel: "Türkçe tarif",
    promptPlaceholder: "Müşteri isteğine uygun tam tarifi yaz",
    bank: "Parametre bankası",
    slotEmpty: "Boş kilit",
    examGate: "Bölüm İş Görevleri Tamamlandı",
  },
  proof: {
    eyebrow: "İş kanıtı",
    cardTitle: "Mühürlü iş kanıtı",
    studentLabel: "Öğrenci",
    taskSubjectLabel: "Özet türü",
    taskSubjectBody: "Görev mührü — kişi değil",
    lessonLabel: "Ders",
    courseLabel: "Eğitim",
    instructorLabel: "Eğitmen",
    hashLabel: "İş kanıtı özeti",
    completedLabel: "Tamamlama",
    verifyLabel: "Doğrulama",
    pngCta: "PNG indir",
    close: "Kapat",
    anonymousHolder: "Aday",
    pdfFail: "Ders notu basılamadı.",
    pngFail: "Kart görseli basılamadı.",
    curriculumKind: "Müfredat iş kanıtı",
    lessonKind: "Ders simülasyonu",
  },
  visual: {
    diagramEyebrow: "Teknik şema",
    videoEyebrow: "Mikro-video",
    videoMeta: (sec: number) => `${sec} sn · sessiz döngü`,
    paramsEyebrow: "Parametre",
    stepsEyebrow: "Teknik adım",
    codeEyebrow: "Örnek kayıt",
    challengeEyebrow: "İsteğe bağlı alıştırma",
    challengeTry: "Alıştırmayı Dene",
    challengeSkip: "Alıştırmayı Geç / Devam Et",
    challengeDone: "Alıştırma notu alındı — devam",
    challengeSkipped: "Alıştırma geçildi — devam",
  },
  listen: {
    eyebrow: (name: string) => `Moderatör Koray · Eğitmen ${name}`,
    cta: "Dersi Dinle",
    preparing: "Hazırlanıyor…",
    playing: (name: string) => `Stüdyo yayını · Koray ve ${name}`,
    stop: "Durdur",
    replay: "Tekrar dinle",
    fail: "Ses üretilemedi.",
    failTextMode: "Ses yüklenemedi, metin modunda devam et",
    reload: "Yeniden yükle",
    readingMode: "Pürüzsüz Okuma Modu",
    listenMode: "Sesli Dinleme",
    modeRead: "Okuma Modu",
    modeListen: "Sesli Dinleme",
    fallbackNotice: "Pürüzsüz Okuma Modu",
    studioPreparing: "Pürüzsüz Okuma Modu",
    failVoiceBinding:
      "Bu dersin ses kaydı doğrulanamadı; metin açık, ses hazırlanırken yanlış ses sunulmaz.",
    failKey: "Ses servisi şu an yapılandırılmamış.",
    failQuota: "Pürüzsüz Okuma Modu",
    failTimeout: "Pürüzsüz Okuma Modu",
    webSpeech: "Tarayıcı sesi",
    failUpstream: "Pürüzsüz Okuma Modu",
    failEmpty: "Okunacak ders metni yok.",
    focusCurrent: "Okunan bölüm",
    play: "Oynat",
    pause: "Duraklat",
    playPause: "Oynat / Duraklat",
    rewind: "10 sn geri",
    dock: "Yayın çubuğu",
    volume: "Ses",
    mute: "Sesi kapat",
    unmute: "Sesi aç",
    cardProgress: (current: number, total: number) => `${current} / ${total} Bölüm`,
  },
  studio: {
    repeat: "Anlamadım, Tekrar Et",
    ask: "Anlamadım, Soru Soracağım",
    askHint: "Bu bölümde bir canlı soru hakkı var.",
    exhaustedHint: "Bu bölümde canlı soru hakkı doldu. Sonraki bölümde yeni hak açılır.",
    askTitle: "Canlı stüdyo sorusu",
    askLead: "Sorunu yaz, Koray mikrofonu açsın.",
    askSend: "Soruyu ilet",
    askPending: "İletiliyor…",
    askPlaceholder: "Bu bölümde takıldığın nokta",
    askClose: "Kapat",
    policyReject:
      "Gönderdiğin soru yayın ilkelerine uygun bulunmadı. Sorunu nezaketle yeniden yaz.",
  },
  review: {
    title: "Mühürlü değerlendirme",
    lead: "Ders bitti. 1–5 yıldız ve kısa yorum.",
    courseLead: "Müfredat kapandı. 1–5 yıldız ve kısa yorum.",
    commentLabel: "Yorum",
    commentPlaceholder: "Ne netleşti, ne eksik kaldı",
    save: "Değerlendirmeyi kaydet",
    pending: "Kaydediliyor…",
    saved: "Mühürlendi.",
    replyEyebrow: "Stüdyo yanıtı",
    skip: "Şimdi değil",
    stars: (n: number) => `${n} yıldız`,
    fail: "Değerlendirme kaydedilemedi.",
    policyReject:
      "Yorumun yayın ilkelerine uygun bulunmadı. Değerlendirmeyi nezaketle yeniden yaz.",
    outOfScope: "Bu konu Orta / İleri Seviye müfredatımızda yer almaktadır.",
    revisionQueued: "Geri bildiriminiz için teşekkürler, incelemeye alındı.",
    revisionTag: "REVİZYON_TALEBİ",
    misconceptionDefault:
      "Satın alma öğrenme kaydıdır. Ustalık belgesi yalnız müfredat sınavı barajından (70+) sonra basılır.",
  },
  revisions: {
    eyebrow: "Akademi",
    title: "Müfredat revizyonu",
    description:
      "Haklı hata veya eksiklik (REVİZYON_TALEBİ) yorumları burada durur. Onay, ilgili ders sürümünü günceller ve tohum güncelleme günlüğüne yazar. Müfredat mührü ve tohum dosyası bu adımda değişmez.",
    auth: "Müfredat revizyonu oturum ister. Sahte onay basılmaz.",
    forbidden:
      "Bu sığınak Super Admin kilidine bağlıdır. SUPER_ADMIN_USER_ID eşleşmezse kuyruk okunmaz.",
    approve: "Revizyon Onayla",
    pending: "Onaylanıyor…",
    empty: "Bekleyen revizyon talebi yok.",
    emptyHint:
      "REVİZYON_TALEBİ yorumları buraya düşer. Bu arada fiyat kataloğu veya Akademi odasına geçebilirsin; uydurma onay basılmaz.",
    queueEyebrow: "Kuyruk",
    queueTitle: "Bekleyen revizyonlar",
    logEyebrow: "Sicil",
    logTitle: "Tohum güncelleme günlüğü",
    logEmpty: "Günlük boş.",
    logEmptyHint: "Onaylanan revizyonlar tohum güncelleme günlüğüne yazılır.",
    catalogCta: "Fiyat kataloğu",
    academyCta: "Akademi kataloğu",
    dashboardCta: "Panele dön",
    freelancerCta: "İlan tahtası",
    fail: "Revizyon onaylanamadı.",
    fromLabel: "Sürüm",
    lessonLabel: "Ders",
    courseLabel: "Kurs",
    confirmTitle: "Revizyonu onayla?",
    confirmBody:
      "Onay, ilgili ders sürümünü günceller ve tohum güncelleme günlüğüne yazar. Müfredat mührü ve tohum dosyası bu adımda değişmez.",
    confirmCta: "Onayla",
    confirmCancel: "Vazgeç",
    confirmEyebrow: "Onay",
    confirmClose: "Kapat",
    confirmPending: "…",
  },
  levelGate: {
    eyebrow: "Seviye kapısı",
    title: "Bandı aç",
    lead: "Temel, Orta veya İleri. Lisans 365 gün.",
    open: (level: string) => `${level} bandı`,
    catalog: "Katalog",
  },
  pathway: {
    eyebrow: "Seviye Yol Haritası",
    title: "Disiplinin yetkinlik adımları",
    lead: "Her dikey tek konunun seviyeleri değildir; disiplinin Temel → Orta → İleri yetkinlik adımlarıdır. Kart gizlenmez; halka mühürlenince iş kanıtı rozeti basılır.",
    highlightAll: "Tüm halkalar",
    highlight: (level: string) => level,
    ringComplete: "Halka mühürlü",
    proofBadge: "İş kanıtı",
    inspect: "İncele",
    continueCta: "Sıradaki Derse Devam Et",
    extras: "Yol haritası dışı eğitim",
    lessons: (count: number) => `${count} ders`,
    locked: "Kilitli",
    open: "Kayıt açık",
    yours: "Senin",
    priceMissing: "Fiyat yok",
  },
  pilotPath: {
    eyebrow: "Yetkinlik Yolu",
    title: "Mühürlü Kariyer",
    lead: "Dört popüler yol: Python, Full-Stack, Yapay Zekâ, Dijital Ürün. Ders, sunucu sınavı (≥70), SHA-256 mühür, kariyer vizesi.",
    steps: (passScore: number) =>
      [
        {
          key: "lesson",
          label: "Ders içeriği",
          detail: "Modül ve laboratuvar. Okunur, odaklanır.",
        },
        {
          key: "exam",
          label: "Sunucu sınavı",
          detail: `Baraj ${passScore}. Değerlendirme sunucuda.`,
        },
        {
          key: "seal",
          label: "SHA-256 mühür",
          detail: "Sertifika yalnız baraj üstünde basılır.",
        },
        {
          key: "visa",
          label: "Kariyer vizesi",
          detail: "CareerVisaStamp. İlan kapısı bu damgayla açılır.",
        },
      ] as const,
  },
  bridge: {
    cta: (title: string) => `Uzmanlaşmaya Devam Et: ${title}`,
    lead: "Bu halka bitti. Bir üst seviye aynı dikeyde durur.",
    masteryCta: "Tam Kapsam Ustalık Mührü",
    masteryLead: "Dikeyin üç halkası mühürlendi. Kamu doğrulama sayfası mührü gösterir.",
  },
  /** Ders → ders Sokratik köprü (Moderatör Koray pekiştirme). */
  moderatorBridge: {
    eyebrow: "Moderatör Koray · Geçiş köprüsü",
    logEyebrow: "Stüdyo köprü günlüğü",
    confirmCta: "Evet, doğru anlamışız",
    reinforceCta: "Pekiştirip devam et",
    skipCta: "Yeni bölüme geç",
    replyLabel: "Eğitmen / pekiştirme notu",
    replyPlaceholder: "Özeti onayla veya kısa bir düzeltme yaz",
    nextLead: (title: string) => `Sıradaki bölüm: ${title}`,
    confirmedHint: "Teyit alındı. Yeni bölüme geçiliyor.",
  },
  certificates: {
    eyebrow: "Sertifikalar",
    title: "Sertifikalar",
    description:
      "Ustalık belgesi sınav kapısı (≥70) ve SHA-256 içerik özeti ile basılır. İmza değildir. Satın alma öğrenme kaydıdır.",
    catalogCta: "Katalog",
    auth: "Sertifikalar oturum ister.",
    /** Sicil okunamadığında vatandaşa dürüst, gürültüsüz mesaj — geliştirici rozeti yok. */
    unbound: "Sertifika sicili şu an okunamadı. Biraz sonra yenile; uydurma belge basılmaz.",
    empty:
      "Henüz sertifika yok. Kursu satın al, müfredat sınavını ≥70 ile geç. Satın alma tek başına ustalık belgesi değildir.",
    emptyCta: "Kataloga dön",
    sealed: "Mühürlü",
    hashLabel: "SHA-256 içerik özeti",
    scoreLabel: "Puan",
    issuedLabel: "Veriliş",
    verifyCta: "Doğrula",
    /** Mühürlü belge → Kariyer Vize Defteri tek tık. */
    careerVisaCta: "Kariyer Vize Defteri'ne git",
    careerVisaLead:
      "SHA-256 özet kariyer vizesine aktarılır. Defteri aç; işe giriş kapısı orada durur.",
  },
  verify: {
    eyebrow: "Sertifika doğrula",
    title: "İçerik özeti / bütünlük kaydı",
    valid: "Özet sicilde geçerli",
    mismatch: "Özet tutmuyor",
    incomplete: "Özet eksik",
    revoked: "İptal edildi",
    missing: "Sicilde yok",
    invalidFormat: "Hash biçimi SHA256 (64 hex) değil.",
    missingBody: "Bu hash akademi sicilinde yok. Uydurma geçerli damga basılmaz.",
    mismatchBody:
      "Kayıt var; yeniden hesaplanan SHA-256 saklanan özet ile örtüşmüyor. Belge güvenilir sayılmaz.",
    incompleteBody:
      "Kayıt var; deneme, puan veya müfredat özeti eksik olduğu için bütünlük kaydı yeniden hesaplanamaz.",
    validBody:
      "Saklanan SHA-256, vatandaş kimliği + kurs + deneme + puan + basım anı + müfredat özeti üzerinden yeniden üretildi ve tuttu. Bu bir kriptografik imza değildir; sicil bütünlük kaydıdır. İptal ayrı bir kayıttır.",
    revokedBody:
      "İçerik özeti basım anındaki yükle tutuyor; sicil bu belgeyi iptal etti. İşe giriş kapısı olarak kullanılmaz.",
    privacy: "Vatandaş kimliği bu sayfada gösterilmez.",
    hashSubjectLabel: "Özet kime ait",
    hashSubjectPerson:
      "Kişiye bağlı sicil. Hash vatandaş kimliği + kurs + deneme + puan + basım anı + müfredat özetini taşır. Kimlik bu sayfada gösterilmez.",
    hashSubjectTask:
      "Görevin kanonik cevabı. Öğrenci parmak izi değildir; aynı simülasyonu doğru kilitleyen herkesin paylaştığı özettir.",
    hashSubjectPathway:
      "Dikey halkaların kanonik iş kanıtı özetleri. Kişi mührü değildir; yol tohumundan yeniden üretilir.",
    algorithm: "SHA256",
    integrityKindLabel: "Kayıt türü",
    hashedFieldsLabel: "Özet kapsamı",
    curriculumSealLabel: "Müfredat özeti",
    scoreLabel: "Puan",
    issuedLabel: "Basım",
    revokedLabel: "İptal",
    courseCta: "Kursa dön",
    catalogCta: "Katalog",
    careerVisaCta: "Kariyer Vize Defteri'ne git",
    proofEyebrow: "İş kanıtı doğrula",
    proofValid: "Görev mührü geçerli",
    proofValidBody:
      "Bu SHA-256, mühürlü simülasyonun kanonik başarı parametrelerinden yeniden üretildi ve tuttu. Öğrenci parmak izi değildir; görev mührüdür. Kriptografik imza değildir.",
    proofCurriculumValid: "Müfredat iş kanıtı geçerli",
    proofCurriculumBody:
      "Ders iş kanıtları ve müfredat mühürü üzerinden yeniden üretilen SHA-256 tuttu. Vatandaş kimliği bu sayfada gösterilmez.",
    proofKindLabel: "Mühür türü",
    instructorLabel: "Eğitmen",
    masteryTitle: "Tam Kapsam Ustalık Mührü",
    masteryBody:
      "Aday bu dikeyin Temel, Orta ve İleri halkalarını mühürledi. Vatandaş kimliği bu sayfada gösterilmez.",
    masteryPublicBody:
      "Bu SHA-256, dikeyin Temel, Orta ve İleri iş kanıtı özetlerinden yeniden üretildi ve tuttu. Öğrenci parmak izi değildir. Kriptografik imza değildir.",
    pathwayLabel: "Dikey",
    masteryHashLabel: "Kapsam özeti",
  },
} as const;
