export const ACADEMY_SEN = {
  catalog: {
    eyebrow: "Akademi",
    title: "Akademi",
    description:
      "Eğitimi incele, dersleri tamamla, testi geç. Dersler ödeme sonrası açılır. Sertifika ve yetkinlik, test barajını (≥70) geçince Kariyer sayfana işlenir.",
    certificatesCta: "Sertifikalar",
    verifyCta: "Doğrula",
    live: (count: number) => (count > 0 ? "Eğitimler — ders, test ve yetkinlik" : ""),
    unbound: "Liste henüz yüklenemedi.",
    empty: "Yayında eğitim yok.",
    cardCtaInspect: "İncele",
    cardCtaOpen: "Eğitimi Gör",
    /** Vitrin kartı — satın alma yokken birincil eylem. Fiyat butonda yazılmaz. */
    cardCtaBuy: "Satın Al",
    /** Vitrin kartı — DURUM A fiyatlı birincil eylem (antre; kartta kullanılmaz). */
    cardCtaBuyPriced: (priceLabel: string) => `Satın Al — ${priceLabel}`,
    /** Kart / antre tutarı — B2C liste KDV dahildir (antre tek satır). */
    priceVatInclusive: (priceLabel: string) => `${priceLabel} · KDV dahil`,
    /** Kart fiyatının altında küçük KDV ipucu. */
    vatInclusiveHint: "KDV dahil",
    /** Süzgeç chip’i ile aynı etiket — Temel Seviye / Orta Seviye / İleri Seviye. */
    badgeLevel: (level: string) => {
      if (level === "Temel") return "Temel Seviye";
      if (level === "Orta") return "Orta Seviye";
      if (level === "İleri") return "İleri Seviye";
      if (level === "Masterclass") return "Masterclass";
      return level;
    },
    /**
     * Kart kicker — Quiet Luxury seviye indikatörü.
     * Seri modülünde seviye sözcüğü (Temel / Orta / İleri) önde durur; kod ikinci.
     */
    cardLevelContext: (level?: string | null, moduleCode?: string | null) => {
      const label = level?.trim() ?? "";
      const code = moduleCode?.trim() ?? "";
      if (label && code) return `${label} · ${code}`;
      return label || code;
    },
    badgeClosed: "Kayıt kapalı",
    priceMissing: "Fiyat yok",
    /** Quiet Luxury Piyasa Talep Skoru — 100 üzerinden Match Score mührü. */
    marketDemandScoreTitle: "Piyasa Talep Skoru",
    marketDemandScore: (score: number) => `✦ ${score.toFixed(1)}`,
    marketRank: (rank: number) => `Piyasa Sırası: #${rank}`,
    /** Kart meta — eğitmen + bölüm; tekrar eden lab süsü yok. Baraj kurs/sınav sayfasında. */
    cardMeta: (lessons: number, instructorName?: string) =>
      [instructorName ? `Eğitmen: ${instructorName}` : null, `${lessons} Bölüm`]
        .filter((part) => Boolean(part && part.length > 0))
        .join(" · "),
    infoBand: (count: number) =>
      count > 0
        ? "Eğitimler · Dersler ödeme sonrası açılır · Test barajı 70+ · Sertifika ve yetkinlik Kariyer sayfasına işlenir"
        : "",
    seriesPath: "Seviye Yolu",
    boardTitle: "Eğitim kataloğu",
    tabCatalog: "Tüm Katalog",
    tabOwned: "Aldığım Eğitimler",
    tabFavorites: "Favorilerim",
    tabLabel: "Katalog sekmeleri",
    filteredEmpty: "Kriterlere uygun eğitim bulunamadı",
    filteredEmptyHint: "Arama, kategori veya seviye süzgecini gevşetmek sonucu açabilir.",
    ownedEmpty: "Henüz satın alınmış eğitim yok.",
    favoritesEmpty: "Henüz favori eğitim yok.",
    clearFiltersCta: "Süzgeçleri temizle",
    favoriteAdd: "Favorilere ekle",
    favoriteRemove: "Favorilerden çıkar",
    statusContinue: "Devam Et",
    statusCompleted: "Tamamlandı",
  },
  filter: {
    searchPlaceholder: "Eğitimlerde ara...",
    categoryLabel: "Kategori",
    groupLabel: "Ana Grup",
    verticalLabel: "Alt Kategori",
    levelLabel: "Seviye",
    sortLabel: "Sıralama",
    viewLabel: "Görünüm",
    viewGrid: "Izgara",
    viewList: "Liste",
  },

  course: {
    eyebrow: "Eğitim · Akademi",
    catalogCta: "Akademi",
    noPrice: "Fiyat henüz yok — kayıt kapalı",
    notPurchasable: "Bu eğitim şu an kayıt almıyor.",
    /** Antre hero — DURUM A (satın alınmadı). */
    heroBuyCta: (priceLabel: string) => `Eğitimi Satın Al — ${priceLabel}`,
    heroBuyCtaIdle: "Satın Al",
    /** Antre / vitrin fiyat yerine — DURUM B (satın alındı). */
    accessOpen: "Erişim Açık",
    purchasedBadge: "Satın Alındı",
    loginLead: "Eğitimi başlatmak için",
    loginCta: "giriş yap",
    ownedExam: (passScore: number) =>
      `Test açık (baraj ${passScore}). Dersleri bitirip testi başlat. Satın alma tek başına sertifika basmaz.`,
    ownedNoExam: "Dersler açık. Bitirince testi başlatırsın.",
    certificateEyebrow: "Sertifika",
    certificateBody:
      "Testi geçtin. Mührün Kariyer'de vizeye dönüşür; teklif kapıları orada görünür.",
    examEyebrow: "Değerlendirme testi",
    libraryGuarantee:
      "Satın aldığın eğitim kütüphanende 365 gün kalır. Sertifika yalnız testi 70+ ile geçince basılır.",
    purchaseEyebrow: "Eğitimi başlat",
    purchaseBody:
      "Dersleri bitir, testi 70+ ile geç. Sertifika ve yetkinlik Kariyer sayfana işlenir. Satın alma tek başına sertifika basmaz. Gösterilen tutar KDV dahildir.",
    pathTrainingCta: (priceLabel: string) => `Eğitimi Satın Al & Öğren (${priceLabel})`,
    pathTrainingCtaIdle: "Eğitimi Satın Al & Öğren",
    pathTrainingBody: "Video, doküman ve uygulamalı dersler.",
    pathExamCta: (priceLabel: string) => `Doğrudan teste gir ve yetkinlik kazan (${priceLabel})`,
    pathExamCtaIdle: "Doğrudan teste gir ve yetkinlik kazan",
    pathExamBody: "Dersleri atla; yalnız test. Belge 70+ puanla gelir.",
  },
  outline: {
    eyebrow: "İçerik",
    title: "Ders listesi",
    exam: (passScore: number) =>
      `Eğitim bitince test. Baraj ${passScore}. Geçince sertifika ve yetkinlik Kariyer sayfana işlenir.`,
    visaPromise:
      "Testi geçince sertifika basılır; mühür Kariyer'de vizeye ve teklif kapısına dönüşür.",
    lockedHint: "Ders gövdesi ödeme sonrası açılır.",
    empty: "Bu eğitimin ders listesi henüz yok.",
    kindVideo: "Video",
    kindDocument: "Doküman",
    durationMin: (minutes: number) => `${minutes} dk`,
    moduleMeta: (lessons: number, minutes: number) => `${lessons} ders · ${minutes} dk`,
    totalMeta: (lessons: number, minutes: number) => `${lessons} ders · ${minutes} dk`,
    completed: "Tamamlandı",
    locked: "Kilitli",
  },
  outcomes: {
    eyebrow: "Öğrenim çıktıları",
    title: "Bu yolda ne kazanırsın",
    empty: "Çıktı sicili yok.",
  },
  settlement: {
    title: "Ödeme notu",
    steps: (lockMinutes: number) =>
      [
        {
          key: "lock",
          label: "Fiyat",
          detail: `Ödeme anındaki fiyat ${lockMinutes} dakika geçerli kalır.`,
        },
        {
          key: "settle",
          label: "Erişim",
          detail: "Ders erişimi açılınca ifa başlar; 6502 cayma istisnası işler. Lisans 365 gündür.",
        },
        {
          key: "record",
          label: "Belge",
          detail: "Dersler ödeme sonrası açılır. Sertifika bu adımda basılmaz.",
        },
      ] as const,
  },
  purchase: {
    cta: (priceLabel: string) => `Eğitimi Satın Al & Öğren (${priceLabel})`,
    ctaIdle: "Eğitimi Satın Al & Öğren",
    ctaExam: (priceLabel: string) => `Doğrudan teste gir ve yetkinlik kazan (${priceLabel})`,
    ctaExamIdle: "Doğrudan teste gir ve yetkinlik kazan",
    ctaTopUp: "Bakiye Yükle / Öde",
    closed: "Ödeme henüz bağlanmadı / pasif",
    closedBody:
      "Ödeme henüz bağlanmadı / pasif. Kart ile yükleme bağlı değil. Cüzdanında harç varsa eğitimi başlat; yoksa kayıt bekler. Sahte bakiye yazılmaz.",
    pendingCta: "Kaydediliyor…",
    locking: (lockMinutes: number) => `Fiyat onaylanıyor — ${lockMinutes} dakika geçerli.`,
    settling: "Ödeme onaylanıyor.",
    lockFail: "Fiyat onayı alınamadı.",
    buyFail: "Satın alma tamamlanamadı.",
    licenseDuration: "365_DAYS",
    licenseNote:
      "Lisans 365 gün. Gösterilen tutar KDV dahildir. Ders erişimi açılınca dijital içerik ifası başlar; cayma hakkı 6502 istisnasına tabidir. Sertifika yalnız testi 70+ ile geçince basılır.",
  },
  exam: {
    barajHint: (passScore: number) => `Baraj ${passScore}. Satın alma sertifika basmaz.`,
    unanswered: "Tüm soruları yanıtla.",
    submit: "Testi gönder",
    pending: "Değerlendiriliyor…",
    failClosed: "Test değerlendirilemedi.",
    remaining: (mm: string, ss: string) => `Kalan Süre: ${mm}:${ss}`,
    passed: (score: number) =>
      `Testi geçtin (${score}). Sertifikan ve yetkinliğin Kariyer sayfasına işlendi.`,
    viewCertificate: "Sertifikanı gör",
    careerVisa: "Kariyer sayfasında gör",
    forensicHash: "Doğrulama özeti",
    timedOut: "Süre doldu. Son gönderim.",
    failed: (score: number) =>
      `Barajın altında (${score}). Sertifika basılmaz; yeniden dene.`,
    retryHint: "Yeniden gönderebilirsin. Belge yalnız baraj üstünde basılır.",
    locked: "Test ödeme sonrası açılır.",
    workTasksLocked: "Bölüm görevleri bitmeden test kapalı.",
    workProofLead: "Bu testte bir uygulama görevi var. Görevi bitirmeden test gönderilmez.",
    workProofMissing: "Uygulama görevini tamamla.",
    startCta: (_minutes: number, _passScore: number) => "Testi Başlat",
    startLead: (minutes: number, passScore: number) =>
      `Bu test ${minutes} dakika, baraj ${passScore}. Başla deyince süre işler.`,
    starting: "Test açılıyor…",
    startFail: "Test oturumu açılamadı.",
    focusLabel: "Değerlendirme testi",
    stepOf: (current: number, total: number) => `Soru ${current} / ${total}`,
    nextQuestion: "Sonraki soru",
    prevQuestion: "Önceki soru",
    diplomaReveal: "Yetkinlik kazandın",
    chamberEyebrow: "Değerlendirme testi",
    /** Focus Chamber — oturumu iptal; JTI tüketilmez, attempt yazılmaz. */
    abandonCta: "Testten vazgeç",
    exitCta: "Çık",
    abandonLead: "Cevaplar gönderilmez. Yeniden başlayabilirsin.",
  },
  player: {
    eyebrow: (name: string, moderatorName = "Koray") =>
      `Moderatör ${moderatorName} · Eğitmen ${name}`,
    instructorLead: (name: string) => `Bu eğitimi ${name} anlatır.`,
    catalogCta: "Eğitime dön",
    locked: "Ödeme alınmadan ders içeriği açılmaz.",
    lockedBody: "Dersler ödeme sonrası açılır. Eğitimi kurs sayfasından başlat.",
    progress: (done: number, total: number) => `${done} / ${total} ders tamam`,
    cardProgress: (current: number, total: number) => `${current} / ${total} Bölüm`,
    nextCardCta: "Sonraki",
    completeCta: "Dersi Tamamladım",
    prevLessonCta: "Önceki Ders",
    nextOrCompleteCta: "Dersi Tamamladım",
    playlistLabel: "Oynatma listesi",
    companionEyebrow: "Ders açıklaması",
    descriptionEyebrow: "Ders açıklaması",
    resourcesEyebrow: "Kaynaklar",
    discussionEyebrow: "Yorumlar",
    discussionEmpty: "Henüz yorum yok.",
    discussionPlaceholder: "Sorunu veya notunu yaz",
    discussionSubmit: "Yorumu gönder",
    discussionPending: "Gönderiliyor…",
    discussionLocked: "Yorum yazmak için bu eğitime kaydol.",
    discussionCount: (count: number) => `${count} yorum`,
    discussionFail: "Yorum kaydedilemedi.",
    cinemaEyebrow: "Ders yayını",
    cinemaTimeline: "Zaman çizelgesi",
    cinemaFullscreen: "Tam ekran",
    cinemaExitFullscreen: "Tam ekrandan çık",
    cinemaCaptions: "Altyazı",
    cinemaCaptionsOn: "Altyazı açık",
    cinemaCaptionsOff: "Altyazı kapalı",
    cinemaPreparing: "Yayın hazırlanıyor…",
    dialogueEyebrow: "Çift-AI diyalog",
    audioPreparing: "Ders Ses Medyası Hazırlanıyor",
    audioPreparingLead: "Ses dosyası henüz bağlanmadı. Diyalog metnini okuyarak takip edebilirsin.",
    audioTimeline: "Ses zaman çizelgesi",
    labEyebrow: "Kod laboratuvarı",
    labRun: "Çalıştır",
    labCopy: "Kopyala",
    labCopied: "Kopyalandı",
    labReset: "Sıfırla",
    labOutput: "Çıktı",
    labStdin: "Girdi",
    labStdinHint: "input() satırları, her satır bir giriş",
    labEmpty: "Bu derste çalıştırılacak kod yok.",
    labCopyFail: "Kopyalanamadı.",
    completing: "Kaydediliyor…",
    completeFail: "Ders tamamlanamadı.",
    completeLocked: "Görev bitmeden ders kapanmaz.",
    examReady: "Dersler bitti. Testi başlat (baraj 70+).",
    examBlocked: "Tüm dersler bitmeden test kapalı.",
    examCta: "Testi Başlat",
    alreadyDone: "Ders tamam",
    nextHint: "Sıradaki ders açık. Atlanan ders tamamlanmaz.",
    openCta: "Derse başla",
    /** Antre — yarım kalan müfredat. */
    resumeCta: "Kaldığın Yerden Devam Et",
    lessonCount: (count: number) => `${count} ders`,
    levelBadge: (level: string) => level,
    autoAdvance: "Otomatik Geçiş",
    advancing: (sec: number) => `Sıradaki derse geçiyoruz… ${sec}`,
    advanceCancel: "İptal",
    sectionDone: "Bu bölüm bitti. Sıradaki derse geçelim mi?",
    sectionDoneLast: "Bu bölüm bitti.",
    nextLessonCta: "Sonraki Ders",
    /** Katalog / kurs — yarım kalan müfredata dönüş. */
    continueEyebrow: "Devam et",
    continueCta: "Kaldığın derse dön",
    continueStripCta: "Devam Et",
    continueDismiss: "Gizle",
    continueLead: (done: number, total: number, title: string) =>
      done === 0
        ? `${title} · henüz başlanmadı.`
        : `${title} · ${done} / ${total} ders.`,
    continueExamLead: (title: string) => `${title} · dersler bitti. Testi başlat; baraj 70.`,
    continueExamCta: "Testi Başlat",
    continueExamHint: "Test",
    startCta: "Derse başla",
    starting: "Yayın açılıyor…",
    pdfCta: "Ders Notunu İndir (PDF)",
    proofCardCta: "Uygulama kaydı",
    curriculumPdfCta: "Müfredat Notunu İndir (PDF)",
    pdfLessonLocked: "Ders tamamlanmadan not basılmaz.",
    pdfCurriculumLocked: "Müfredat tamamlanmadan toplu not basılmaz.",
    licenseEnded: "Lisans süresi doldu. Ders notları durur.",
    /** İkincil aksiyonlar — ana sahnede değil, Araçlar menüsünde. */
    toolsMenu: "Araçlar",
    toolsMenuHint: "Ders notu ve uygulama görevi",
    toolsClose: "Kapat",
    toolsTask: "Uygulama görevi",
  },
  task: {
    eyebrow: "Uygulama",
    title: "Görev",
    amountHint:
      "Bu görev kuruş tamsayısı ister. Vitrin ₺ gösterir; 25000 yazmak 250,00 ₺ demektir.",
    confirm: "Görevi Onayla",
    confirmed: "Görev tamamlandı",
    locked: "Doğru cevap olmadan devam edilmez",
    amountLabel: "Tutar (kuruş)",
    currencyLabel: "Para birimi",
    promptLabel: "Türkçe tarif",
    promptPlaceholder: "Müşteri isteğine uygun tam tarifi yaz",
    bank: "Parametre bankası",
    slotEmpty: "Boş kilit",
    examGate: "Bölüm görevleri tamamlandı",
  },
  proof: {
    eyebrow: "Uygulama kaydı",
    cardTitle: "Uygulama kaydı",
    studentLabel: "Öğrenci",
    taskSubjectLabel: "Özet türü",
    taskSubjectBody: "Görev mührü — kişi değil",
    lessonLabel: "Ders",
    courseLabel: "Eğitim",
    instructorLabel: "Eğitmen",
    hashLabel: "Kayıt özeti",
    completedLabel: "Tamamlama",
    verifyLabel: "Doğrulama",
    pngCta: "PNG indir",
    close: "Kapat",
    anonymousHolder: "Aday",
    pdfFail: "Ders notu basılamadı.",
    pngFail: "Kart görseli basılamadı.",
    curriculumKind: "Müfredat kaydı",
    lessonKind: "Ders kaydı",
  },
  visual: {
    diagramEyebrow: "Teknik şema",
    videoEyebrow: "Mikro-video",
    videoMeta: (sec: number) => `${sec} sn · sessiz döngü`,
    paramsEyebrow: "Parametre",
    stepsEyebrow: "Teknik adım",
    codeEyebrow: "Örnek kayıt",
    challengeEyebrow: "İsteğe bağlı alıştırma",
    challengeTry: "Alıştırmayı Dene",
    challengeSkip: "Alıştırmayı Geç / Devam Et",
    challengeDone: "Alıştırma notu alındı — devam",
    challengeSkipped: "Alıştırma geçildi — devam",
  },
  listen: {
    eyebrow: (name: string, moderatorName = "Koray") =>
      `Moderatör ${moderatorName} · Eğitmen ${name}`,
    cta: "Dersi Dinle",
    preparing: "Hazırlanıyor…",
    playing: (name: string, moderatorName = "Koray") =>
      `Stüdyo yayını · ${moderatorName} ve ${name}`,
    stop: "Durdur",
    replay: "Tekrar dinle",
    fail: "Ses üretilemedi.",
    failTextMode: "Ses yüklenemedi, metin modunda devam et",
    reload: "Yeniden yükle",
    readingMode: "Pürüzsüz Okuma Modu",
    listenMode: "Sesli Dinleme",
    modeRead: "Okuma Modu",
    modeListen: "Sesli Dinleme",
    fallbackNotice: "Pürüzsüz Okuma Modu",
    studioPreparing: "Pürüzsüz Okuma Modu",
    failVoiceBinding:
      "Bu dersin ses kaydı doğrulanamadı; metin açık, ses hazırlanırken yanlış ses sunulmaz.",
    failKey: "Ses servisi şu an yapılandırılmamış.",
    failQuota: "Pürüzsüz Okuma Modu",
    failTimeout: "Pürüzsüz Okuma Modu",
    webSpeech: "Tarayıcı sesi",
    failUpstream: "Pürüzsüz Okuma Modu",
    failEmpty: "Okunacak ders metni yok.",
    focusCurrent: "Okunan bölüm",
    play: "Oynat",
    pause: "Duraklat",
    playPause: "Oynat / Duraklat",
    rewind: "10 sn geri",
    dock: "Yayın çubuğu",
    volume: "Ses",
    mute: "Sesi kapat",
    unmute: "Sesi aç",
    cardProgress: (current: number, total: number) => `${current} / ${total} Bölüm`,
  },
  studio: {
    repeat: "Anlamadım, Tekrar Et",
    ask: "Anlamadım, Soru Soracağım",
    askHint: "Bu bölümde bir canlı soru hakkı var.",
    exhaustedHint: "Bu bölümde canlı soru hakkı doldu. Sonraki bölümde yeni hak açılır.",
    askTitle: "Canlı stüdyo sorusu",
    askLead: "Sorunu yaz, Koray mikrofonu açsın.",
    askSend: "Soruyu ilet",
    askPending: "İletiliyor…",
    askPlaceholder: "Bu bölümde takıldığın nokta",
    askClose: "Kapat",
    policyReject:
      "Gönderdiğin soru yayın ilkelerine uygun bulunmadı. Sorunu nezaketle yeniden yaz.",
  },
  review: {
    title: "Değerlendirme",
    lead: "Ders bitti. 1–5 yıldız ve kısa yorum.",
    courseLead: "Müfredat kapandı. 1–5 yıldız ve kısa yorum.",
    commentLabel: "Yorum",
    commentPlaceholder: "Ne netleşti, ne eksik kaldı",
    save: "Değerlendirmeyi kaydet",
    pending: "Kaydediliyor…",
    saved: "Kaydedildi.",
    replyEyebrow: "Stüdyo yanıtı",
    skip: "Şimdi değil",
    stars: (n: number) => `${n} yıldız`,
    fail: "Değerlendirme kaydedilemedi.",
    policyReject:
      "Yorumun yayın ilkelerine uygun bulunmadı. Değerlendirmeyi nezaketle yeniden yaz.",
    outOfScope: "Bu konu Orta / İleri Seviye müfredatımızda yer almaktadır.",
    revisionQueued: "Geri bildiriminiz için teşekkürler, incelemeye alındı.",
    revisionTag: "REVİZYON_TALEBİ",
    misconceptionDefault:
      "Satın alma öğrenme kaydıdır. Ustalık belgesi yalnız müfredat sınavı barajından (70+) sonra basılır.",
  },
  revisions: {
    eyebrow: "Akademi",
    title: "Müfredat revizyonu",
    description:
      "Haklı hata veya eksiklik (REVİZYON_TALEBİ) yorumları burada durur. Onay, ilgili ders sürümünü günceller ve tohum güncelleme günlüğüne yazar. Müfredat mührü ve tohum dosyası bu adımda değişmez.",
    auth: "Müfredat revizyonu oturum ister. Sahte onay basılmaz.",
    forbidden:
      "Bu sığınak Super Admin kilidine bağlıdır. SUPER_ADMIN_USER_ID eşleşmezse kuyruk okunmaz.",
    approve: "Revizyon Onayla",
    pending: "Onaylanıyor…",
    empty: "Bekleyen revizyon talebi yok.",
    emptyHint:
      "REVİZYON_TALEBİ yorumları buraya düşer. Bu arada fiyat kataloğu veya Akademi odasına geçebilirsin; uydurma onay basılmaz.",
    queueEyebrow: "Kuyruk",
    queueTitle: "Bekleyen revizyonlar",
    logEyebrow: "Sicil",
    logTitle: "Tohum güncelleme günlüğü",
    logEmpty: "Günlük boş.",
    logEmptyHint: "Onaylanan revizyonlar tohum güncelleme günlüğüne yazılır.",
    catalogCta: "Fiyat kataloğu",
    academyCta: "Akademi kataloğu",
    dashboardCta: "Panele dön",
    freelancerCta: "İlan tahtası",
    fail: "Revizyon onaylanamadı.",
    fromLabel: "Sürüm",
    lessonLabel: "Ders",
    courseLabel: "Kurs",
    confirmTitle: "Revizyonu onayla?",
    confirmBody:
      "Onay, ilgili ders sürümünü günceller ve tohum güncelleme günlüğüne yazar. Müfredat mührü ve tohum dosyası bu adımda değişmez.",
    confirmCta: "Onayla",
    confirmCancel: "Vazgeç",
    confirmEyebrow: "Onay",
    confirmClose: "Kapat",
    confirmPending: "…",
  },
  levelGate: {
    eyebrow: "Seviye kapısı",
    title: "Bandı aç",
    lead: "Temel, Orta veya İleri. Lisans 365 gün.",
    open: (level: string) => `${level} bandı`,
    catalog: "Katalog",
  },
  pathway: {
    eyebrow: "Seviye Yol Haritası",
    title: "Disiplinin yetkinlik adımları",
    lead: "Her alanın Temel → Orta → İleri adımları. Kart gizlenmez; eğitim bitince rozet görünür.",
    highlightAll: "Tüm seviyeler",
    highlight: (level: string) => level,
    ringComplete: "Tamamlandı",
    proofBadge: "Belge",
    inspect: "İncele",
    continueCta: "Sıradaki Derse Devam Et",
    extras: "Yol haritası dışı eğitim",
    lessons: (count: number) => `${count} ders`,
    locked: "Kilitli",
    open: "Kayıt açık",
    yours: "Senin",
    priceMissing: "Fiyat yok",
  },
  pilotPath: {
    eyebrow: "Akademi",
    title: "Akademi",
    lead: "Dersleri bitir, testi geç, yetkinliği Kariyer sayfana taşı.",
    steps: (passScore: number) =>
      [
        {
          key: "lesson",
          label: "Eğitimi Tamamla",
          detail: "Video ve doküman derslerini sırayla bitir.",
        },
        {
          key: "exam",
          label: "Testi Başlat",
          detail: `Baraj ${passScore}. Değerlendirme sunucuda.`,
        },
        {
          key: "seal",
          label: "Sertifika / Yetkinlik Kazan",
          detail: "Geçince belge basılır; yetkinlik Kariyer sayfana işlenir.",
        },
        {
          key: "visa",
          label: "Kariyer sayfası",
          detail: "Mührün vizeye dönüşür; hangi işe teklif vereceğin orada görünür.",
        },
      ] as const,
  },
  bridge: {
    cta: (title: string) => `Sıradaki eğitim: ${title}`,
    lead: "Bu eğitim bitti. Bir üst seviye aynı alanda durur.",
    masteryCta: "Alan sertifikası",
    masteryLead: "Bu alanın üç seviyesini tamamladın. Doğrulama sayfası belgeyi gösterir.",
  },
  /** Ders → ders Sokratik köprü (Moderatör Koray pekiştirme). */
  moderatorBridge: {
    eyebrow: "Moderatör Koray · Geçiş köprüsü",
    logEyebrow: "Stüdyo köprü günlüğü",
    confirmCta: "Evet, doğru anlamışız",
    reinforceCta: "Pekiştirip devam et",
    skipCta: "Yeni bölüme geç",
    replyLabel: "Eğitmen / pekiştirme notu",
    replyPlaceholder: "Özeti onayla veya kısa bir düzeltme yaz",
    nextLead: (title: string) => `Sıradaki bölüm: ${title}`,
    confirmedHint: "Teyit alındı. Yeni bölüme geçiliyor.",
  },
  certificates: {
    eyebrow: "Sertifikalar",
    title: "Sertifikalar",
    description:
      "Sertifika, testi 70+ ile geçince basılır. Satın alma tek başına belge değildir. Yetkinlik Kariyer sayfasına işlenir.",
    catalogCta: "Katalog",
    auth: "Sertifikalar oturum ister.",
    /** Sicil okunamadığında vatandaşa dürüst, gürültüsüz mesaj — geliştirici rozeti yok. */
    unbound: "Sertifika sicili şu an okunamadı. Biraz sonra yenile; uydurma belge basılmaz.",
    empty:
      "Henüz sertifika yok. Eğitimi al, dersleri bitir, testi 70+ ile geç.",
    emptyCta: "Kataloga dön",
    sealed: "Onaylı",
    hashLabel: "SHA-256 içerik özeti",
    scoreLabel: "Puan",
    issuedLabel: "Veriliş",
    verifyCta: "Doğrula",
    /** Mühürlü belge → Kariyer vitrini tek tık. */
    careerVisaCta: "Kariyer sayfasında gör",
    careerVisaLead:
      "Mührün Kariyer'de vizeye dönüşür. Teklif kapıları orada görünür.",
  },
  verify: {
    eyebrow: "Sertifika doğrula",
    title: "İçerik özeti / bütünlük kaydı",
    valid: "Özet sicilde geçerli",
    mismatch: "Özet tutmuyor",
    incomplete: "Özet eksik",
    revoked: "İptal edildi",
    missing: "Sicilde yok",
    invalidFormat: "Hash biçimi SHA256 (64 hex) değil.",
    missingBody: "Bu hash akademi sicilinde yok. Uydurma geçerli damga basılmaz.",
    mismatchBody:
      "Kayıt var; yeniden hesaplanan SHA-256 saklanan özet ile örtüşmüyor. Belge güvenilir sayılmaz.",
    incompleteBody:
      "Kayıt var; deneme, puan veya müfredat özeti eksik olduğu için bütünlük kaydı yeniden hesaplanamaz.",
    validBody:
      "Saklanan SHA-256, vatandaş kimliği + kurs + deneme + puan + basım anı + müfredat özeti üzerinden yeniden üretildi ve tuttu. Bu bir kriptografik imza değildir; sicil bütünlük kaydıdır. İptal ayrı bir kayıttır.",
    revokedBody:
      "İçerik özeti basım anındaki yükle tutuyor; sicil bu belgeyi iptal etti. İşe giriş kapısı olarak kullanılmaz.",
    privacy: "Vatandaş kimliği bu sayfada gösterilmez.",
    hashSubjectLabel: "Özet kime ait",
    hashSubjectPerson:
      "Kişiye bağlı sicil. Hash vatandaş kimliği + kurs + deneme + puan + basım anı + müfredat özetini taşır. Kimlik bu sayfada gösterilmez.",
    hashSubjectTask:
      "Görevin kanonik cevabı. Öğrenci parmak izi değildir; aynı simülasyonu doğru kilitleyen herkesin paylaştığı özettir.",
    hashSubjectPathway:
      "Alan seviyelerinin kanonik kayıt özetleri. Kişi belgesi değildir; yol tohumundan yeniden üretilir.",
    algorithm: "SHA256",
    integrityKindLabel: "Kayıt türü",
    hashedFieldsLabel: "Özet kapsamı",
    curriculumSealLabel: "Müfredat özeti",
    scoreLabel: "Puan",
    issuedLabel: "Basım",
    revokedLabel: "İptal",
    courseCta: "Kursa dön",
    catalogCta: "Katalog",
    careerVisaCta: "Kariyer sayfasında gör",
    landingTitle: "Sertifika doğrula",
    landingLead:
      "Üçüncü şahıs veya kurum, 64 hex SHA-256 özetini yazar. Oturum istenmez; vatandaş kimliği gösterilmez.",
    hashFieldLabel: "SHA-256 içerik özeti",
    hashPlaceholder: "64 karakter hex",
    submitCta: "Özeti doğrula",
    qrCaption: "Kamera bu sayfayı açar",
    proofEyebrow: "Uygulama kaydını doğrula",
    proofValid: "Görev kaydı geçerli",
    proofValidBody:
      "Bu SHA-256, simülasyonun kanonik başarı parametrelerinden yeniden üretildi ve tuttu. Öğrenci parmak izi değildir. Kriptografik imza değildir.",
    proofCurriculumValid: "Müfredat kaydı geçerli",
    proofCurriculumBody:
      "Ders kayıtları ve müfredat özeti üzerinden yeniden üretilen SHA-256 tuttu. Vatandaş kimliği bu sayfada gösterilmez.",
    proofKindLabel: "Kayıt türü",
    instructorLabel: "Eğitmen",
    masteryTitle: "Alan sertifikası",
    masteryBody:
      "Aday bu alanın Temel, Orta ve İleri seviyelerini tamamladı. Vatandaş kimliği bu sayfada gösterilmez.",
    masteryPublicBody:
      "Bu SHA-256, alanın Temel, Orta ve İleri kayıt özetlerinden yeniden üretildi ve tuttu. Öğrenci parmak izi değildir. Kriptografik imza değildir.",
    pathwayLabel: "Alan",
    masteryHashLabel: "Kapsam özeti",
  },
} as const;
