import { YETKIN_BRAND } from "@/lib/copy/brand";

/** Rail SEN aksı — giriş / kayıt / şifre. Müze sen-voice kopyalanmaz. */
export const AUTH_SEN = {
  brand: YETKIN_BRAND,
  skeletonAria: "Kimlik yüzeyi yükleniyor",
  login: {
    title: "Giriş",
    description: "Güvenli oturum. Kimliğin hesabına bağlıdır.",
    unbound: "Giriş henüz bağlanmadı. Hesap bağlantısı tamamlanınca bu form açılır.",
    email: "E-posta",
    password: "Şifre",
    submit: "Giriş yap",
    pending: "Giriş…",
    fail: "Giriş başarısız.",
    envMissing:
      "Tarayıcı kimlik istemcisi yapılandırılmadı. Geliştirme sunucusunu env ile yeniden başlat.",
    timeout: "Kimlik sunucusuna ulaşılamadı. Ağ veya CSP bağlantısı kapalı olabilir.",
    invalid: "E-posta veya şifre kabul edilmedi.",
    unconfirmed: "E-posta henüz doğrulanmadı. Gelen kutudaki bağlantıyı aç.",
    forgotCta: "Şifremi Unuttum?",
    registerCta: "Kayıt",
    homeCta: "Ana sayfa",
  },
  logout: {
    submit: "Çıkış Yap",
    pending: "Çıkış…",
    blurb: "Oturumu kapat",
  },
  register: {
    title: "Kayıt",
    description: "Hesap aç; Türk Lirası cüzdanın seninle kurulur.",
    unbound: "Kayıt henüz bağlanmadı. Bağlantı tamamlanınca hesabın ve cüzdanın burada açılır.",
    fullName: "Ad soyad",
    fullNameInvalid: "Ad soyad geçersiz.",
    email: "E-posta",
    password: "Şifre",
    ageConfirm: "18 yaşından büyüğüm.",
    ageRequired: "Kayıt için 18 yaşından büyük olduğunu onaylaman gerekir.",
    submit: "Hesap oluştur",
    pending: "Kayıt…",
    fail: "Kayıt başarısız.",
    duplicate: "Bu e-posta zaten kayıtlı. Giriş yap.",
    success: "Kayıt alındı. E-posta doğrulaması açıksa gelen kutunu kontrol et.",
    loginCta: "Giriş",
    generatePassword: "Güvenli Şifre Üret",
    copy: "Kopyala",
    copied: "Kopyalandı",
    copyFail: "Panoya kopyalanamadı — görünür şifreyi elle kopyala.",
    copyEmpty: "Önce bir şifre yaz veya üret.",
    passwordHint: (min: number) =>
      `En az ${min} karakter. Üretilen şifre 16 karakter ve dört sınıftır; panoya kopyalamayı unutma.`,
  },
  forgot: {
    title: "Şifremi Unuttum",
    description: "Kayıtlı e-postana sıfırlama bağlantısı gider. Hesap yoksa ileti gelmez.",
    unbound: "Şifre sıfırlama henüz bağlanmadı. Hesap bağlantısı tamamlanınca bu form açılır.",
    email: "E-posta",
    submit: "Sıfırlama bağlantısı gönder",
    pending: "Gönderiliyor…",
    fail: "Sıfırlama isteği gönderilemedi.",
    invalidEmail: "Geçerli bir e-posta yaz.",
    sent: "Sıfırlama bağlantısı yola çıktı. Gelen kutunu ve spam klasörünü kontrol et. Bu adres sistemde kayıtlı değilse e-posta gelmez; hesap varlığını burada doğrulamayız.",
    supportLead: "Bağlantı gelmezse",
    supportTail: "yaz.",
    backCta: "Giriş sayfasına dön",
    loginCta: "Giriş",
    registerCta: "Kayıt",
  },
  reset: {
    title: "Şifre Yenile",
    description: "E-postadaki bağlantı bu sayfayı açar. Yeni şifre en az 8 karakterdir.",
    unbound: "Şifre yenileme henüz bağlanmadı. Hesap bağlantısı tamamlanınca bu form açılır.",
    newPassword: "Yeni şifre",
    confirmPassword: "Şifreyi doğrula",
    submit: "Şifreyi kaydet",
    pending: "Kaydediliyor…",
    fail: "Şifre güncellenemedi.",
    success: "Şifre güncellendi. Şimdi giriş yap.",
    mismatch: "Şifreler eşleşmiyor.",
    tooShort: (min: number) => `Şifre en az ${min} karakter olmalı.`,
    noSession: "Sıfırlama oturumu yok. E-postadaki bağlantıya tekrar tıkla.",
    checking: "Sıfırlama oturumu kontrol ediliyor…",
    missing:
      "Sıfırlama oturumu bulunamadı. E-postadaki bağlantıya tekrar tıkla veya yeni bir bağlantı iste.",
    forgotCta: "Şifremi Unuttum?",
    loginCta: "Giriş",
  },
} as const;
