/** Rail SEN aksı — kariyer odası. Doğrulanmış Rozetten türetilen salt okuma damga projeksiyonu. */
export const CAREER_SEN = {
  eyebrow: "Kariyer",
  title: "Kariyer vizesi",
  description:
    "Kariyer vizesi burada görünür: Doğrulanmış Rozetin Pasaport Vize Damgasına dönüşür. Yapay zeka sertifikası Akademi sınavından türer. Teklif Kapısı işveren ağına görünürlük, mühürlü özgeçmiş bağlantısı ve proje kanıt dosyasını açar. Sahte rozet eklenmez.",
  faqHeading: "Sık sorulanlar",
  auth: "Kariyer sayfasını görmek için giriş yap.",
  /** Sicil okunamadığında vatandaşa dürüst, gürültüsüz mesaj — geliştirici rozeti yok. */
  loadSoft: "Kariyer bilgilerin şu an yüklenemedi. Biraz sonra sayfayı yenile.",
  ledgerTitle: "Pasaport Vize Damgası",
  proofsTitle: "Pasaport Vize Damgası",
  visasTitle: "Pasaport Vize Damgaları",
  proofEmpty:
    "Henüz bir Pasaport Vize Damgan yok. Akademi'de 9 dersi bitir, testi 70+ ile geç; mühürlü sertifikan burada görünür. Satın alma tek başına damga basmaz.",
  academyCta: "Akademiye git",
  freelancerCta: "Freelancer'a git",
  passportCta: "Pasaport",
  certificatesCta: "Sertifikalarım",
  freelancerBoardCta: "Freelancer İlan Panosu",
  publicTalentCta: "Kamuya açık yetkinlik kartı",
  sealed: "Doğrulanmış Rozet",
  hashLabel: "SHA-256 içerik özeti",
  hashNote: "İçerik özetidir; imza değildir.",
  proofLine: "Portföy kaydı",
  issuedLabel: "Veriliş tarihi",
  verifyCta: "Sertifikayı doğrula",
  openCourseCta: "Eğitime git",
  openContractCta: "Sözleşmeyi aç",
  copyVisa: "Belge anahtarını kopyala",
  copyHash: "Özeti kopyala",
  copied: "Kopyalandı",
  copyFail: "Kopyalanamadı",
  footnote:
    "Pasaport Vize Damgası yalnız Akademi müfredat sınavından türer: 9 ders tamam + baraj 70. Elle basılmaz. Pasaport listeler; damgayı Kariyer basar. İptal edilmiş Akademi belgesi burada görünmez. Hedef rol, yetenek haritası veya mülakat oyunu yok.",
  footnotePassportCta: "Pasaportu aç",
  footnoteVerifyCta: "Sertifika doğrula",
  footnoteAcademyCta: "Akademiye git",
  ledger: {
    eyebrow: "Pasaport Vize Damgası",
    title: "Pasaport Vize Damgası defteri",
    lead: "Doğrulanmış Rozetin burada Pasaport Vize Damgasına dönüşür. Paylaştığın kart doğrulanabilir bir belgedir. Sahte rozet eklenmez.",
  },
  scope: {
    eyebrow: "Teklif Kapısı",
    title: "Teklif Kapısı",
    lead: "Kapı, ilgili Akademi SKU’sunun 9 dersi bitirilip sınav 70+ geçilince açılır. Satın alma belge basmaz. Açık kapıda üç hak doğar: doğrulanmış işveren ağına görünürlük, liyakat mühürlü özgeçmiş bağlantısı ve proje kanıt dosyası.",
    open: "Erişim Hakkı açık",
    closed: "Erişim Hakkı kapalı",
    held: "Sınav mühürlü",
    missing: "Sınav bekleniyor",
    examGate: "9 ders + baraj 70",
    benefitEmployer: "Doğrulanmış İşveren Ağına Görünürlük",
    benefitEmployerBody:
      "Açık kapı, bu SKU’nun müfredat sınavını (≥70) geçince o uzmanlık ilanında teklif hakkını taşır. İşveren senin mühür kartını oturumsuz görür.",
    benefitResume: "Liyakat Mühürlü Özgeçmiş Bağlantısı",
    benefitResumeBody:
      "Kamuya açık yetkinlik kartın mühürleri, sertifika doğrulama bağını ve proje kanıtını tek adreste toplar.",
    benefitProof: "Proje Kanıt Dosyası",
    benefitProofBody:
      "Damgaya bağlı portföy satırı işverene teslim kanıtını gösterir. Serbest içerik eklenmez.",
    benefitLocked: "Kapalı",
    benefitReady: "Hazır",
    publicCardCta: "Mühürlü kartı aç",
  },
  gateway: {
    eyebrow: "İşveren Kapısı",
    title: "Proof-of-Work ve İşveren Kapısı",
    lead: "Vaat panosu değil: açık kapı, paylaşılabilir mühür kartı ve damgaya bağlı proje kanıtı. Sahte vitrin yok.",
  },
  publicPage: {
    eyebrow: "Kamuya açık yetkinlik",
    title: "Liyakat mühürlü özgeçmiş kartı",
    description:
      "Mühürler, sertifika doğrulama bağları ve proje kanıtları. Oturum istenmez; vatandaş kimliği ve e-posta gösterilmez.",
    landingTitle: "Kariyer vizesi kartı",
    landingLead:
      "Bu adres bir kariyer vizesi kartıdır (Pasaport Vize Damgası). Yapay zeka sertifikası sicile bağlıdır. Bağ, Kariyer odasından kopyalanır. Uydurma kart basılmaz.",
    missing: "Kart sicilde yok",
    missingBody: "Bu bağlantıya ait canlı mühür yok. İptal edilmiş belge burada görünmez.",
    invalidFormat: "Kart anahtarı geçersiz.",
    privacy: "Vatandaş kimliği, e-posta ve sözleşme numarası bu kartta yoktur.",
    sealsTitle: "Doğrulanmış mühürler",
    proofsTitle: "Proje kanıt dosyası",
    proofEmpty: "Bu karta bağlı proje kanıt satırı yok.",
    verifyCta: "Sertifikayı doğrula",
    openCourseCta: "Eğitime git",
    careerCta: "Kariyer",
    academyCta: "Akademiye git",
    homeCta: "Ana sayfa",
    faqHeading: "Sık sorulanlar",
    featured: "Öne çıkan mühür",
  },
  badge: {
    cvCta: "CV'ne Mühür Ekle",
    linkedInCta: "LinkedIn Yetkinlik Onayına Bağla",
    cvEyebrow: "Özgeçmiş rehberi",
    cvTitle: "CV'ne mühürlü bağ ekle",
    cvLead:
      "İşveren CV'deki sertifika satırından bu karta ve açık sicil doğrulamasına iner. Vatandaş kimliği bağda yoktur.",
    cvStep1: "Liyakat mühürlü özgeçmiş bağlantısını kopyala.",
    cvStep2: "Sertifika doğrulama bağını kopyala.",
    cvStep3: "CV'de sertifika satırına köprü olarak yapıştır. QR istersen doğrulama sayfasındadır.",
    linkedInEyebrow: "LinkedIn rehberi",
    linkedInTitle: "LinkedIn yetkinlik onayına bağla",
    linkedInLead:
      "LinkedIn Lisanslar ve sertifikalar formunu mühürlü sicil bağınla açar. Paylaşım vatandaş kimliği taşımaz.",
    linkedInStep1: "Aşağıdaki düğme LinkedIn sertifika ekleme formunu açar.",
    linkedInStep2: "Kuruluş yetkin.ai, belgenin adı ve doğrulama bağın hazır gelir. Tarihi kontrol et.",
    linkedInStep3: "Kaydet. İstersen ilgili yetkinliği de ekleyip bu bağa işaret et.",
    linkedInOpen: "LinkedIn formunu aç",
    copyTalent: "Özgeçmiş bağını kopyala",
    copyVerify: "Doğrulama bağını kopyala",
    copied: "Kopyalandı",
    copyFail: "Kopyalanamadı",
    locked: "Önce Akademi'de bir Doğrulanmış Rozet kazan. Mühür olmadan bağ üretilmez.",
    lockedCta: "Akademiye git",
  },
} as const;
