/** Rail SEN aksı — kariyer odası. Doğrulanmış Rozetten türetilen salt okuma damga projeksiyonu. */
export const CAREER_SEN = {
  eyebrow: "Kariyer",
  title: "Kariyer",
  description:
    "Doğrulanmış Rozetin Pasaport Vize Damgası olarak sicile düşer; Teklif Kapısını ve Erişim Hakkını açar. Pasaport damgaları listeler; damgayı burası basar. Hedef rol, yetenek haritası veya mülakat oyunu yok.",
  auth: "Kariyer sayfasını görmek için giriş yap.",
  /** Sicil okunamadığında vatandaşa dürüst, gürültüsüz mesaj — geliştirici rozeti yok. */
  loadSoft: "Kariyer bilgilerin şu an yüklenemedi. Biraz sonra sayfayı yenile.",
  ledgerTitle: "Pasaport Vize Damgası",
  proofsTitle: "Pasaport Vize Damgası",
  visasTitle: "Pasaport Vize Damgaları",
  proofEmpty:
    "Henüz bir Pasaport Vize Damgan yok. Akademi'de bir eğitimi tamamla veya Freelancer'da bir iş teslim et — Doğrulanmış Rozetin burada görünür.",
  academyCta: "Akademiye git",
  freelancerCta: "Freelancer'a git",
  passportCta: "Pasaport",
  certificatesCta: "Sertifikalarım",
  freelancerBoardCta: "Freelancer İlan Panosu",
  sealed: "Doğrulanmış Rozet",
  hashLabel: "SHA-256 içerik özeti",
  hashNote: "İçerik özetidir; imza değildir.",
  proofLine: "Portföy kaydı",
  issuedLabel: "Veriliş tarihi",
  verifyCta: "Sertifikayı doğrula",
  openCourseCta: "Eğitime git",
  openContractCta: "Sözleşmeyi aç",
  copyVisa: "Belge anahtarını kopyala",
  copyHash: "Özeti kopyala",
  copied: "Kopyalandı",
  copyFail: "Kopyalanamadı",
  footnote:
    "Pasaport Vize Damgası yalnız Akademi sınavı ve Freelancer tesliminden türer. Elle basılmaz. Pasaport listeler; damgayı Kariyer basar. İptal edilmiş Akademi belgesi burada görünmez.",
  footnotePassportCta: "Pasaportu aç",
  footnoteVerifyCta: "Sertifika doğrula",
  footnoteAcademyCta: "Akademiye git",
  ledger: {
    eyebrow: "Pasaport Vize Damgası",
    title: "Pasaport Vize Damgası defteri",
    lead: "Doğrulanmış Rozetin burada Pasaport Vize Damgasına dönüşür. Paylaştığın kart doğrulanabilir bir belgedir. Sahte rozet eklenmez.",
  },
  scope: {
    eyebrow: "Teklif Kapısı",
    title: "Teklif Kapısı",
    lead: "Açık Erişim Hakkı, Doğrulanmış Rozetinin hangi işe teklif vereceğini gösterir. Teklif Kapısı elle açılmaz.",
    open: "Erişim Hakkı açık",
    closed: "Erişim Hakkı kapalı",
    held: "Belgen var",
    missing: "Belge yok",
  },
} as const;
