/** Rail SEN aksı — freelancer odası. Müze sen-voice kopyalanmaz. */
export const FREELANCER_SEN = {
  catalog: {
    eyebrow: "Bağımsız iş",
    title: "Freelancer tezgâhı",
    description:
      "İlan oluştur, teklifi kabul et. Bakiye kilitlidir. Teslim onayı ile aktarılır. İtiraz durumunda tahkim süreci işler.",
    createCta: "İlan oluştur",
    live: (count: number) => `Canlı sicil — ${count} ilan`,
    unbound: "Liste henüz yüklenemedi — örnek düzen",
  },
  stats: {
    openLabel: "Açık ilan",
    escrowLabel: "Emanet",
    escrowValue: "kilit",
    escrowHint: "bakiye kilitlidir",
    pathLabel: "Mutlu yol",
    pathValue: "3 adım",
    pathHint: "ilan → emanet → teslim",
  },
  list: {
    emptyHint: "Canlı ilan yok. Aşağıdaki kartlar vitrin düzenidir; sahte iş emanetine kilitlemez.",
    openCta: "İlanı aç",
    lockLabel: "Emanet kilit",
  },
  job: {
    eyebrow: "İlan",
    budgetLabel: "Bütçe",
    contractTitle: "Sözleşme",
    contractCta: "Emanet sözleşmesini aç",
    bidsTitle: "Teklifler",
    bidsEmpty: "Henüz teklif yok.",
    bidTitle: "Teklif ver",
    loginLead: "Teklif veya kabul için",
    loginCta: "giriş yap",
    visaGate:
      "Nitelikli ilana teklif Kariyer Vizesi (akademi sertifikası) ister. Emanet tutarı vizeden bağımsızdır.",
    visaCta: "Kariyer pasaportu",
  },
  create: {
    eyebrow: "Bağımsız iş",
    title: "İlan oluştur",
    description:
      "Bütçe, teklif kabulünde cüzdanda kilitlenir. Bakiye kilitlidir. Teslim onayı ile aktarılır.",
    backCta: "Tezgâha dön",
    titleLabel: "Başlık",
    briefLabel: "İş tanımı",
    budgetLabel: "Bütçe (₺)",
    band: (minMajor: number, maxMajor: number, holdPercent: number) =>
      `Bant: ₺${minMajor} – ₺${maxMajor}. Teklif kabulünde tutar cüzdanda kilitlenir; platform payı %${holdPercent}. Teslim onayı ile aktarılır.`,
    submit: "İlan oluştur",
    pending: "Oluşturuluyor…",
    fail: "İlan açılamadı.",
  },
  escrow: {
    title: "Emanet mühürü",
    eyebrow: "Hold · teslim · tahkim",
    holdNotice: (amount: string, holdPercent: number) =>
      `Kabul, ${amount} tutarını cüzdanda kilitler (emanet hold, platform payı %${holdPercent}). Anında settlement yoktur.`,
    pendingLive: "Bakiye kilitleniyor…",
    steps: (holdPercent: number) =>
      [
        {
          key: "hold" as const,
          label: "Bakiye kilitli",
          detail:
            "Kabulde tutar cüzdanda kilitlenir. Bakiye kilitlidir; freelancer henüz almaz. Anında settlement yoktur.",
        },
        {
          key: "release" as const,
          label: "Teslim onayı ile aktarılır",
          detail: `İşveren teslimi onaylayınca net freelancer cüzdanına, platform payı (%${holdPercent}) hazineye geçer.`,
        },
        {
          key: "dispute" as const,
          label: "İtiraz durumunda tahkim süreci işler",
          detail:
            "İki turlu bilirkişi tahkimi. Emanet kilitli kalır; iade veya bölüşüm rapora bağlanır.",
        },
      ] as const,
  },
  accept: {
    cta: "Teklifi kabul et — bakiyeyi kilitle",
    pending: "Kilitleniyor…",
    fail: "Teklif kabul edilemedi.",
  },
  bid: {
    amountLabel: "Teklif (₺)",
    coverLabel: "Kapak notu",
    submit: "Teklif gönder",
    pending: "Gönderiliyor…",
    received: "Teklif alındı.",
    fail: "Teklif gönderilemedi.",
    visaDenied: "Teklif kapalı — Kariyer Vizesi yok.",
  },
  contract: {
    eyebrow: "Sözleşme",
    fallbackTitle: "Emanet sözleşmesi",
    splitTitle: "Ödeme dağılımı",
    gross: "Toplam",
    platformShare: (percent: number) => `Platform payı (%${percent})`,
    freelancerShare: "Freelancer payı",
    lock: "Kilit",
    backCta: "Tezgâha dön",
  },
  actions: {
    release: "Teslimi onayla ve aktar",
    releasing: "Aktarılıyor…",
    refund: "İade et",
    refunding: "İade…",
    fundedHint: "Bakiye kilitlidir. Teslim onayı ile aktarılır; iade işverene döner.",
    fail: "İşlem başarısız.",
  },
  dispute: {
    title: "İki turlu tahkim",
    eyebrow: "Bilirkişi · emanet kilitli kalır",
    claimPlaceholder: "1. tur — iddia ve kanıt özeti",
    openCta: "İtiraz aç",
    opening: "Açılıyor…",
    roundOneClaim: "1. tur iddiası",
    rebutPlaceholder: "2. tur — karşı cevap",
    rebutCta: "Karşı cevabı gönder",
    rebutting: "Gönderiliyor…",
    reportPending: "Bilirkişi raporu bekleniyor. Emanet kilitli kalır.",
    employerRefund: "İşveren iade oranı",
    approve: "Raporu onayla",
    approving: "Onay…",
    reject: "İtiraz et (insan incelemesi)",
    rejecting: "Red…",
    humanReview: "Dosya Super Admin insan incelemesinde. Emanet kilitli kalır.",
    settled: "Tahkim kapandı. İade oranı",
    closed: "İtiraz yalnız kilitli emanette açılır.",
    fail: "Tahkim işlemi başarısız.",
  },
  thread: {
    title: "Sözleşme mesajı",
    eyebrow: "Teslim · revizyon · kanıt",
    empty: "Henüz mesaj yok.",
    placeholder: "Teslim notu, revizyon veya mesaj",
    artifactPlaceholder: "Kanıt URL (isteğe bağlı)",
    artifactCta: "Kanıt",
    send: "Gönder",
    sending: "Gönderiliyor…",
    fail: "Mesaj gönderilemedi.",
    kindText: "Mesaj",
    kindDelivery: "Teslim kanıtı",
    kindRevision: "Revizyon talebi",
  },
  squad: {
    title: "Geçici iş takımı",
    eyebrow: "Pay · ikinci cüzdan yok",
    empty: "Takım yok — serbest bırakınca net tek freelancer’a gider.",
    status: "Durum",
    partnerPlaceholder: "Üye kullanıcı kimliği",
    create: "İki kişilik takım kur",
    creating: "Kuruluyor…",
    fail: "Takım kurulamadı.",
  },
} as const;
