/** Rail SEN aksı — freelancer odası. Müze sen-voice kopyalanmaz. */
export const FREELANCER_SEN = {
  catalog: {
    eyebrow: "İş Pazarı",
    title: "İş Pazarı",
    description: "Güvenli ödeme havuzuyla açık ilanlara teklif ver.",
    createCta: "İlan oluştur",
    live: (count: number) => `Açık ilan — ${count}`,
    unbound: "İlan listesi şu an okunamadı. Biraz sonra yenile.",
  },
  stats: {
    open: (count: number) => `${count} Açık İlan`,
    escrowInline: "Güvenli Ödeme",
    escrowHint: "Güvenli Ödeme (Escrow): teklif onayında bütçe havuza alınır",
    pathInline: "3 Adımda Teslim",
    pathHint: "Teklif → Teslim → Onay",
    revisionInline: "3 Revizyon Hakkı",
    revisionHint: "Teslim sonrası varsayılan 3 revizyon; hak bitince onay öne çıkar",
    barLabel: "İlan özeti",
  },
  list: {
    emptyHint: "Henüz açık ilan bulunmuyor",
    emptyBody:
      "Pazaryerinde ilk ilanı sen oluşturarak onaylı uzmanlardan teklif almaya başlayabilirsin.",
    emptyCta: "İlan Oluştur",
    openCta: "İncele / Teklif Ver",
    inspectBidCta: "İncele / Teklif Ver",
    lockLabel: "Güvenli ödeme",
    boardTitle: "Açık ilanlar",
    filteredEmpty: "Aramanıza uygun ilan bulunamadı.",
    filteredEmptyHint:
      "Arama terimini veya bütçe/ihtiyaç filtrelerini gevşeterek tekrar deneyebilirsin.",
    clearFiltersCta: "Filtreleri Sıfırla",
  },
  filter: {
    searchPlaceholder: "İlanlarda ara...",
    pathwayAll: "Tüm ihtiyaçlar",
    pathwayLabel: "İhtiyaç",
    budgetMinPlaceholder: "Min ₺",
    budgetMaxPlaceholder: "Max ₺",
    budgetLabel: "Bütçe",
    sortLabel: "Sıralama",
    sortNewest: "En Yeni",
    sortBudgetDesc: "Bütçe: Yüksekten Düşüğe",
    sortBudgetAsc: "Bütçe: Düşükten Yükseğe",
    viewGrid: "Izgara",
    viewList: "Liste",
    viewLabel: "Görünüm",
  },
  job: {
    eyebrow: "İlan",
    budgetLabel: "Bütçe",
    formatsLabel: "Teslim formatı",
    durationLabel: "Süre",
    durationDays: (days: number) => `${days} gün`,
    requirementsTitle: "Gereksinimler",
    contractTitle: "Sözleşme",
    contractCta: "Sözleşmeyi aç",
    bidsTitle: "Teklifler",
    bidsEmpty: "Henüz teklif yok.",
    bidsHidden: "Teklifler yalnız ilan sahibine açıktır.",
    bidTitle: "Teklif ver",
    loginLead: "Teklif veya kabul için oturum gerekir.",
    loginCta: "Giriş Yap",
    visaGate: "Bu işe teklif verebilmek için Akademi sertifikası gereklidir.",
    visaRequired: (certName: string) =>
      `Bu işe teklif verebilmek için «${certName}» ihtiyacına uygun Akademi belgesi gerekir.`,
    visaCta: "Eğitime Git",
    visaScopeTitle: "Bu iş için gereken eğitim",
    visaScopeLead: (pathway: string) =>
      `Teklif için «${pathway}» ihtiyacına uygun belgelerden en az biri gerekir. Aşağıdaki eğitimlerden birini tamamla.`,
  },
  create: {
    eyebrow: "İş Pazarı",
    title: "İlan oluştur",
    description:
      "Bütçe, teslim edilecek işi ve ihtiyacı yaz. Teklif kabul edilince tutar güvenli ödemeye alınır; teslim onaylanınca bakiyene geçer.",
    backCta: "İş Pazarı'na dön",
    titleLabel: "Başlık",
    briefLabel: "İş tanımı",
    budgetLabel: "Bütçe (₺)",
    pathwayLabel: "İhtiyaç",
    pathwayHint: "Teklif yalnız bu ihtiyaca uygun Akademi belgesi taşıyan ustalara açılır.",
    band: (minMajor: number, maxMajor: number, holdPercent: number) =>
      `Bütçe bandı: ₺${minMajor} – ₺${maxMajor}. Teklif kabulünde tutar güvenli ödemeye alınır; platform payı %${holdPercent}.`,
    submit: "İlan oluştur",
    pending: "Oluşturuluyor…",
    fail: "İlan açılamadı.",
  },
  escrow: {
    title: "Güvenli Ödeme (Escrow)",
    eyebrow: "Havuz · teslim · onay",
    lead: "İşveren teklifi onayladığında bütçe güvenli havuza alınır. İşi teslim edip işveren onayladığında bakiyene aktarılır.",
    holdNotice: (amount: string, holdPercent: number) =>
      `Kabul, ${amount} tutarını güvenli ödemeye alır (platform payı %${holdPercent}).`,
    pendingLive: "Güvenli ödeme başlatılıyor…",
    steps: (holdPercent: number) =>
      [
        {
          key: "hold" as const,
          label: "Bütçe güvenli havuza alınır",
          detail:
            "İşveren teklifi onaylayınca tutar kilitlenir. Freelancer henüz almaz.",
        },
        {
          key: "release" as const,
          label: "Teslim onayında bakiyene geçer",
          detail: `İşi teslim et; işveren onaylayınca tutar bakiyene aktarılır. Platform payı %${holdPercent}.`,
        },
        {
          key: "dispute" as const,
          label: "Anlaşmazlıkta süreç durur",
          detail:
            "İtiraz durumunda bütçe havuzda bloke edilir. AI asistanı 2 turlu itiraz ve cevap sürecini inceleyerek Sonuç Analiz Raporu yayınlar. Çözülemeyen uyuşmazlıklarda resmi yasal başvuru yolları açıktır.",
        },
      ] as const,
  },
  delivery: {
    title: "Teslim ve revizyon",
    eyebrow: "Nasıl teslim edilir",
    lead: "İş kabul edilince dosyayı yükler, onaya gönderirsin. İşverenin 3 revizyon hakkı vardır.",
    upload: "Dosya Yükle",
    submit: "Onaya Gönder",
    remainingLabel: "Kalan revizyon hakkı",
    remaining: (remaining: number, allowance: number) =>
      `${remaining} / ${allowance} hak`,
    remainingHint: "İşveren teslimden sonra revizyon isteyebilir. Hak bitince onay öne çıkar.",
  },
  accept: {
    cta: "Teklifi kabul et — güvenli ödemeyi başlat",
    pending: "Güvenli ödeme başlatılıyor…",
    fail: "Teklif kabul edilemedi.",
    paymentsClosed: "Güvenli ödeme henüz bağlanmadı",
    paymentsClosedBody:
      "Güvenli ödeme henüz bağlanmadı. İlan ve teklif çalışır; iş kabulünde ödeme alınmaz.",
    paymentsClosedCta: "Anlaşıldı",
  },
  bid: {
    amountLabel: "Teklif (₺)",
    coverLabel: "Kapak notu",
    submit: "Teklif ver",
    pending: "Gönderiliyor…",
    received: "Teklif alındı.",
    fail: "Teklif gönderilemedi.",
    visaDenied: "Bu işe teklif verebilmek için Akademi sertifikası gereklidir.",
    freeBidNote:
      "Teklif ücretsizdir. Bazı işler Akademi sertifikası ister.",
  },
  chat: {
    title: "Sözleşme içi iletişim",
    eyebrow: "Mesaj · dosya · teslim bağlantısı",
    empty: "Henüz yazışma yok.",
    placeholder: "Mesaj, teslim notu veya dosya açıklaması",
    artifactPlaceholder: "Dosya / teslimat bağlantısı (https://…)",
    artifactCta: "Dosyayı aç",
    send: "Gönder",
    sending: "Gönderiliyor…",
    fail: "Mesaj gönderilemedi.",
    kindText: "Mesaj",
    kindDelivery: "Teslim / dosya",
    kindRevision: "Revizyon talebi",
    evidenceNote:
      "Sözleşme içi yazışmalar ve dosya paylaşımları olası bir incelemede delil sayılır.",
  },
  revision: {
    title: "Revizyon hakkı",
    eyebrow: "Şeffaf sayaç · varsayılan 3 hak",
    lead: (allowance: number) =>
      `İşveren teslim sonrası revizyon isteyebilir. Bu işte ${allowance} revizyon hakkı vardır; her talep bir hak düşürür.`,
    usedLabel: "Kullanılan hak",
    remainingLabel: "Kalan hak",
    remainingBadge: (remaining: number, allowance: number) =>
      `${remaining} / ${allowance} hak`,
    requestCta: "Revizyon İstiyorum",
    requesting: "Yazılıyor…",
    notePlaceholder: "Ne düzeltilmeli? Ölçülebilir not yaz.",
    defaultNote: "Revizyon talep edildi.",
    releaseCta: "Teslimatı Onayla",
    releasing: "Onay yazılıyor…",
    releaseHint: "Onaydan sonra tutar bakiyene aktarılır.",
    exhaustedHint: "Revizyon hakkı bitti. Teslimi onayla; ek revizyon yeni iş olarak açılır.",
    freelancerWait: "Revizyon sayacı işverene açıktır. Usta teslim veya düzeltme bekler.",
    closed: "Revizyon, güvenli ödeme başladıktan sonra işler.",
    fail: "İşlem başarısız.",
  },
  contract: {
    eyebrow: "Sözleşme",
    fallbackTitle: "Güvenli ödeme sözleşmesi",
    splitTitle: "Ödeme dağılımı",
    gross: "Toplam",
    platformShare: (percent: number) => `Platform payı (%${percent})`,
    freelancerShare: "Freelancer payı",
    lock: "Ödeme",
    backCta: "İş Pazarı'na dön",
    advancedSummary: "Gelişmiş: revizyon ve anlaşmazlık",
    advancedHint:
      "Mutlu yol teslim ve onaydır. Anlaşmazlık yalnız ihtilaf içindir; ekip paneli yalnız kurulu takımda açılır.",
  },
  actions: {
    release: "Teslimi onayla ve aktar",
    releasing: "Onay yazılıyor…",
    refund: "İade et",
    refunding: "İade…",
    fundedHint: "Tutar güvenli ödemede. Teslim onayı ile bakiyene aktarılır; iade işverene döner.",
    freezeBanner: "Onaydan sonra tutar hesabına geçer. Platform cüzdanına usta payı yazılmaz.",
    fail: "İşlem başarısız.",
  },
  dispute: {
    title: "AI Bilirkişi · Dostane çözüm",
    eyebrow: "İki tur · eşit söz hakkı · bağlayıcı olmayan tavsiye",
    lead:
      "Her turda önce şikayetçi iddiasını, sonra karşı taraf cevabını yazar; ardından AI asistanı inceler. 1. tur raporu itiraz edilirse 2. turda ek delil ve nihai analiz işler. Sonuç Analiz Raporu tavsiye niteliğindedir; mahkeme hükmü değildir. Her iki taraf onaylarsa ödeme dağılır. Çözülemeyen uyuşmazlıklarda karar mercii platform yönetimi değildir; resmi yasal başvuru yolları açıktır.",
    claimPlaceholder: "1. tur — iddia: gerekçe ve kanıt özeti",
    openCta: "Dostane çözümü başlat",
    opening: "Açılıyor…",
    roundOneClaim: "İddia",
    roundOneAnswer: "Cevap",
    rebutPlaceholder: "1. tur — cevap: savunma ve delil özeti",
    rebutCta: "Cevabı gönder",
    rebutting: "Gönderiliyor…",
    reportPending: "1. tur AI analizi üretiliyor. Tutar güvenli ödemede kalır.",
    reportTitle: "1. Tur AI Analizi",
    reportHint: "Bu rapor tavsiye niteliğindedir; mahkeme hükmü değildir. İtiraz ederseniz 2. tur açılır.",
    finalReportTitle: "Sonuç Analiz Raporu",
    employerRefund: "İşveren iade oranı / haklılık",
    approve: "Raporu onayla",
    approving: "Onay…",
    reject: "İtiraz et — 2. tur",
    rejecting: "İtiraz…",
    humanReview:
      "Sonuç Analiz Raporu yayınlandı. Çözülemeyen uyuşmazlıklarda resmi yasal başvuru yolları açıktır; tutar güvenli ödemede kalır.",
    settled: "Tahkim kapandı. İade oranı",
    closed: "İtiraz, güvenli ödeme başladıktan sonra açılır.",
    fail: "Tahkim işlemi başarısız.",
    roundLabels: {
      roundOne: "1. Tur",
      roundTwo: "2. Tur · İtiraz",
      claim: "İddia",
      answer: "Cevap",
      aiRoundOne: "1. Tur AI Analizi",
      appealClaim: "Ek İddia / İtiraz",
      appealAnswer: "Ek Cevap",
      aiFinal: "Nihai AI Analizi",
      idle: "Başlangıç",
      human: "Yasal başvuru",
      settled: "Kapandı",
    },
    legalNote:
      "Bu süreç resmi mahkeme öncesi dostane tavsiye niteliğindedir. Karar mercii platform yönetimi değildir; sonuç AI Analiz Raporu ve yasal mercilere aittir. Uzlaşı sağlanamazsa resmi yasal başvuru yolları açıktır.",
  },
  /** @deprecated Prefer `chat` — ADIM 17 ContractChatConsole. */
  thread: {
    title: "Sözleşme içi iletişim",
    eyebrow: "Mesaj · dosya · teslim bağlantısı",
    empty: "Henüz yazışma yok.",
    placeholder: "Mesaj, teslim notu veya dosya açıklaması",
    artifactPlaceholder: "Dosya / teslimat bağlantısı (https://…)",
    artifactCta: "Dosyayı aç",
    send: "Gönder",
    sending: "Gönderiliyor…",
    fail: "Mesaj gönderilemedi.",
    kindText: "Mesaj",
    kindDelivery: "Teslim / dosya",
    kindRevision: "Revizyon talebi",
  },
  satellite: {
    frozenEyebrow: "Bu fazda kapalı",
    squadTitle: "Takım / Squad",
    squadBody:
      "Takım paylaşımı halkayı döndürmez. Teklif tek ustadan, açık ilandan geçer. Bu yüzey dondurulmuştur.",
    directOfferTitle: "Doğrudan iş teklifi",
    directOfferBody:
      "Doğrudan teklif bu fazda kapalı. İş açık ilan ve vize kapısından yürür.",
  },
  squad: {
    title: "Takım / Squad",
    eyebrow: "Proje takımı",
    teaserTitle: "Takım / Squad kur",
    teaserBody:
      "Proje bazlı geçici takım: üyeleri davet et, hakediş paylarını yüzde ile şeffaf belirle. İş bitince net tutar üyelerin hesaplarına bölünür.",
    teaserCta: "Açık ilanlara bak",
    teaserCreateCta: "Takım / Squad Kur",
    bidAsTeamTitle: "Takım olarak teklif ver",
    bidAsTeamBody:
      "Teklifte takım niyetini ve öngörülen payları yaz. Paylar teklif kabulü sonrası sözleşmede kesinleşir.",
    bidAsTeamToggle: "Takım niyeti ile teklif",
    bidAsTeamSolo: "Tek kişi teklif",
    readyPickLabel: "Hazır Takımlarımdan Seç",
    readyPickEmpty: "Henüz ön takım yok — İş Pazarı'nda Takım / Squad Kur ile hazır kıta kurulur.",
    readyPickManual: "Elle yaz",
    paytrNote: "Ödeme iş bitiminde üyelerin hesaplarına bölünür.",
    honestyNote:
      "Bu takım bir ön gruptur. Takım hazır kıta bekler; bir ilan kabul edildiğinde kesin paylar sözleşmeye yazılır ve ödeme iş bitiminde üyelere aktarılır.",
    empty: "Takım yok — serbest bırakınca net tek freelancer’a gider.",
    status: "Durum",
    leadShare: "Lider payı (%)",
    partnerShare: "Üye payı (%)",
    partnerPlaceholder: "Üye kullanıcı kimliği",
    partnerInvitePlaceholder: "E-posta veya kullanıcı kimliği",
    partnerRolePlaceholder: "Rol (ör. tasarım, backend)",
    teamNameLabel: "Takım adı",
    teamNamePlaceholder: "Örn. Safir Üçlüsü",
    addPartner: "Üye satırı ekle",
    removePartner: "Kaldır",
    shareTotal: "Toplam pay",
    create: "Takım kur",
    creating: "Kuruluyor…",
    update: "Payları güncelle",
    modalTitle: "Bağımsız takım kur",
    modalLead: "İlana bağlı olmadan ön takım kur; teklifte hazır kıta olarak seç.",
    modalSave: "Hazır kıta olarak kaydet",
    modalSaving: "Kaydediliyor…",
    modalClose: "Kapat",
    modalSaved: "Ön takım hazır kıta olarak kaydedildi.",
    fail: "Takım kurulamadı.",
    shareFail: "Pay toplamı %100 olmalıdır.",
    nameFail: "Takım adı gerekli.",
  },
  directOffer: {
    eyebrow: "Doğrudan iş teklifi",
    title: "Doğrudan İş Teklifi",
    buttonCta: "Doğrudan İş Teklifi Et",
    modalLead: "Bu teklif genel pazaryerinde açık ilan olmaz; yalnız seçilen ustanın tezgâhına özel düşer.",
    honestyNote:
      "Bu teklif doğrudan seçilen ustaya özel olarak iletilir. Kabul durumunda tutar güvenli ödemeye alınır.",
    inviteeLabel: "Usta",
    inviteeIdLabel: "Usta kullanıcı kimliği",
    inviteeIdHint: "Teklif yalnız bu kimliğin tezgâhına düşer.",
    inviteeIdPlaceholder: "kullanıcı-id",
    titleLabel: "İş başlığı",
    briefLabel: "İş tanımı",
    budgetLabel: "Özel bütçe (₺)",
    dueDaysLabel: "Teslim süresi (gün)",
    pathwayLabel: "İhtiyaç",
    pathwayHint: "Ustanın bu ihtiyaca uygun Akademi belgesi yoksa teklif gönderilemez.",
    visaOk: "Eğitim uyumu: seçilen ihtiyaç usta belgesiyle eşleşmeli (sunucu denetler).",
    visaBadgesLabel: "Akademi sertifikaları",
    submit: "Teklifi gönder",
    pending: "Gönderiliyor…",
    fail: "Doğrudan teklif gönderilemedi.",
    sent: "Özel iş teklifi ustanın tezgâhına düştü.",
    close: "Kapat",
    inboxTitle: "Özel İş Teklifleri",
    inboxEmpty: "Henüz sana özel doğrudan teklif yok.",
    inboxDue: (days: number) => `${days} gün teslim`,
    acceptCta: "Teklifi kabul et — güvenli ödemeyi başlat",
    accepting: "Güvenli ödeme başlatılıyor…",
    acceptFail: "Doğrudan teklif kabul edilemedi.",
    declineCta: "Teklifi reddet",
    declining: "Reddediliyor…",
    declineFail: "Doğrudan teklif reddedilemedi.",
    holdWarning: "Kabulde tutar güvenli ödemeye alınır. Teslim onayından sonra bakiyene geçer.",
    expertiseTitle: "Sertifikalı uzmanlıklar",
    expertiseLead: "İşveren, beğendiği sertifikalı ustaya doğrudan özel teklif gönderebilir.",
  },
} as const;
