/** Rail SEN aksı — freelancer odası. Müze sen-voice kopyalanmaz. */
export const FREELANCER_SEN = {
  catalog: {
    eyebrow: "Bağımsız iş",
    title: "Freelancer tezgâhı",
    description:
      "İlan, teklif, mesajlaşma çalışır; lisanslı split henüz bağlı olmadığından iş kabulü/emanet (accept) 503 Service Unavailable döner. Cüzdan ile fonlanmaz; usta payı yetkin.ai cüzdanına yazılmaz. İtiraz durumunda tahkim süreci işler.",
    createCta: "İlan oluştur",
    live: (count: number) => `Canlı sicil — ${count} ilan`,
    unbound: "İlan listesi şu an okunamadı. Biraz sonra yenile; uydurma ilan basılmaz.",
  },
  stats: {
    open: (count: number) => `${count} Açık İlan`,
    escrowInline: "Emanet Korumalı",
    escrowHint: "Ödeme henüz bağlanmadı — Pazaryeri split pasif",
    pathInline: "3 Adımda Teslim",
    pathHint: "İlan → Emanet → Teslim",
    revisionInline: "3 Revizyon Hakkı",
    revisionHint: "Teslim sonrası varsayılan 3 revizyon; hak bitince onay öne çıkar",
    barLabel: "Tezgâh özeti",
  },
  list: {
    emptyHint: "Henüz canlı ilan yok. İlk ilanı sen aç; emanet kilit kabulde kurulur.",
    openCta: "İlanı İncele",
    inspectBidCta: "İncele / Teklif Ver",
    lockLabel: "Emanet kilit",
    boardTitle: "Açık ilanlar",
    filteredEmpty: "Kriterlere uygun ilan bulunamadı",
    filteredEmptyHint: "Arama, vize kapsamı veya bütçe süzgecini gevşetmek sonucu açabilir.",
    clearFiltersCta: "Süzgeçleri temizle",
  },
  filter: {
    searchPlaceholder: "İlanlarda ara...",
    pathwayAll: "Tüm Vize Kapsamları",
    pathwayLabel: "Vize kapsamı",
    budgetMinPlaceholder: "Min ₺",
    budgetMaxPlaceholder: "Max ₺",
    budgetLabel: "Bütçe",
    sortLabel: "Sıralama",
    sortNewest: "En Yeni",
    sortBudgetDesc: "Bütçe: Yüksekten Düşüğe",
    sortBudgetAsc: "Bütçe: Düşükten Yükseğe",
    viewGrid: "Izgara",
    viewList: "Liste",
    viewLabel: "Görünüm",
  },
  job: {
    eyebrow: "İlan",
    budgetLabel: "Bütçe",
    contractTitle: "Sözleşme",
    contractCta: "Emanet sözleşmesini aç",
    bidsTitle: "Teklifler",
    bidsEmpty: "Henüz teklif yok.",
    bidsHidden: "Teklifler yalnız ilan sahibine açıktır.",
    bidTitle: "Teklif ver",
    loginLead: "Teklif veya kabul için oturum gerekir.",
    loginCta: "Giriş Yap",
    visaGate: "Bu ilan için Kariyer Vizesi gerekir.",
    visaCta: "Kariyer Vize Defteri'ne Git",
    visaScopeTitle: "Hangi kurs bu ilanı açar?",
    visaScopeLead: (pathway: string) =>
      `Bu ilan «${pathway}» dikeyine kilitli. Aşağıdaki akademi belgelerinden biri yeter.`,
  },
  create: {
    eyebrow: "Bağımsız iş",
    title: "İlan oluştur",
    description:
      "Bütçe, teklif kabulünde ödeme kuruluşunda (PayTR Split) bloke edilir. Kuruluş bağlı değilse kabul 503 döner; cüzdan ile fonlanmaz. Teslim onayı ile kuruluş dağıtır.",
    backCta: "Freelancer'a dön",
    titleLabel: "Başlık",
    briefLabel: "İş tanımı",
    budgetLabel: "Bütçe (₺)",
    pathwayLabel: "Vize kapsamı",
    pathwayHint: "Teklif yalnız bu dikeydeki Kariyer Vizesi ile açılır. Kelime tahmini kullanılmaz.",
    band: (minMajor: number, maxMajor: number, holdPercent: number) =>
      `Bant: ₺${minMajor} – ₺${maxMajor}. Teklif kabulünde tutar ödeme kuruluşunda kilitlenir; platform payı %${holdPercent}. PayTR Split bağlı değilse kabul 503 — cüzdan ile fonlanmaz.`,
    submit: "İlan oluştur",
    pending: "Oluşturuluyor…",
    fail: "İlan açılamadı.",
  },
  escrow: {
    title: "Emanet mühürü",
    eyebrow: "Hold · teslim · tahkim",
    holdNotice: (amount: string, holdPercent: number) =>
      `Kabul, ${amount} tutarını ödeme kuruluşunda kilitler (PayTR Split, platform payı %${holdPercent}). Cüzdan ile fonlanmaz. Anında settlement yoktur.`,
    pendingLive: "Kuruluş kilidi bekleniyor…",
    steps: (holdPercent: number) =>
      [
        {
          key: "hold" as const,
          label: "Kuruluşta kilitli",
          detail:
            "Kabulde tutar ödeme kuruluşunda kilitlenir. yetkin.ai cüzdanından düşülmez; freelancer henüz almaz. Anında settlement yoktur.",
        },
        {
          key: "release" as const,
          label: "Teslim onayı ile aktarılır",
          detail: `İşveren teslimi onaylayınca net kuruluş üzerinden ustaya gider; platform payı (%${holdPercent}) hazineye geçer. Usta payı yetkin.ai cüzdanına yazılmaz.`,
        },
        {
          key: "dispute" as const,
          label: "İtiraz durumunda tahkim süreci işler",
          detail:
            "İki turda eşit söz hakkı: iddia–cevap–AI analizi; itirazda ek tur ve nihai analiz. Emanet kilitli kalır.",
        },
      ] as const,
  },
  accept: {
    cta: "Teklifi kabul et — kuruluşta kilitle",
    pending: "Kuruluş kilidi deneniyor…",
    fail: "Teklif kabul edilemedi.",
    paymentsClosed: "Ödeme henüz bağlanmadı",
    paymentsClosedBody:
      "Ödeme henüz bağlanmadı / pasif. Lisanslı split henüz bağlı değil; iş kabulü (accept) 503 Service Unavailable döner. İlan açık kaldı; sahte kilit veya sahte CREDIT yazılmaz. Cüzdan ile fonlanmaz.",
    paymentsClosedCta: "Anlaşıldı",
  },
  bid: {
    amountLabel: "Teklif (₺)",
    coverLabel: "Kapak notu",
    submit: "Teklif gönder",
    pending: "Gönderiliyor…",
    received: "Teklif alındı.",
    fail: "Teklif gönderilemedi.",
    visaDenied: "Teklif kapalı — Kariyer Vizesi yok.",
    freeBidNote:
      "Teklif %100 ücretsizdir. Kilit ücreti yoktur; nitelikli ilana kapı Kariyer Vizesi (akademi sertifikası) ile açılır.",
  },
  chat: {
    title: "Sözleşme içi iletişim",
    eyebrow: "Mesaj · dosya · teslim bağlantısı",
    empty: "Henüz yazışma yok.",
    placeholder: "Mesaj, teslim notu veya dosya açıklaması",
    artifactPlaceholder: "Dosya / teslimat bağlantısı (https://…)",
    artifactCta: "Dosyayı aç",
    send: "Gönder",
    sending: "Gönderiliyor…",
    fail: "Mesaj gönderilemedi.",
    kindText: "Mesaj",
    kindDelivery: "Teslim / dosya",
    kindRevision: "Revizyon talebi",
    evidenceNote:
      "Sözleşme içi tüm yazışmalar ve dosya paylaşımları olası bir AI Bilirkişi tahkiminde delil niteliği taşır.",
  },
  revision: {
    title: "Revizyon hakkı",
    eyebrow: "Şeffaf sayaç · varsayılan 3 hak",
    lead: (allowance: number) =>
      `İşveren teslim sonrası revizyon isteyebilir. Bu sözleşmede ${allowance} revizyon hakkı vardır; her talep bir hak düşürür.`,
    usedLabel: "Kullanılan hak",
    remainingLabel: "Kalan hak",
    remainingBadge: (remaining: number, allowance: number) =>
      `${remaining} / ${allowance} hak`,
    requestCta: "Revizyon İstiyorum",
    requesting: "Yazılıyor…",
    notePlaceholder: "Ne düzeltilmeli? Ölçülebilir not yaz.",
    defaultNote: "Revizyon talep edildi.",
    releaseCta: "Teslimatı Onayla & Hakedişi Aktar",
    releasing: "Onay yazılıyor…",
    releaseHint:
      "Onay, net tutarı lisanslı kuruluşun (PayTR Split) dağıtımına bırakır. Usta payı yetkin.ai cüzdanına yazılmaz.",
    exhaustedHint:
      "Revizyon hakkı bitti. Onayla ve hakedişi aktar; ek tur yeni emanet farkı ister.",
    freelancerWait: "Revizyon sayacı işverene açıktır. Usta teslim veya düzeltme bekler.",
    closed: "Revizyon yalnız kilitli emanette (FUNDED) işler.",
    fail: "İşlem başarısız.",
  },
  contract: {
    eyebrow: "Sözleşme",
    fallbackTitle: "Emanet sözleşmesi",
    splitTitle: "Ödeme dağılımı",
    gross: "Toplam",
    platformShare: (percent: number) => `Platform payı (%${percent})`,
    freelancerShare: "Freelancer payı",
    lock: "Kilit",
    backCta: "Freelancer'a dön",
    advancedSummary: "Gelişmiş: revizyon ve tahkim",
    advancedHint: "Mutlu yol teslim ve onaydır. Tahkim yalnız ihtilaf içindir; ekip paneli yalnız kurulu takımda açılır.",
  },
  actions: {
    release: "Teslimi onayla ve aktar",
    releasing: "Onay yazılıyor…",
    refund: "İade et",
    refunding: "İade…",
    fundedHint: "Tutar ödeme kuruluşunda kilitlidir. Teslim onayı ile aktarılır; iade işverene döner.",
    freezeBanner:
      "Usta payı yetkin.ai cüzdanına yazılmaz. Teslim onayı, ödemeyi lisanslı kuruluşun dağıtımına bırakır.",
    fail: "İşlem başarısız.",
  },
  dispute: {
    title: "AI Bilirkişi · Dostane çözüm",
    eyebrow: "İki tur · eşit söz hakkı · bağlayıcı olmayan tavsiye",
    lead:
      "Her turda önce şikayetçi iddiasını, sonra karşı taraf cevabını yazar; ardından AI bilirkişi analiz eder. 1. tur raporu itiraz edilirse 2. turda ek delil ve nihai analiz işler. Rapor bağlayıcı değildir; her iki taraf onaylarsa emanet PayTR Split ile dağılır.",
    claimPlaceholder: "1. tur — iddia: gerekçe ve kanıt özeti",
    openCta: "Dostane çözümü başlat",
    opening: "Açılıyor…",
    roundOneClaim: "İddia",
    roundOneAnswer: "Cevap",
    rebutPlaceholder: "1. tur — cevap: savunma ve delil özeti",
    rebutCta: "Cevabı gönder",
    rebutting: "Gönderiliyor…",
    reportPending: "1. tur AI analizi üretiliyor. Emanet ödeme kuruluşunda kilitli kalır.",
    reportTitle: "1. Tur AI Analizi",
    reportHint: "Bu rapor tavsiye niteliğindedir; mahkeme hükmü değildir. İtiraz ederseniz 2. tur açılır.",
    finalReportTitle: "Nihai AI Analizi",
    employerRefund: "İşveren iade oranı / haklılık",
    approve: "Raporu onayla",
    approving: "Onay…",
    reject: "İtiraz et — 2. tur",
    rejecting: "İtiraz…",
    humanReview:
      "2. tur itirazı insan incelemesine alındı (Super Admin). Nihai çözüm bekleniyor; emanet kilitli kalır.",
    settled: "Tahkim kapandı. İade oranı",
    closed: "İtiraz yalnız kilitli emanette açılır.",
    fail: "Tahkim işlemi başarısız.",
    roundLabels: {
      roundOne: "1. Tur",
      roundTwo: "2. Tur · İtiraz",
      claim: "İddia",
      answer: "Cevap",
      aiRoundOne: "1. Tur AI Analizi",
      appealClaim: "Ek İddia / İtiraz",
      appealAnswer: "Ek Cevap",
      aiFinal: "Nihai AI Analizi",
      idle: "Başlangıç",
      human: "İnsan incelemesi",
      settled: "Kapandı",
    },
    legalNote:
      "Bu süreç resmi mahkeme öncesi dostane tavsiye niteliğindedir; uzlaşı sağlanamazsa yasal yollar açıktır.",
  },
  /** @deprecated Prefer `chat` — ADIM 17 ContractChatConsole. */
  thread: {
    title: "Sözleşme içi iletişim",
    eyebrow: "Mesaj · dosya · teslim bağlantısı",
    empty: "Henüz yazışma yok.",
    placeholder: "Mesaj, teslim notu veya dosya açıklaması",
    artifactPlaceholder: "Dosya / teslimat bağlantısı (https://…)",
    artifactCta: "Dosyayı aç",
    send: "Gönder",
    sending: "Gönderiliyor…",
    fail: "Mesaj gönderilemedi.",
    kindText: "Mesaj",
    kindDelivery: "Teslim / dosya",
    kindRevision: "Revizyon talebi",
  },
  squad: {
    title: "Takım / Squad",
    eyebrow: "Proje takımı · PayTR Split",
    teaserTitle: "Takım / Squad kur",
    teaserBody:
      "Proje bazlı geçici takım: üyeleri davet et, hakediş paylarını yüzde ile şeffaf belirle. İş bitince net tutar PayTR Split ile doğrudan üyelerin IBAN’larına bölünür — yetkin.ai’de ikinci cüzdan veya lisanssız kasa yoktur.",
    teaserCta: "Açık ilanlara bak",
    teaserCreateCta: "Takım / Squad Kur",
    bidAsTeamTitle: "Takım olarak teklif ver",
    bidAsTeamBody:
      "Teklifte takım niyetini ve öngörülen payları yaz. Paylar teklif kabulü ve PayTR kilidi sonrası sözleşmede kesinleşir; ödeme üyelerin IBAN’larına Split ile gider.",
    bidAsTeamToggle: "Takım niyeti ile teklif",
    bidAsTeamSolo: "Tek kişi teklif",
    readyPickLabel: "Hazır Takımlarımdan Seç",
    readyPickEmpty: "Henüz ön takım yok — tezgâhta Takım / Squad Kur ile hazır kıta kurulur.",
    readyPickManual: "Elle yaz",
    paytrNote:
      "Ödeme iş bitiminde PayTR Split ile doğrudan üyelerin IBAN’larına bölünür. Platform sanal kasa tutmaz; yetkin.ai cüzdanına usta payı yazılmaz.",
    honestyNote:
      "Bu takım bir ön gruptur. Takım hazır kıta bekler, bir ilan kabul edildiğinde kesin paylar sözleşmeye kilitlenir ve ödeme iş bitiminde PayTR Split ile doğrudan IBAN’lara aktarılır. Sanal kasa veya ikinci cüzdan yoktur.",
    empty: "Takım yok — serbest bırakınca net tek freelancer’a gider.",
    status: "Durum",
    leadShare: "Lider payı (%)",
    partnerShare: "Üye payı (%)",
    partnerPlaceholder: "Üye kullanıcı kimliği",
    partnerInvitePlaceholder: "E-posta veya kullanıcı kimliği",
    partnerRolePlaceholder: "Rol (ör. tasarım, backend)",
    teamNameLabel: "Takım adı",
    teamNamePlaceholder: "Örn. Safir Üçlüsü",
    addPartner: "Üye satırı ekle",
    removePartner: "Kaldır",
    shareTotal: "Toplam pay",
    create: "Takım kur",
    creating: "Kuruluyor…",
    update: "Payları güncelle",
    modalTitle: "Bağımsız takım kur",
    modalLead: "İlana bağlı olmadan ön takım kur; teklifte hazır kıta olarak seç.",
    modalSave: "Hazır kıta olarak kaydet",
    modalSaving: "Kaydediliyor…",
    modalClose: "Kapat",
    modalSaved: "Ön takım hazır kıta olarak kaydedildi.",
    fail: "Takım kurulamadı.",
    shareFail: "Pay toplamı %100 olmalıdır.",
    nameFail: "Takım adı gerekli.",
  },
  directOffer: {
    eyebrow: "Doğrudan iş teklifi",
    title: "Doğrudan İş Teklifi",
    buttonCta: "Doğrudan İş Teklifi Et",
    modalLead: "Bu teklif genel pazaryerinde açık ilan olmaz; yalnız seçilen ustanın tezgâhına özel düşer.",
    honestyNote:
      "Bu teklif doğrudan usta cüzdanına ve tezgâhına özel olarak iletilir. Kabul durumunda tutar ödeme kuruluşunda kilitlenir.",
    inviteeLabel: "Usta",
    inviteeIdLabel: "Usta kullanıcı kimliği",
    inviteeIdHint: "Teklif yalnız bu kimliğin tezgâhına düşer.",
    inviteeIdPlaceholder: "kullanıcı-id",
    titleLabel: "İş başlığı",
    briefLabel: "İş tanımı",
    budgetLabel: "Özel bütçe (₺)",
    dueDaysLabel: "Teslim süresi (gün)",
    pathwayLabel: "Vize kapsamı",
    pathwayHint: "Ustanın bu dikeyde Kariyer Vizesi yoksa teklif gönderilemez.",
    visaOk: "Vize uyumu: seçilen dikey usta rozetleriyle eşleşmeli (sunucu denetler).",
    visaBadgesLabel: "Kariyer Vizesi rozetleri",
    submit: "Teklifi gönder",
    pending: "Gönderiliyor…",
    fail: "Doğrudan teklif gönderilemedi.",
    sent: "Özel iş teklifi ustanın tezgâhına düştü.",
    close: "Kapat",
    inboxTitle: "Özel İş Teklifleri",
    inboxEmpty: "Henüz sana özel doğrudan teklif yok.",
    inboxDue: (days: number) => `${days} gün teslim`,
    acceptCta: "Teklifi kabul et — kuruluşta kilitle",
    accepting: "Kuruluş kilidi deneniyor…",
    acceptFail: "Doğrudan teklif kabul edilemedi.",
    declineCta: "Teklifi reddet",
    declining: "Reddediliyor…",
    declineFail: "Doğrudan teklif reddedilemedi.",
    holdWarning:
      "Kabulde tutar PayTR Split ile ödeme kuruluşunda kilitlenir. yetkin.ai cüzdanına usta payı yazılmaz; sahte settlement yoktur.",
    expertiseTitle: "Vizeli uzmanlıklar",
    expertiseLead: "İşveren, beğendiği vizeli ustaya doğrudan özel teklif gönderebilir.",
  },
} as const;
