/** Rail SEN aksı — kurumsal oda. Müze sen-voice kopyalanmaz. */
export const KURUMSAL_SEN = {
  eyebrow: "Şirket beyni",
  title: "Kurumsal",
  description: "Şirket profilini kur, ilanı emanete mühürle, Freelancer veya DevLabs’e iş ver.",
  sealedCta: "Mühürlü ilan",
  metricsTitle: "Şirket finansman özeti",
  legalNameLabel: "Unvan",
  noProfile: "profil yok",
  sealedLabel: "Mühürlü ilan",
  sealedHint: (total: number) => `${total} toplam`,
  escrowLabel: "Emanet kilit",
  escrowHint: "Mühürlü ve ödüllendirilmiş ilanlar",
  profileTitle: "Şirket profili",
  loginLead: "Şirket paneli için",
  loginCta: "oturum",
  loginTail: "gerekir.",
  unbound: "Liste henüz yüklenemedi — örnek düzen",
  create: {
    eyebrow: "Şirket beyni",
    title: "Mühürlü iş ilanı",
    description: "Bütçe, ilan anında emanete kilitlenir. Katalog tabanı iş ilanı alt sınırıdır.",
    backCta: "Kurumsala dön",
  },
  offer: {
    title: "Teklif ver",
    coverLabel: "Kapak notu",
    submit: "Teklif gönder",
    pending: "Gönderiliyor…",
    received: "Teklif alındı.",
    fail: "Teklif gönderilemedi.",
    visaGate:
      "Mühürlü ilana teklif Kariyer Vizesi (akademi sertifikası) ister. Emanet tutarı vizeden bağımsızdır.",
    visaCta: "Kariyer pasaportu",
    listTitle: "Teklifler",
    empty: "Henüz teklif yok.",
  },
} as const;
