#!/usr/bin/env tsx
/**
 * OpenAPI components.schemas → apps/rail-is/src/generated/v1.ts
 * Kernel/Prisma bu bundle'a girmez. --check sapmayı kırar.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const ROOT = process.cwd();
const OPENAPI = join(ROOT, "lib/kernel/http/openapi-v1.json");
const TARGET = join(ROOT, "apps/rail-is/src/generated/v1.ts");
const check = process.argv.includes("--check");

type JsonSchema = {
  type?: string | string[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  additionalProperties?: boolean | JsonSchema;
  enum?: unknown[];
  const?: unknown;
  items?: JsonSchema;
  nullable?: boolean;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  allOf?: JsonSchema[];
  $ref?: string;
  description?: string;
  format?: string;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
};

type OpenApiDoc = {
  components?: { schemas?: Record<string, JsonSchema> };
};

function refName(ref: string): string {
  const parts = ref.split("/");
  return parts[parts.length - 1] ?? "Unknown";
}

function tsFromSchema(schema: JsonSchema, indent = 0): string {
  if (schema.$ref) {
    return refName(schema.$ref);
  }
  if (schema.enum && schema.enum.length > 0) {
    const values = schema.enum.map((item) => JSON.stringify(item)).join(" | ");
    if (schema.nullable) {
      return `${values} | null`;
    }
    return values;
  }
  if (schema.const !== undefined) {
    const value = JSON.stringify(schema.const);
    return schema.nullable ? `${value} | null` : value;
  }
  const unions = schema.anyOf ?? schema.oneOf;
  if (unions && unions.length > 0) {
    return unions.map((item) => tsFromSchema(item, indent)).join(" | ");
  }
  if (schema.allOf && schema.allOf.length > 0) {
    return schema.allOf.map((item) => tsFromSchema(item, indent)).join(" & ");
  }
  const types = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
  if (types.includes("null") && types.length === 1) {
    return "null";
  }
  const nonNull = types.filter((item) => item !== "null");
  const nullable = schema.nullable === true || types.includes("null");
  let inner = "unknown";
  if (nonNull[0] === "string" || (!nonNull[0] && schema.format === "uuid")) {
    inner = "string";
  } else if (nonNull[0] === "integer" || nonNull[0] === "number") {
    inner = "number";
  } else if (nonNull[0] === "boolean") {
    inner = "boolean";
  } else if (nonNull[0] === "array") {
    inner = `Array<${schema.items ? tsFromSchema(schema.items, indent) : "unknown"}>`;
  } else if (nonNull[0] === "object" || schema.properties) {
    inner = objectToTs(schema, indent);
  }
  return nullable && inner !== "unknown" ? `${inner} | null` : inner;
}

function objectToTs(schema: JsonSchema, indent: number): string {
  const props = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const pad = "  ".repeat(indent + 1);
  const close = "  ".repeat(indent);
  const lines = Object.entries(props).map(([key, value]) => {
    const optional = required.has(key) ? "" : "?";
    return `${pad}${JSON.stringify(key)}${optional}: ${tsFromSchema(value, indent + 1)};`;
  });
  if (lines.length === 0) {
    return "Record<string, unknown>";
  }
  return `{\n${lines.join("\n")}\n${close}}`;
}

function emit(): string {
  const document = JSON.parse(readFileSync(OPENAPI, "utf8")) as OpenApiDoc;
  const schemas = document.components?.schemas ?? {};
  const blocks: string[] = [
    "/**",
    " * AUTO-GENERATED by scripts/generate-rail-v1-dron-types.ts — do not edit.",
    " * Source: lib/kernel/http/openapi-v1.json",
    " * Kernel / Zod / Prisma this bundle'a girmez.",
    " */",
    "",
    'export const RAIL_V1_API_VERSION = "1" as const;',
    "",
    "export type RailV1OkBody<T extends Record<string, unknown> = Record<string, unknown>> = {",
    "  ok: true;",
    "  error: null;",
    "  requestId: string;",
    "  apiVersion: typeof RAIL_V1_API_VERSION;",
    "  data: T;",
    "};",
    "",
    "export type RailV1FailBody = {",
    "  ok: false;",
    "  error: string;",
    "  requestId: string;",
    "  apiVersion: typeof RAIL_V1_API_VERSION;",
    "  data: null;",
    "};",
    "",
    "export type RailV1Envelope<T extends Record<string, unknown> = Record<string, unknown>> =",
    "  | RailV1OkBody<T>",
    "  | RailV1FailBody;",
    "",
  ];
  for (const [name, schema] of Object.entries(schemas)) {
    blocks.push(`export type ${name} = ${tsFromSchema(schema)};`, "");
  }
  return `${blocks.join("\n")}\n`;
}

const serialized = emit();
if (check) {
  if (!existsSync(TARGET)) {
    console.error("generated/v1.ts yok — npm run generate:v1-client");
    process.exit(1);
  }
  const onDisk = readFileSync(TARGET, "utf8");
  if (onDisk !== serialized) {
    console.error("generated/v1.ts sapması — npm run generate:v1-client");
    process.exit(1);
  }
  console.log("verify:v1-client OK — dron tipleri OpenAPI ile örtüşür.");
  process.exit(0);
}

mkdirSync(dirname(TARGET), { recursive: true });
writeFileSync(TARGET, serialized, "utf8");
console.log(`wrote ${TARGET}`);
