/**
 * Kenar projeksiyonu. Elle yazılmaz.
 * Kaynak: senaryo başlığı ve katalog sırası.
 * Yenile: npx tsx scripts/sync-junior-lesson-face.ts
 */
export const JUNIOR_LESSON_FACE = [
  { key: "jr_06_mat-1", title: "Üslü ifadede taban ve üs" },
  { key: "jr_06_mat-2", title: "İşlem önceliği" },
  { key: "jr_06_mat-3", title: "Ortak çarpan ve dağılma" },
  { key: "jr_06_mat-4", title: "Doğal sayı problemleri" },
  { key: "jr_06_mat-5", title: "Çarpanlar, katlar ve bölünebilme" },
  { key: "jr_06_mat-6", title: "Asal sayılar ve asal çarpanlar" },
  { key: "jr_06_mat-7", title: "Ortak bölen ve ortak kat" },
  { key: "jr_06_mat-8", title: "Kümeler" },
  { key: "jr_06_mat-9", title: "Tam sayılar ve mutlak değer" },
  { key: "jr_06_mat-10", title: "Kesirleri karşılaştırma ve sıralama" },
  { key: "jr_06_mat-11", title: "Payda aynıyken toplama" },
  { key: "jr_06_mat-12", title: "Paydayı eşitleyerek toplama" },
  { key: "jr_06_mat-13", title: "Kesirlerde çarpma ve bölme" },
  { key: "jr_06_mat-14", title: "Ondalık gösterimi okumak" },
  { key: "jr_06_mat-15", title: "Ondalık sayılarla işlem" },
  { key: "jr_06_mat-16", title: "Oran" },
  { key: "jr_06_mat-17", title: "Cebirsel ifadeler" },
  { key: "jr_06_mat-18", title: "Veri toplama ve değerlendirme" },
  { key: "jr_06_mat-19", title: "Veri analizi" },
  { key: "jr_06_mat-20", title: "Komşu, tümler, bütünler ve ters açılar" },
  { key: "jr_06_mat-21", title: "Paralelkenar ve üçgenin alanı" },
  { key: "jr_06_mat-22", title: "Alan ölçü birimleri ve arazi" },
  { key: "jr_06_mat-23", title: "Çember" },
  { key: "jr_06_mat-24", title: "Prizmalar ve hacim" },
  { key: "jr_06_mat-25", title: "Sıvı ölçme" },
  { key: "jr_06_fen-1", title: "Güneş sistemindeki gezegenler" },
  { key: "jr_06_fen-2", title: "Güneş ve Ay tutulması" },
  { key: "jr_06_fen-3", title: "Destek ve hareket sistemi" },
  { key: "jr_06_fen-4", title: "Sindirim sistemi" },
  { key: "jr_06_fen-5", title: "Dolaşım sistemi" },
  { key: "jr_06_fen-6", title: "Kan grupları ve kan bağışı" },
  { key: "jr_06_fen-7", title: "Solunum sistemi" },
  { key: "jr_06_fen-8", title: "Boşaltım sistemi" },
  { key: "jr_06_fen-9", title: "Bileşke kuvvet" },
  { key: "jr_06_fen-10", title: "Sabit süratli hareket" },
  { key: "jr_06_fen-11", title: "Maddenin tanecikli yapısı" },
  { key: "jr_06_fen-12", title: "Yoğunluk" },
  { key: "jr_06_fen-13", title: "Madde ve ısı" },
  { key: "jr_06_fen-14", title: "Sesin yayılması" },
  { key: "jr_06_fen-15", title: "Sesin maddeyle etkileşimi" },
  { key: "jr_06_fen-16", title: "Denetleyici ve düzenleyici sistemler" },
  { key: "jr_06_fen-17", title: "Duyu organları" },
  { key: "jr_06_fen-18", title: "Sistemlerin sağlığı" },
  { key: "jr_06_fen-19", title: "İletken ve yalıtkan maddeler" },
  { key: "jr_06_fen-20", title: "Elektriksel direnç" },
  { key: "jr_06_turkce-1", title: "Gerçek, mecaz ve terim anlam" },
  { key: "jr_06_turkce-2", title: "Eş anlam, zıt anlam ve yakın anlamlı sözcükler" },
  { key: "jr_06_turkce-3", title: "Sözcükte çok anlamlılık ve söz varlığı" },
  { key: "jr_06_turkce-4", title: "Söz sanatları" },
  { key: "jr_06_turkce-5", title: "Öznel ve nesnel anlatımlı cümleler" },
  { key: "jr_06_turkce-6", title: "Neden-sonuç, amaç-sonuç ve koşul-sonuç cümleleri" },
  { key: "jr_06_turkce-7", title: "Cümlede örtülü anlam ve cümle yorumlama" },
  { key: "jr_06_turkce-8", title: "Paragrafta ana fikir ve konu" },
  { key: "jr_06_turkce-9", title: "Paragrafta yardımcı fikirler" },
  { key: "jr_06_turkce-10", title: "Paragrafın yapısı" },
  { key: "jr_06_turkce-11", title: "Anlatım biçimleri ve düşünceyi geliştirme yolları" },
  { key: "jr_06_turkce-12", title: "Metin türleri" },
  { key: "jr_06_turkce-13", title: "Deyimler ve atasözleri" },
  { key: "jr_06_turkce-14", title: "İsim ve fiil kökü" },
  { key: "jr_06_turkce-15", title: "Yapım ekleri ve sözcük türetme" },
  { key: "jr_06_turkce-16", title: "İsim çekim ekleri" },
  { key: "jr_06_turkce-17", title: "Büyük harfler ve sayıların yazımı" },
  { key: "jr_06_turkce-18", title: "de, da, ki ve mi'nin yazımı" },
  { key: "jr_06_turkce-19", title: "Nokta, virgül, noktalı virgül ve iki nokta" },
  { key: "jr_06_turkce-20", title: "Üç nokta, soru, ünlem, kesme ve tırnak" },
  { key: "jr_06_ing_main-1", title: "Daily routines ve saati söylemek" },
  { key: "jr_06_ing_main-2", title: "He, she ve it ile simple present" },
  { key: "jr_06_ing_main-3", title: "Yiyecek, içecek ve likes, dislikes" },
  { key: "jr_06_ing_main-4", title: "Rica etmek ve some, any" },
  { key: "jr_06_ing_main-5", title: "Şehirde şu an ne oluyor" },
  { key: "jr_06_ing_main-6", title: "Bigger ve cheaper ile karşılaştırma" },
  { key: "jr_06_ing_main-7", title: "Sunny, rainy ve cold" },
  { key: "jr_06_ing_main-8", title: "Happy, anxious ve scared" },
  { key: "jr_06_ing_main-9", title: "Lunaparkta rides ve fun" },
  { key: "jr_06_ing_main-10", title: "Fuarda duyguyu söylemek" },
  { key: "jr_06_ing_main-11", title: "Doctor, architect ve vet" },
  { key: "jr_06_ing_main-12", title: "Was ve were ile geçmiş tarih" },
  { key: "jr_06_ing_main-13", title: "Visited, swam ve played" },
  { key: "jr_06_ing_main-14", title: "Tatil etkinliği ve hava" },
  { key: "jr_06_ing_main-15", title: "Kitap okumaktan söz etmek" },
  { key: "jr_06_ing_main-16", title: "In, on, under, behind ve next to" },
  { key: "jr_06_ing_main-17", title: "Çevreyi korumak ve recycling" },
  { key: "jr_06_ing_main-18", title: "Should ve shouldn't" },
  { key: "jr_06_ing_main-19", title: "Okul seçimi ve voting" },
  { key: "jr_06_ing_main-20", title: "Hak, sorumluluk ve sınıf kuralı" },
  { key: "jr_06_sosyal-1", title: "Değerlerimiz ve toplumdaki roller" },
  { key: "jr_06_sosyal-2", title: "Toplumsal uyum ve yardımlaşma" },
  { key: "jr_06_sosyal-3", title: "Önyargıları kırıyoruz" },
  { key: "jr_06_sosyal-4", title: "Hak, sorumluluk ve özgürlük" },
  { key: "jr_06_sosyal-5", title: "İlk Türk devletleri ve Orta Asya Türk kültürü" },
  { key: "jr_06_sosyal-6", title: "İslamiyet'in doğuşu ve yayılışı" },
  { key: "jr_06_sosyal-7", title: "Türklerin İslamiyet'i kabulü ve ilk Türk-İslam devletleri" },
  { key: "jr_06_sosyal-8", title: "İpek Yolu ve kültürel etkileşim" },
  { key: "jr_06_sosyal-9", title: "Mutlak konum ve göreceli konum" },
  { key: "jr_06_sosyal-10", title: "Türkiye'nin coğrafi konumu ve iklim çeşitliliği" },
  { key: "jr_06_sosyal-11", title: "Türkiye'nin yeryüzü şekilleri ve bitki örtüsü" },
  { key: "jr_06_sosyal-12", title: "Ülkemizin kaynakları ve ekonomik faaliyetler" },
  { key: "jr_06_sosyal-13", title: "Doğal kaynaklarımız ve sürdürülebilirlik" },
  { key: "jr_06_sosyal-14", title: "Vergilerimiz ve vatandaşlık sorumluluğu" },
  { key: "jr_06_sosyal-15", title: "Nitelikli insan gücü ve meslek seçimi" },
  { key: "jr_06_sosyal-16", title: "Demokrasinin gelişimi ve yönetim biçimleri" },
  { key: "jr_06_sosyal-17", title: "Haklarımızın güvencesi: anayasa ve demokrasi" },
  { key: "jr_06_sosyal-18", title: "Devletin organları" },
  { key: "jr_06_sosyal-19", title: "Komşularımız ve uluslararası ilişkiler" },
  { key: "jr_06_sosyal-20", title: "Ülkeler arası ticaret ve kültürel etkileşim" },
  { key: "jr_06_ing-1", title: "Saate göre selam" },
  { key: "jr_06_ing-2", title: "Adını sormak" },
  { key: "jr_06_alm-1", title: "Günün selamı" },
  { key: "jr_06_alm-2", title: "Adını söylemek" },
  { key: "jr_06_fra-1", title: "Bonjour demek" },
  { key: "jr_06_fra-2", title: "Adını sormak" },
  { key: "jr_06_siyer-1", title: "Doğru söz" },
  { key: "jr_06_siyer-2", title: "Merhamet" },
  { key: "jr_06_kod-1", title: "Komut sırası" },
  { key: "jr_06_kod-2", title: "Hatalı adımı bulmak" },
  { key: "jr_06_arp-1", title: "Selam vermek" },
  { key: "jr_06_arp-2", title: "Sağdan sola okumak" },
] as const;

export type JuniorLessonFaceKey = (typeof JUNIOR_LESSON_FACE)[number]["key"];
